### ISSUE TITLE
Regression in 2026.7.0 – stream_server fails to compile (network API change)

### ISSUE THREAD

**Issue by dkarios** [OttoWinter/esphomeyaml#17698]
### The problem

After updating ESPHome to 2026.7.0, any ESP8266 device using the stream_server component fails to compile.
The error indicates that esphome::network::get_use_address() no longer exists in the network API.

This function was removed or renamed internally, but the stream_server component still calls it, causing a compile-time failure.

Error log:

Code
error: 'get_use_address' is not a member of 'esphome::network';
did you mean 'get_use_address_to'?
Expected behavior:  
stream_server should compile normally, as in ESPHome 2026.6.5.

Actual behavior:  
Compilation fails on ESP8266 targets.

Version:  
ESPHome 2026.7.0
PlatformIO: espressif8266@4.2.1

Notes:  
This is a regression introduced in 2026.7.0.
The changelog does not mention the removal of get_use_address(), but the network API appears to have changed internally.

### Which version of ESPHome has the issue?

2026.7.0

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Component causing the issue

stream_server

### YAML Config

```yaml
esphome:
  name: paradox
  friendly_name: Paradox Alarm System
  min_version: 2026.4.0
  name_add_mac_suffix: false

esp8266:
  board: esp01_1m

# Enable logging
logger:
  # this is required if you use the same RX/TX pins as for logging
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: "*********************"  

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# this is for UART-to-IP conversion as you cannot tap into UART directly over network
external_components:
  - source: github://oxan/esphome-stream-server

# UART (serial) settings - pin21 and pin20 should be adjusted based on tx/rx port location on your board
uart:
  - id: paradox_uart
    tx_pin: GPIO1
    rx_pin: GPIO3
    baud_rate: 9600

# UART-to-IP server settings, this port will be used to connect from Home Assistant
stream_server:
  uart_id: paradox_uart
  port: 10000

# just a sensor to report if HA is connected to the board or not
binary_sensor:
  - platform: stream_server
    connected:
      name: Paradox UART
```

### Anything in the logs that might be useful for us?

```txt

```

**Comment by bdraco** [comment]
It was removed in https://github.com/esphome/esphome/pull/17432

There is an example on the new method

**Comment by pputerla** [comment]
It's being addresed in https://github.com/oxan/esphome-stream-server/pull/71

Until it's merged you can use fork https://github.com/grob6000/esphome-stream-server
