### PR TITLE
Drop 128x160 ESP-32 camera resolution

### LINKED ISSUE #1884: espcam fails to compile with espressif@3.1.0
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io, Mac OS pip

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESPcam32

**ESPHome version (latest production, beta, dev branch)**

v1.16.2

**Affected component:**

https://esphome.io/components/esp32_camera.html

**Description of problem:**

Build fails

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: esp32cam
  platform: ESP32
  board: esp32cam
  arduino_version: espressif32@3.1.0
  build_path: esp32cam
  platformio_options: {}
  includes: []
  libraries: []

```

**Logs (if applicable):**

```
Compiling .pioenvs/esp32cam/src/esphome/components/json/json_util.cpp.o
src/esphome/components/esp32_camera/esp32_camera.cpp: In member function 'virtual void esphome::esp32_camera::ESP32Camera::dump_config()':
src/esphome/components/esp32_camera/esp32_camera.cpp:58:10: error: 'FRAMESIZE_QQVGA2' was not declared in this scope
     case FRAMESIZE_QQVGA2:
          ^
src/esphome/components/esp32_camera/esp32_camera.cpp: In member function 'void esphome::esp32_camera::ESP32Camera::set_frame_size(esphome::esp32_camera::ESP32CameraFrameSize)':
src/esphome/components/esp32_camera/esp32_camera.cpp:213:34: error: 'FRAMESIZE_QQVGA2' was not declared in this scope
       this->config_.frame_size = FRAMESIZE_QQVGA2;
                                  ^
*** [.pioenvs/esp32cam/src/esphome/components/esp32_camera/esp32_camera.cpp.o] Error 1

```

**Additional information and things you've tried:**

### PR DESCRIPTION
**Pull request by oxan**
# What does this implement/fix? 

Since the addition of OV5640 support in the ESP-32 camera driver in March 2020, it no longer provides the FRAMESIZE_QQVGA2 type. This was imported in Arduino ESP32 core 1.0.5, so compilation was broken from that version onwards.

Drop the support for this resolution, as this specific resolution does not seem to be useful enough for it to be worthwhile to make it conditionally available depending on the used Arduino version (which is further complicated by the fact that Arduino doesn't provide a numeric version define).

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (this will require users to update their yaml configuration files to keep working)

Technically this is a breaking change for users using this resolution, but I don't think we should bother to do anything about that beyond a changelog entry.

**Related issue or feature (if applicable):** fixes esphome/issues#1884

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>
  
# Test Environment

- [ ] ESP32
- [ ] ESP8266
- [ ] Windows
- [ ] Mac OS
- [x] Linux

## Example entry for `config.yaml`:
N/A

# Explain your changes

It fixes compilation.

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by oxan** [comment]
I also added the ESP-32 camera to one of the test YAML files, so that it'll at least get compile tested in CI from now on in the hopes that'll catch similar breakage faster from now on :)

**Review by agners — APPROVED** [review]
This actually fixes compiling the Camera component with Arduino SDK 1.0.6.

**Comment by oxan** [comment]
This is esphome/esphome-docs#1192 btw, I see I forgot to fill in the PR number.
