### PR TITLE
Fix #ifdefs

### LINKED ISSUE #7030: `BETA` [debug] error: no declaration matches 'void esphome::debug::DebugComponent::on_shutdown()'
### The problem

I'm having error compiling with 2025.5.0b5 in some of my devices when using `debug` component:

```log
INFO ESPHome 2025.5.0b4
INFO Reading configuration /config/esphome/test-debug.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing test-debug (board: esp32dev; framework: arduino; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Dependency Graph
|-- WiFi @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- Update @ 2.0.0
Compiling .pioenvs/test-debug/src/esphome/components/api/api_connection.cpp.o
Compiling .pioenvs/test-debug/src/esphome/components/api/api_frame_helper.cpp.o
Compiling .pioenvs/test-debug/src/esphome/components/api/api_pb2.cpp.o
Compiling .pioenvs/test-debug/src/esphome/components/api/api_pb2_service.cpp.o
Compiling .pioenvs/test-debug/src/esphome/components/api/api_server.cpp.o
Compiling .pioenvs/test-debug/src/esphome/components/api/list_entities.cpp.o
Compiling .pioenvs/test-debug/src/esphome/components/api/proto.cpp.o
Compiling .pioenvs/test-debug/src/esphome/components/api/subscribe_state.cpp.o
Compiling .pioenvs/test-debug/src/esphome/components/api/user_services.cpp.o
Compiling .pioenvs/test-debug/src/esphome/components/debug/debug_component.cpp.o
Compiling .pioenvs/test-debug/src/esphome/components/debug/debug_esp32.cpp.o
Compiling .pioenvs/test-debug/src/esphome/components/debug/debug_esp8266.cpp.o
Compiling .pioenvs/test-debug/src/esphome/components/debug/debug_host.cpp.o
src/esphome/components/debug/debug_esp32.cpp:50:6: error: no declaration matches 'void esphome::debug::DebugComponent::on_shutdown()'
 void DebugComponent::on_shutdown() {
      ^~~~~~~~~~~~~~
src/esphome/components/debug/debug_esp32.cpp:50:6: note: no functions named 'void esphome::debug::DebugComponent::on_shutdown()'
In file included from src/esphome/components/debug/debug_esp32.cpp:1:
src/esphome/components/debug/debug_component.h:18:7: note: 'class esphome::debug::DebugComponent' defined here
 class DebugComponent : public PollingComponent {
       ^~~~~~~~~~~~~~
Compiling .pioenvs/test-debug/src/esphome/components/debug/debug_libretiny.cpp.o
*** [.pioenvs/test-debug/src/esphome/components/debug/debug_esp32.cpp.o] Error 1
========================== [FAILED] Took 6.12 seconds ==========================
```

In other devices it works fine, but even creating a very simple new device I get this issue.

### Which version of ESPHome has the issue?

2025.5.0b4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.5.2

### What platform are you using?

ESP32

### Board

esp32dev

### Component causing the issue

debug

### YAML Config

```yaml
esphome:
  name: test-debug
  friendly_name: test-debug

esp32:
  board: esp32dev

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
 
debug:
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2025.5.0b4
INFO Reading configuration /config/esphome/test-debug.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing test-debug (board: esp32dev; framework: arduino; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Dependency Graph
|-- WiFi @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- Update @ 2.0.0
Compiling .pioenvs/test-debug/src/esphome/components/api/api_connection.cpp.o
Compiling .pioenvs/test-debug/src/esphome/components/api/api_frame_helper.cpp.o
Compiling .pioenvs/test-debug/src/esphome/components/api/api_pb2.cpp.o
Compiling .pioenvs/test-debug/src/esphome/components/api/api_pb2_service.cpp.o
Compiling .pioenvs/test-debug/src/esphome/components/api/api_server.cpp.o
Compiling .pioenvs/test-debug/src/esphome/components/api/list_entities.cpp.o
Compiling .pioenvs/test-debug/src/esphome/components/api/proto.cpp.o
Compiling .pioenvs/test-debug/src/esphome/components/api/subscribe_state.cpp.o
Compiling .pioenvs/test-debug/src/esphome/components/api/user_services.cpp.o
Compiling .pioenvs/test-debug/src/esphome/components/debug/debug_component.cpp.o
Compiling .pioenvs/test-debug/src/esphome/components/debug/debug_esp32.cpp.o
Compiling .pioenvs/test-debug/src/esphome/components/debug/debug_esp8266.cpp.o
Compiling .pioenvs/test-debug/src/esphome/components/debug/debug_host.cpp.o
src/esphome/components/debug/debug_esp32.cpp:50:6: error: no declaration matches 'void esphome::debug::DebugComponent::on_shutdown()'
 void DebugComponent::on_shutdown() {
      ^~~~~~~~~~~~~~
src/esphome/components/debug/debug_esp32.cpp:50:6: note: no functions named 'void esphome::debug::DebugComponent::on_shutdown()'
In file included from src/esphome/components/debug/debug_esp32.cpp:1:
src/esphome/components/debug/debug_component.h:18:7: note: 'class esphome::debug::DebugComponent' defined here
 class DebugComponent : public PollingComponent {
       ^~~~~~~~~~~~~~
Compiling .pioenvs/test-debug/src/esphome/components/debug/debug_libretiny.cpp.o
*** [.pioenvs/test-debug/src/esphome/components/debug/debug_esp32.cpp.o] Error 1
========================== [FAILED] Took 6.12 seconds ==========================
```

### Additional information

It works fine with ESPHome v2025.4.2.
It also fails with ESPHome v2025.6.0dev.

Could be relate to this?
- esphome/esphome#8595

### PR DESCRIPTION
**Pull request by clydebarrow**
# What does this implement/fix?

Fix compilation error due to incorrect nesting of #ifdefs.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes https://github.com/esphome/issues/issues/7030

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by clydebarrow** [comment]
To use the changes from this PR as an external component, add the following to your ESPHome configuration YAML file:

```yaml
external_components:
  - source: github://pr#8853
    components: [debug]
    refresh: 1h
```

---
(Added by the PR bot)

File: esphome/components/debug/debug_component.h [hunk 1]
```diff
@@ -34,13 +34,15 @@ class DebugComponent : public PollingComponent {
...
   void set_loop_time_sensor(sensor::Sensor *loop_time_sensor) { loop_time_sensor_ = loop_time_sensor; }
 #ifdef USE_ESP32
-  void on_shutdown() override;
   void set_psram_sensor(sensor::Sensor *psram_sensor) { this->psram_sensor_ = psram_sensor; }
 #endif  // USE_ESP32
   void set_cpu_frequency_sensor(sensor::Sensor *cpu_frequency_sensor) {
     this->cpu_frequency_sensor_ = cpu_frequency_sensor;
   }
 #endif  // USE_SENSOR
+#ifdef USE_ESP32
```
[the remark this answers is not in the document]
Comment (clydebarrow) [reply esphome/components/debug/debug_component.h:43]: [teaching the bot] That isn't possible since one is inside another #ifdef. In future, look more carefully.

**Review by bdraco — APPROVED** [review]

File: esphome/components/debug/debug_component.h (hunk 1 above)
[the remark this answers is not in the document]
Comment (nielsnl68) [reply esphome/components/debug/debug_component.h:43]: bots tegenwoordig denken dat ze alles beter weten :P
