### PR TITLE
[epaper_spi] Add Waveshare 7.5" V2 BWR support

### PR DESCRIPTION
**Pull request by twisterss**
# What does this implement/fix?

Adds support for the Waveshare 7.5" V2 BWR (Black/White/Red) e-paper display to the `epaper_spi` component.

- Controller: UC8179 (EDP_7in5b_V2)
- Resolution: 800×480 pixels
- Colors: Black, White, Red
- New driver class `EPaperWaveshareBWR` with dual-plane buffer layout (Black/White plane + Red plane)
- Model name: `waveshare-7.5in-bv2-bwr`

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) — [policy](https://developers.esphome.io/contributing/code/#what-constitutes-a-c-breaking-change)
- [ ] Developer breaking change (an API change that could break external components) — [policy](https://developers.esphome.io/contributing/code/#what-is-considered-public-c-api)
- [ ] Undocumented C++ API change (removal or change of undocumented public methods that lambda users may depend on) — [policy](https://developers.esphome.io/contributing/code/#c-user-expectations)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- N/A

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#6455

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040/RP2350
- [ ] BK72xx
- [ ] RTL87xx
- [ ] LN882x
- [ ] nRF52840

## Example entry for `config.yaml`:

```yaml
display:
  - platform: epaper_spi
    model: waveshare-7.5in-bv2-bwr
    cs_pin: GPIO5
    dc_pin: GPIO17
    reset_pin: GPIO16
    busy_pin: GPIO4
    lambda: |-
      it.filled_rectangle(0, 0, it.get_width(), it.get_height(), Color::WHITE);
      it.print(0, 0, id(my_font), Color::BLACK, "Hello!");
      it.circle(400, 240, 100, Color(255, 0, 0));
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by candrews** [comment]
Is there any chance you'd be interested in doing the same for the `7.50in-hd-b` model? :)

**Comment by twisterss** [comment]
Hi @candrews , I would be happy to help support other models but it’s difficult as I have only this one at home to test.

**Comment by BuckarooBanzay** [comment]
i tested this on my `v3` variant of the epaper display, works flawless :+1: i had some issues with the `waveshare_epaper` platform previously but this is very nice work, thanks :heart:

**Comment by BuckarooBanzay** [comment]
looks like this has been broken by this PR: https://github.com/esphome/esphome/pull/16872
(might also be a false-positive, not sure, just reporting this here for completeness)

i get this when i try to compile:

```
ERROR Unable to import component epaper_spi.display:
Traceback (most recent call last):
  File "/esphome/esphome/loader.py", line 233, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/.esphome/external_components/60c45869/esphome/components/epaper_spi/display.py", line 8, in <module>
    from esphome.components.mipi import (
ImportError: cannot import name 'model_schema_extractor' from 'esphome.components.mipi' (/esphome/esphome/components/mipi/__init__.py). Did you mean: 'schema_extractors'?
Failed config

Platform not found: 'display.epaper_spi'
```

Relevant yml code:

```yml
external_components:
  - source: github://pr#15719
    components: [epaper_spi]
    refresh: 1h

display:
  - platform: epaper_spi
    id: main_display
    model: waveshare-7.5in-bv2-bwr # 800x480
    cs_pin: GPIO01
    dc_pin: GPIO03
    reset_pin: GPIO16
    update_interval: never
    busy_pin:
      number: GPIO17
      inverted: True
    lambda: |-
      it.filled_rectangle(0, 0, it.get_width(), it.get_height(), Color::WHITE);

```

**Comment by twisterss** [comment]
Thanks for the report @BuckarooBanzay! I believe this is due to an incompatible ESPHome version. I recently merged upstream/dev in this PR, which included recent changes that are not yet in the released esphome.

As you said, the `model_schema_extractor` import in `display.py` was introduced by #16872 (merged June 7), which is a separate upstream change to the `epaper_spi` component. When you use `external_components` to load this PR, you get the current state of the branch which includes that upstream change — but your installed ESPHome's `mipi` module predates it.

It should work again once next version is released. Sorry for that. Not sure how I can avoid that and still fix conflicts to have a chance to get this PR merged :sweat_smile: 

Maybe something like that could get your setup working until the next release (it pins the component to before the merge, not tested) but you will have to change it again after next release:
```yaml
external_components:
  - source:
      type: git
      url: https://github.com/twisterss/esphome-dev
      ref: 6133e705
    components: [epaper_spi]
    refresh: 1h
```

**Comment by BuckarooBanzay** [comment]
> Thanks for the report @BuckarooBanzay! I believe this is due to an incompatible ESPHome version. I recently merged upstream/dev in this PR, which included recent changes that are not yet in the released esphome.

huh, yeah, you are right, i was not up to date on my side, sorry for the trouble

> It should work again once next version is released. Sorry for that. Not sure how I can avoid that and still fix conflicts to have a chance to get this PR merged 😅

it worked for me again after the update, thank you for all the work :heart:

**Comment by kpustelnik** [comment]
Hi @twisterss
Ive asked on esphome Discord if this PR could be reviewed as it has been pending for quite a while, yet been told its not worth reviewing due to conflicts. Any way for you to resolve them? Would love to implement this in my projects.

**Comment by twisterss** [comment]
Hi @kpustelnik 
Thank you for your interest. I fixed the conflict.

**Comment by kpustelnik** [comment]
@twisterss thanks for fixing the conflict. Unfortunately Ive stopped getting any responses on Discord after bumping this case... guess we're waiting till the PR has conflict again. The PR works well on my side. Perhaps you have some option to request a review or something in github UI?

**Review by clydebarrow — APPROVED** [review]
