### ISSUE TITLE
Compilation Issue: "error: use of deleted function"

### ISSUE THREAD

**Issue by wrichter** [OttoWinter/esphomeyaml#10351]
### The problem

Building ESP32 firmware fails on ESPHome 2025.8 (after adding subdevices) which worked fine on 2025.5 (without subdevices). I'm getting a C++ compilation error.

### Which version of ESPHome has the issue?

2025.8.0

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Component causing the issue

TextSensor

### YAML Config

```yaml
esphome:
  name: esp32-zaehlerschrank
  friendly_name: esp32-zaehlerschrank

  devices:
    - id: pv_erzeugung_zaehler
      name: PV Erzeugung Zaehler
    - id: hausanschluss_zaehler
      name: Hausanschluss Zaehler
    - id: heizung
      name: Heizung

esp32:
  board: wemos_d1_mini32
  framework: 
    type: esp-idf

logger:
  # disable serial logging
  baud_rate: 0
  logs:
    #sml: INFO
    canbus: INFO
    isotp: INFO
    uds: INFO
    text_sensor: INFO

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password
  platform: esphome


### ENTWEDER WIFI
#wifi:
#  ssid: !secret wifi_ssid
#  password: !secret wifi_password


#captive_portal:

### ODER ETHERNET
ethernet:
  type: W5500
  clk_pin: GPIO18
  miso_pin: GPIO19
  mosi_pin: GPIO23
  cs_pin: GPIO05


# One Wire Configuration
one_wire:
  - platform: gpio
    pin: GPIO26

uart:
- id: uart_0  
  tx_pin: GPIO01 ## verkehrt herum
  rx_pin: GPIO03
  baud_rate: 9600
- id: uart_2
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 9600
#  debug:
#    direction: BOTH
#    dummy_receiver: false
#    after:
#      delimiter: "\n"
#    sequence:
#      - lambda: UARTDebug::log_string(direction, bytes);



sml:
- id: hausanschluss
  uart_id: uart_0
- id: wechselrichter
  uart_id: uart_2


binary_sensor:
  - platform: template
    name: "Heizung Status Zirkulationspumpe 491"
    id: vc491
    device_id: heizung
  - platform: template
    name: "Heizung Status Zentrale Heizungspumpe 381"
    id: vc381
    device_id: heizung
  - platform: template
    name: "Heizung Status Kompressor 2351"
    id: vc2351
    device_id: heizung
  - platform: template
    name: "Heizung Status Heizwasserdurchlauferhitzer 2352"
    id: vc2352
    device_id: heizung
  - platform: template
    name: "Heizung Status Pumpe Heizkörper 2792"
    id: vc2792
    device_id: heizung
  - platform: template
    name: "Heizung Status Pumpe Fußboden 2793"
    id: vc2793
    device_id: heizung


sensor:
- platform: template
  name: "Heizung Temperatur Aussengerät Zulauf 268"
  id: vc268
  unit_of_measurement: °C
  device_class: temperature
  state_class: "measurement"
  accuracy_decimals: 1
  device_id: heizung

- platform: template
  name: "Heizung Temperatur Aussengerät Rücklauf 269"
  id: vc269
  unit_of_measurement: °C
  device_class: temperature
  state_class: "measurement"
  accuracy_decimals: 1
  device_id: heizung
 
- platform: template
  name: "Heizung Temperatur Warmwasser Speicher 271"
  id: vc271
  unit_of_measurement: °C
  device_class: temperature
  state_class: "measurement"
  accuracy_decimals: 1
  device_id: heizung

- platform: template
  name: "Heizung Anlagendruck 318"
  id: vc318
  unit_of_measurement: bar
  device_class: pressure
  state_class: "measurement"
  accuracy_decimals: 1
  device_id: heizung

- platform: template
  name: "Heizung Durchflusssensor Fluss 1043"
  id: vc1043
  unit_of_measurement: L/h
  device_class: volume_flow_rate
  state_class: "measurement"
  accuracy_decimals: 1
  device_id: heizung

- platform: template
  name: "Heizung Geschwindigkeit Kompressor 2346"
  id: vc2346
  unit_of_measurement: "%"
  state_class: "measurement"
  accuracy_decimals: 0
  device_id: heizung

- platform: template
  name: "Heizung Anzahl Starts Verdichter 2369"
  id: vc2369_starts
  state_class: "measurement"
  accuracy_decimals: 0
  device_id: heizung

- platform: template
  name: "Heizung Betriebsstunden Verdichter 2369"
  id: vc2369_hours
  state_class: "measurement"
  device_class: duration
  unit_of_measurement: h
  accuracy_decimals: 0
  device_id: heizung

- platform: template
  name: "Heizung Anzahl Starts Heizwasserdurchlauferhitzer 2370"
  id: vc2370_starts
  state_class: "measurement"
  accuracy_decimals: 0
  device_id: heizung

- platform: template
  name: "Heizung Betriebsstunden Heizwasserdurchlauferhitzer 2370"
  id: vc2370_hours
  state_class: "measurement"
  device_class: duration
  unit_of_measurement: h
  accuracy_decimals: 0
  device_id: heizung

- platform: template
  name: "Heizung Leistung Elektrisch 2488"
  id: vc2488
  state_class: "measurement"
  device_class: power
  unit_of_measurement: W
  accuracy_decimals: 0
  device_id: heizung

- platform: template
  name: "Heizung Leistung Thermisch 2496"
  id: vc2496
  state_class: "measurement"
  device_class: power
  unit_of_measurement: W
  accuracy_decimals: 0
  device_id: heizung

- platform: template
  name: "Heizung Temperatur Puffer 3016"
  id: vc3016
  state_class: "measurement"
  unit_of_measurement: °C
  device_class: temperature
  accuracy_decimals: 0
  device_id: heizung

- platform: dallas_temp
  address: 0x4b01211292b2ac28
  name: "Heizung Temperatur Vorlauf Fußboden"
  accuracy_decimals: 1
  device_id: heizung

- platform: dallas_temp
  address: 0xe10121124baf6d28
  name: "Heizung Temperatur Rücklauf Fußboden"
  accuracy_decimals: 1
  device_id: heizung

- platform: dallas_temp
  address: 0x6c012112a1368b28
  name: "Heizung Temperatur Rücklauf Heizkörper"
  accuracy_decimals: 1
  device_id: heizung

- platform: dallas_temp
  address: 0xfb0121129dc07c28
  name: "Heizung Temperatur Vorlauf Heizkörper"
  accuracy_decimals: 1
  device_id: heizung

- platform: sml
  name: "Hausanschluss Energie Bezug"
  sml_id: hausanschluss
  obis_code: "1-0:1.8.0"
  unit_of_measurement: kWh
  accuracy_decimals: 3
  device_class: energy
  state_class: total_increasing
  filters:
  - multiply: 0.0001
  device_id: hausanschluss_zaehler

- platform: sml
  name: "Hausanschluss Energie Einspeisung"
  sml_id: hausanschluss
  obis_code: "1-0:2.8.0"
  unit_of_measurement: kWh
  accuracy_decimals: 3
  device_class: energy
  state_class: total_increasing
  filters:
  - multiply: 0.0001
  device_id: hausanschluss_zaehler

- platform: sml
  name: "Hausanschluss Leistung"
  sml_id: hausanschluss
  obis_code: "1-0:16.7.0"
  unit_of_measurement: W
  accuracy_decimals: 0
  device_class: power
  state_class: measurement
  device_id: hausanschluss_zaehler


- platform: sml
  name: "PV Leistung"
  sml_id: wechselrichter
  obis_code: "1-0:16.7.0"
  unit_of_measurement: W
  accuracy_decimals: 0
  device_class: power
  state_class: measurement
  filters:
  - multiply: -1.0
  device_id: pv_erzeugung_zaehler

- platform: sml
  name: "PV Produktion"
  sml_id: wechselrichter
  obis_code: "1-0:2.8.0"
  unit_of_measurement: kWh
  accuracy_decimals: 3
  device_class: energy
  state_class: total_increasing
  filters:
  - multiply: 0.0001
  device_id: pv_erzeugung_zaehler


### Viessmann VitoCal CAN Bus Query Implementation, based on
### https://www.csselectronics.com/pages/uds-protocol-tutorial-unified-diagnostic-services
### https://github.com/open3e/open3e/blob/master/src/open3e/Open3Edatapoints.py
### https://github.com/maromme/esphome-vitoair


text_sensor:

- id: vc2735
  name: "Heizung Status 3 Wege Ventil 2735"
  platform: template
  device_id: heizung


# 268 : O3EComplexType(9, "FlowTemperatureSensor", [O3EInt16(2, "Actual", signed=True), O3EInt16(2, "Minimum", signed=True), O3EInt16(2, "Maximum", signed=True), O3EInt16(2, "Average", signed=True), O3EByteVal(1, "Unknown")]),
- id: uds_268 
  internal: true
  platform: template
  on_value:
      then:
        - lambda: 'id(vc268).publish_state(float((((uint16_t) x[1]) << 8) | x[0]) * 0.1);'

# 269 : O3EComplexType(9, "ReturnTemperatureSensor", [O3EInt16(2, "Actual", signed=True), O3EInt16(2, "Minimum", signed=True), O3EInt16(2, "Maximum", signed=True), O3EInt16(2, "Average", signed=True), O3EByteVal(1, "Unknown")]),
- id: uds_269 # ReturnTemperatureSensor
  internal: true
  platform: template
  on_value:
      then:
        - lambda: 'id(vc269).publish_state(float((((uint16_t) x[1]) << 8) | x[0]) * 0.1);'

# 271 : O3EComplexType(9, "DomesticHotWaterSensor", [O3EInt16(2, "Actual", signed=True), O3EInt16(2, "Minimum", signed=True), O3EInt16(2, "Maximum", signed=True), O3EInt16(2, "Average", signed=True), O3EByteVal(1, "Unknown")]),
- id: uds_271
  internal: true
  platform: template
  on_value:
      then:
        - lambda: 'id(vc271).publish_state(float((((uint16_t) x[1]) << 8) | x[0]) * 0.1);'

# 274 : O3EComplexType(9, "OutsideTemperatureSensor", [O3EInt16(2, "Actual", signed=True), O3EInt16(2, "Minimum", signed=True), O3EInt16(2, "Maximum", signed=True), O3EInt16(2, "Average", signed=True), O3EByteVal(1, "Unknown")]),
# 284 : O3EComplexType(9, "MixerOneCircuitFlowTemperatureSensor", [O3EInt16(2, "Actual", signed=True), O3EInt16(2, "Minimum", signed=True), O3EInt16(2, "Maximum", signed=True), O3EInt16(2, "Average", signed=True), O3EByteVal(1, "Unknown")]),
# 285 : O3EComplexType(9, "MixerOneCircuitReturnTemperatureSensor", [O3EInt16(2, "Actual", signed=True), O3EInt16(2, "Minimum", signed=True), O3EInt16(2, "Maximum", signed=True), O3EInt16(2, "Average", signed=True), O3EByteVal(1, "Unknown")]),
# 286 : O3EComplexType(9, "MixerTwoCircuitFlowTemperatureSensor", [O3EInt16(2, "Actual", signed=True), O3EInt16(2, "Minimum", signed=True), O3EInt16(2, "Maximum", signed=True), O3EInt16(2, "Average", signed=True), O3EByteVal(1, "Unknown")]),
# 287 : O3EComplexType(9, "MixerTwoCircuitReturnTemperatureSensor", [O3EInt16(2, "Actual", signed=True), O3EInt16(2, "Minimum", signed=True), O3EInt16(2, "Maximum", signed=True), O3EInt16(2, "Average", signed=True), O3EByteVal(1, "Unknown")]),

# 318 : O3EComplexType(9, "WaterPressureSensor", [O3EInt16(2, "Actual", signed=True), O3EInt16(2, "Minimum", signed=True), O3EInt16(2, "Maximum", signed=True), O3EInt16(2, "Average", signed=True), O3EByteVal(1, "Unknown")]),
- id: uds_318 
  internal: true
  platform: template
  on_value:
      then:
        - lambda: 'id(vc318).publish_state(float((((uint16_t) x[1]) << 8) | x[0]) * 0.1);'

# 320 : O3EComplexType(9, "PrimaryHeatExchangerLiquidTemperatureSensor", [O3EInt16(2, "Actual", signed=True), O3EInt16(2, "Minimum", signed=True), O3EInt16(2, "Maximum", signed=True), O3EInt16(2, "Average", signed=True), O3EByteVal(1, "Unknown")]),
# 321 : O3EComplexType(9, "CompressorInletTemperatureSensor", [O3EInt16(2, "Actual", signed=True), O3EInt16(2, "Minimum", signed=True), O3EInt16(2, "Maximum", signed=True), O3EInt16(2, "Average", signed=True), O3EByteVal(1, "Unknown")]),
# 322 : O3EComplexType(9, "CompressorInletPressureSensor", [O3EInt16(2, "Actual", scale = 100), O3EInt16(2, "Minimum", scale = 100), O3EInt16(2, "Maximum", scale = 100), O3EInt16(2, "Average", scale = 100), O3EByteVal(1, "Unknown")]),
# 324 : O3EComplexType(9, "CompressorOutletTemperatureSensor", [O3EInt16(2, "Actual", signed=True), O3EInt16(2, "Minimum", signed=True), O3EInt16(2, "Maximum", signed=True), O3EInt16(2, "Average", signed=True), O3EByteVal(1, "Unknown")]),
# 325 : O3EComplexType(9, "CompressorOutletPressureSensor", [O3EInt16(2, "Actual", scale = 100), O3EInt16(2, "Minimum", scale = 100), O3EInt16(2, "Maximum", scale = 100), O3EInt16(2, "Average", scale = 100), O3EByteVal(1, "Unknown")]),
# 327 : O3EComplexType(9, "OutdoorAirTemperatureSensor",[O3EInt16(2, "Actual", signed=True), O3EInt16(2, "Minimum", signed=True), O3EInt16(2, "Maximum", signed=True), O3EInt16(2, "Average", signed=True), O3EByteVal(1, "Error")]),
# 355 : O3EComplexType(9, "SecondaryHeatExchangerLiquidTemperatureSensor",[O3EInt16(2, "Actual", signed=True), O3EInt16(2, "Minimum", signed=True), O3EInt16(2, "Maximum", signed=True), O3EInt16(2, "Average", signed=True), O3EByteVal(1, "Error")]),

# 381 : O3EComplexType(4, "CentralHeatingPump", [O3EInt8(1, "Minimum"), O3EInt8(1, "Actual"), O3EInt8(1, "Maximum"), RawCodec(1, "Unknown")]),
- id: uds_381
  internal: true
  platform: template
  on_value:
    then:
      - lambda: 'id(vc381).publish_state(x[1] > 0);'

# 389 : O3EInt8(1, "ElectronicExpansionValveOneCurrentPositionPercent"),
# 391 : O3EInt8(1, "ElectronicExpansionValveTwoCurrentPositionPercent"),
# 395 : O3EInt16(2, "CentralHeatingTemperatureSetpoint"),
# 396 : O3EInt16(2, "DomesticHotWaterTemperatureSetpoint", signed=True),

# 491 : O3EComplexType(2, "DomesticHotWaterCirculationPump",[O3EByteVal(1,"State"),O3EByteVal(1,"Unknown")]),                
- id: uds_491 
  internal: true
  platform: template
  on_value:
    then:
      - lambda: 'id(vc491).publish_state(x[0] > 0);'


# 1043 : O3EComplexType(5, "AllengraSensor", [O3EInt16(2, "Actual"), O3EInt16(2, "Temperature"), RawCodec(1, "Unknown")]),
- id: uds_1043
  internal: true
  platform: template
  on_value:
    then:
      - lambda: 'id(vc1043).publish_state( float((((uint16_t) x[1]) << 8) | x[0]) * 0.1 );'

# 1769 : O3EComplexType(9, "PrimaryInletTemperatureSensor", [O3EInt16(2, "Actual", signed=True), O3EInt16(2, "Minimum", signed=True), O3EInt16(2, "Maximum", signed=True), O3EInt16(2, "Average", signed=True), O3EByteVal(1, "Unknown")]),
# 1771 : O3EComplexType(9, "EngineRoomTemperatureSensor", [O3EInt16(2, "Actual", signed=True), O3EInt16(2, "Minimum", signed=True), O3EInt16(2, "Maximum", signed=True), O3EInt16(2, "Average", signed=True), O3EByteVal(1, "Unknown")]),
# 1772 : O3EComplexType(9, "CompressorOilTemperatureSensor", [O3EInt16(2, "Actual", signed=True), O3EInt16(2, "Minimum", signed=True), O3EInt16(2, "Maximum", signed=True), O3EInt16(2, "Average", signed=True), O3EByteVal(1, "Unknown")]),
# 1773 : O3EByteVal(1, "RefrigerantCircuitFourWayValve"),
# 1774 : O3EByteVal(1, "CompressorCrankCaseHeater"),
# 1775 : O3EByteVal(1, "PrimaryCircuitFanOne"),
# 1776 : O3EByteVal(1, "PrimaryCircuitFanTwo"),
# 2333 : O3EComplexType(9, "EconomizerLiquidTemperatureSensor", [O3EInt16(2, "Actual", signed=True), O3EInt16(2, "Minimum", signed=True), O3EInt16(2, "Maximum", signed=True), O3EInt16(2, "Average", signed=True), O3EByteVal(1, "Unknown")]),
# 2334 : O3EComplexType(9, "EvaporatorVaporTemperatureSensor", [O3EInt16(2, "Actual", signed=True), O3EInt16(2, "Minimum", signed=True), O3EInt16(2, "Maximum", signed=True), O3EInt16(2, "Average", signed=True), O3EByteVal(1, "Unknown")]),

# 2345 : O3EInt8(1, "CompressorSetpointPercent"),
# 2346 : O3EInt8(1, "CompressorSpeedPercent"),
- id: uds_2346 
  internal: true
  platform: template
  on_value:
    then:
      - lambda: 'id(vc2346).publish_state(float(x[0]));'

# 2351 : O3EComplexType(2, "HeatPumpCompressor", [O3EByteVal(1, "PowerState"), O3EByteVal(1, "ErrorState")]),
- id: uds_2351 
  internal: true
  platform: template
  on_value:
    then:
      - lambda: 'id(vc2351).publish_state(x[0] > 0);'
# 2352 : O3EComplexType(2, "AdditionalElectricHeater", [O3EByteVal(1, "PowerState"), O3EByteVal(1, "ErrorState")]),
- id: uds_2352 
  internal: true
  platform: template
  on_value:
    then:
      - lambda: 'id(vc2352).publish_state(x[0] > 0);'

# 2369 : O3EComplexType(14, "HeatPumpCompressorStatistical",[RawCodec(6, "Unknown1"), O3EInt16(2, "starts", scale=1), RawCodec(2, "Unknown2"), O3EInt16(2, "hours", scale=1), RawCodec(2, "Unknown3")]),
- id: uds_2369
  internal: true
  platform: template
  on_value:
    then:
      - lambda: |-
          id(vc2369_starts).publish_state( float( (((uint16_t) x[7]) << 8) | x[6] ) ); 
          id(vc2369_hours).publish_state( float( (((uint16_t) x[11]) << 8) | x[10] ) );

# 2370 : O3EComplexType(11, "AdditionalElectricHeaterStatistical",[RawCodec(3, "Unknown1"), O3EInt16(2, "starts", scale=1), RawCodec(2, "Unknown2"), O3EInt16(2, "hours", scale=1), RawCodec(2, "Unknown3")]),
- id: uds_2370 
  internal: true
  platform: template
  on_value:
    then:
      - lambda: |-
          id(vc2370_starts).publish_state( float( (((uint16_t) x[7]) << 8) | x[6] ) ); 
          id(vc2370_hours).publish_state( float( (((uint16_t) x[11]) << 8) | x[10] ) );

# 2486 : O3EInt32(4, "CurrentElectricalPowerConsumptionRefrigerantCircuit", scale = 1),
# 2487 : O3EInt32(4, "CurrentElectricalPowerConsumptionElectricHeater", scale = 1),
# 2488 : O3EInt32(4, "CurrentElectricalPowerConsumptionSystem", scale = 1),
- id: uds_2488 
  internal: true
  platform: template
  on_value:
    then:
      - lambda: 'id(vc2488).publish_state( float( (((uint32_t) x[3]) << 24) | (((uint32_t) x[2]) << 16 ) | (((uint32_t) x[1]) << 8 ) | ((uint32_t) x[0]) ) );'


# 2494 : O3EInt32(4, "CurrentThermalCapacityRefrigerantCircuit", scale = 1, signed = True),# Unit: Watts
# 2495 : O3EInt32(4, "CurrentThermalCapacityElectricHeater", scale = 1),# Unit: Watts
# 2496 : O3EInt32(4, "CurrentThermalCapacitySystem", scale = 1),# Unit: Watts
- id: uds_2496 
  internal: true
  platform: template
  on_value:
    then:
      - lambda: 'id(vc2496).publish_state( float( (((uint32_t) x[3]) << 24) | (((uint32_t) x[2]) << 16 ) | (((uint32_t) x[1]) << 8 ) | ((uint32_t) x[0]) ) );'

# 2735 : O3EByteVal(1, "FourThreeWayValveValveCurrentPosition"),# 0 = Central Heating / Cooling, 1 = Internal Buffer, 2 = Domestic Hot Water, 3 = Central Heating / Cooling + Internal Buffer, 4 = Domestic Hot Water + Internal Buffer
- id: uds_2735 
  internal: true
  platform: template
  on_value:
    then:
      - lambda: |-
          switch (x[0]) {
              case 0: id(vc2735).publish_state("Heizen / Kühlen"); break;
              case 1: id(vc2735).publish_state("Puffer"); break;
              case 2: id(vc2735).publish_state("Warmwasser"); break;
              case 3: id(vc2735).publish_state("Heizen / Kühlen + Puffer"); break;
              case 4: id(vc2735).publish_state("Warmwasser + Puffer"); break;
              default: break;
          }

# 2792 : O3EComplexType(5, "MixerOneCircuitPumpStatus", [O3EInt8(1, "Actual"), RawCodec(4, "Unknown")]),
# 2793 : O3EComplexType(5, "MixerTwoCircuitPumpStatus", [O3EInt8(1, "Actual"), RawCodec(4, "Unknown")]),
- id: uds_2792
  internal: true
  platform: template
  on_value:
    then:
      - lambda: 'id(vc2792).publish_state(x[0] > 0);'

# 491 : O3EComplexType(2, "DomesticHotWaterCirculationPump",[O3EByteVal(1,"State"),O3EByteVal(1,"Unknown")]),                
- id: uds_2793
  internal: true
  platform: template
  on_value:
    then:
      - lambda: 'id(vc2793).publish_state(x[0] > 0);'

# 2794 : O3EComplexType(5, "MixerThreeCircuitPumpStatus", [O3EInt8(1, "Actual"), RawCodec(4, "Unknown")]),
# 2795 : O3EComplexType(5, "MixerFourCircuitPumpStatus", [O3EInt8(1, "Actual"), RawCodec(4, "Unknown")]),

# 3016 : O3EComplexType(9, "HeatingBufferTemperatureSensor", [O3EInt16(2, "Actual", signed=True), O3EInt16(2, "Minimum", signed=True), O3EInt16(2, "Maximum", signed=True), O3EInt16(2, "Average", signed=True), O3EByteVal(1, "Unknown")]),
- id: uds_3016
  internal: true
  platform: template
  on_value:
      then:
        - lambda: 'id(vc3016).publish_state(float((((uint16_t) x[1]) << 8) | x[0]) * 0.1);'
# 3017 : O3EComplexType(9, "CoolingBufferTemperatureSensor", [O3EInt16(2, "Actual", signed=True), O3EInt16(2, "Minimum", signed=True), O3EInt16(2, "Maximum", signed=True), O3EInt16(2, "Average", signed=True), O3EByteVal(1, "Unknown")]),
# 3018 : O3EComplexType(9, "HeatingCoolingBufferTemperatureSensor", [O3EInt16(2, "Actual", signed=True), O3EInt16(2, "Minimum", signed=True), O3EInt16(2, "Maximum", signed=True), O3EInt16(2, "Average", signed=True), O3EByteVal(1, "Unknown")]),


globals:
- id: text_sensors_representing_dids
  type: std::vector<esphome::text_sensor::TextSensor>
  restore_value: no
  # cat|yq '.text_sensor[].id| select(. == "uds_*")|= "id(" + . + "),"' - |tr '\n' ' '
  initial_value: '{ id(uds_268), id(uds_269), id(uds_271), id(uds_318), id(uds_381), id(uds_491), id(uds_1043), id(uds_2346), id(uds_2351), id(uds_2352), id(uds_2369), id(uds_2370), id(uds_2488), id(uds_2496), id(uds_2735), id(uds_2792), id(uds_2793), id(uds_3016) }'
- id: can_target_address
  type: int
  restore_value: no
  initial_value: '0x680' 
- id: isotp_current_dataframe
  type: std::vector<uint8_t>
  restore_value: no
  initial_value: '{0}'
- id: isotp_current_dataframe_length
  type: uint16_t
  restore_value: no
  initial_value: '0'
- id: current_did_index
  type: int
  restore_value: no
  initial_value: '0' 

## the stuff below should not need reconfiguration

interval:
- interval: 2s # query one DID every X seconds
  then:
    - lambda: |-
        int did = std::stoi(id(text_sensors_representing_dids)[id(current_did_index)].get_object_id().substr(4,12));
        ESP_LOGD("uds", "query UDS DID %d",  did);
        id(uds_0x22_read_did_request)->execute(did);
        if (++id(current_did_index) >= id(text_sensors_representing_dids).size()) { 
            id(current_did_index) = 0;
        }

canbus:
  - platform: esp32_can
    tx_pin: GPIO21
    rx_pin: GPIO22
    can_id: 0x680
    id: cb
    bit_rate: 250KBPS
    on_frame:
      - can_id: 0x690
        then:
          - lambda: |-
              ESP_LOGD("isotp", "received: 0x%02X %02X %02X %02X %02X %02X %02X %02X", x[0], x[1], x[2], x[3], x[4], x[5], x[6], x[7]);

              //ISO-TP protocol handling
              switch (x[0] >> 4) {

                  case 0: { // single frame
                      id(isotp_current_dataframe_length) = x[0] & 0x0f;
                      id(isotp_current_dataframe).reserve(id(isotp_current_dataframe_length));
                      id(isotp_current_dataframe).clear();
                      for (int i=1; i<=id(isotp_current_dataframe_length); i++) { // first byte is ISO-TS PCI
                        id(isotp_current_dataframe).push_back(x[i]);
                      }
                      id(isotp_frame_received)->execute();

                      break;
                  }
                  case 1: { // first frame (of multiple)
                      id(isotp_current_dataframe_length) = (( (uint16_t) (x[0] & 0x0f) ) << 8) + ((uint16_t)x[1]);
                      ESP_LOGD("isotp", "dataframe length %d", id(isotp_current_dataframe_length));
                      id(isotp_current_dataframe).reserve(id(isotp_current_dataframe_length));
                      id(isotp_current_dataframe).clear();
                      for (int i=2; i<8; i++) { // first two bytes are ISO-TS PCI, len always exceeds the 8 byte packet, this is why we push all bytes in packet
                        id(isotp_current_dataframe).push_back(x[i]);
                      }
                      
                      // 0x30: ISO-TP Protocol Control Information (PCI) high nibble: PCI Flow Control, low nibble: "Continue to Send" (0x0)
                      // 0x00: send remaining frames without flow control or delay
                      // 0x00: minimum consecutive frame separation time (ST) 0
                      // 0xAA 0xAA 0xAA 0xAA 0xAA: Padding
                      std::vector< uint8_t > data0{ 0x30, 0x00, 0x00, 0xAA, 0xAA, 0xAA, 0xAA ,0xAA };
                      ESP_LOGD("isotp", "sent: 0x%02X %02X %02X %02X %02X %02X %02X %02X", data0[0], data0[1], data0[2], data0[3], data0[4], data0[5], data0[6], data0[7]);
                      id(cb)->send_data(id(can_target_address), 0, data0);

                      break;
                  }
                  case 2: { // consecutive frame (of multiple)
                      uint16_t pos = (((uint16_t) x[0] & 0x0f) - 1) * 7 + 6;
                      uint16_t end = pos;

                      ESP_LOGD("isotp", "received data at position %d for a dataframe length of %d", pos, id(isotp_current_dataframe_length));

                      for (int i=1; i<8 && end<id(isotp_current_dataframe_length) ; i++, end++) { // first byte is ISO-TS PCI
                        id(isotp_current_dataframe).push_back(x[i]);
                      }

                      // if this datagram completes the indicated frame size
                      ESP_LOGD("isotp", "received %d bytes of a %d byte frame", end, id(isotp_current_dataframe_length));
                      if (end >=  id(isotp_current_dataframe_length)) {
                        id(isotp_frame_received)->execute();
                      }
                      break;
                  }
                  default: // ignore flow control frame and others
                      break;
              }

script:
- id: uds_0x22_read_did_request
  parameters:
    did: int
  then:
    lambda: |-
        // 0x03: ISO-TP Protocol Control Information (PCI) high nibble: PCI single frame, low nibble: 3 bytes length
        // 0x22: Service Identifier (SID): Unified Diagnistics Service Data Read Request
        // 0x?? 0x??: Data Identifier (DID): The value in question
        // 0xAA 0xAA 0xAA 0xAA: Padding
        std::vector< uint8_t > x{ 0x03, 0x22, (uint8_t) (did >> 8), (uint8_t) (did & 0x00ff), 0xAA, 0xAA, 0xAA, 0xAA };
        ESP_LOGD("isotp", "sent: 0x%02X %02X %02X %02X %02X %02X %02X %02X", x[0], x[1], x[2], x[3], x[4], x[5], x[6], x[7]);
        id(cb)->send_data(id(can_target_address), 0, x);
- id: uds_0x2E_write_did_request_two_bytes
  parameters:
    did: int
    data: int
  then:
    lambda: |-
        // 0x03: ISO-TP Protocol Control Information (PCI) high nibble: PCI single frame, low nibble: 3 bytes length
        // 0x2E: Service Identifier (SID): Unified Diagnistics Service Data Write Request
        // 0x?? 0x??: Data Identifier (DID): The value in question
        // 0x?? 0x??: Payload
        // 0xAA 0xAA: Padding
        std::vector< uint8_t > x{ 0x03, 0x2E, (uint8_t) (did >> 8), (uint8_t) (did & 0x00ff), (uint8_t) (data >> 8), (uint8_t) (data & 0x00ff), 0xAA, 0xAA };
        ESP_LOGD("isotp", "sent: 0x%02X %02X %02X %02X %02X %02X %02X %02X", x[0], x[1], x[2], x[3], x[4], x[5], x[6], x[7]);
        id(cb)->send_data(id(can_target_address), 0, x);
- id: isotp_frame_received
  then:
    - lambda: |-
        switch (id(isotp_current_dataframe)[0]) {
            case 0x62: { // SID UDS data read response (0x22 + 0x40)
                id(uds_0x62_read_did_response)->execute();
                break;
            }
            case 0x6E: { // SID UDS data write positive response (0x2E + 0x40)
                break;
            }
            case 0x7F: { // SID UDS data write negative response (0x2E + 0x51)
                break;
            }
            default: break; //ignore
        }
- id: uds_0x62_read_did_response
  then:
    - lambda: |-
        uint16_t did = (((uint16_t)id(isotp_current_dataframe)[1]) << 8) | ((uint16_t)id(isotp_current_dataframe)[2]);
        uint16_t len = id(isotp_current_dataframe).size();
        std::string text(id(isotp_current_dataframe).begin() + 3, id(isotp_current_dataframe).end());

        ESP_LOGD("uds", "received DID %04X length %d", did, len);

        // identify internal text sensor belonging to DID
        for (esphome::text_sensor::TextSensor &ts : id( text_sensors_representing_dids )) {
            int sensor_did = std::stoi(ts.get_object_id().substr(4,12));

            if (did == sensor_did) {
                ESP_LOGD("uds", "found sensor %s", ts.get_object_id().c_str());
                ts.publish_state(text);
                break;
            }
        }
```

### Anything in the logs that might be useful for us?

```txt
/config/esphome/esp32-zaehlerschrank.yaml: In function 'void setup()':
/config/esphome/esp32-zaehlerschrank.yaml:712:361: error: use of deleted function 'esphome::text_sensor::TextSensor::TextSensor(const esphome::text_sensor::TextSensor&)'
In file included from src/esphome/core/application.h:38,
                 from src/esphome/components/api/api_frame_helper.h:12,
                 from src/esphome/components/api/api_connection.h:5,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/components/text_sensor/text_sensor.h:32:7: note: 'esphome::text_sensor::TextSensor::TextSensor(const esphome::text_sensor::TextSensor&)' is implicitly deleted because the default definition would be ill-formed:
   32 | class TextSensor : public EntityBase, public EntityBase_DeviceClass {
      |       ^~~~~~~~~~
src/esphome/components/text_sensor/text_sensor.h: At global scope:
src/esphome/components/text_sensor/text_sensor.h:32:7: error: use of deleted function 'std::unique_ptr<_Tp, _Dp>::unique_ptr(const std::unique_ptr<_Tp, _Dp>&) [with _Tp = esphome::CallbackManager<void(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)>; _Dp = std::default_delete<esphome::CallbackManager<void(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)> >]'
In file included from /data/cache/platformio/packages/toolchain-xtensa-esp-elf/xtensa-esp-elf/include/c++/14.2.0/memory:78,
                 from src/esphome/components/socket/socket.h:2,
                 from src/esphome/components/api/api_frame_helper.h:11:
/data/cache/platformio/packages/toolchain-xtensa-esp-elf/xtensa-esp-elf/include/c++/14.2.0/bits/unique_ptr.h:516:7: note: declared here
  516 |       unique_ptr(const unique_ptr&) = delete;
      |       ^~~~~~~~~~
src/esphome/components/text_sensor/text_sensor.h:32:7: note: use '-fdiagnostics-all-candidates' to display considered candidates
   32 | class TextSensor : public EntityBase, public EntityBase_DeviceClass {
      |       ^~~~~~~~~~
/config/esphome/esp32-zaehlerschrank.yaml: In function 'void setup()':
/config/esphome/esp32-zaehlerschrank.yaml:712:361: note: use '-fdiagnostics-all-candidates' to display considered candidates
In file included from /data/cache/platformio/packages/toolchain-xtensa-esp-elf/xtensa-esp-elf/include/c++/14.2.0/vector:66,
                 from src/esphome/components/api/api_frame_helper.h:7:
/data/cache/platformio/packages/toolchain-xtensa-esp-elf/xtensa-esp-elf/include/c++/14.2.0/bits/stl_vector.h:678:43: note:   initializing argument 1 of 'constexpr std::vector<_Tp, _Alloc>::vector(std::initializer_list<_Tp>, const allocator_type&) [with _Tp = esphome::text_sensor::TextSensor; _Alloc = std::allocator<esphome::text_sensor::TextSensor>; allocator_type = std::allocator<esphome::text_sensor::TextSensor>]'
  678 |       vector(initializer_list<value_type> __l,
      |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
```

**Comment by ssieb** [comment]
I don't know how that ever worked.  Your vector of text sensors needs to be pointers.

**Comment by wrichter** [comment]
Thank you @ssieb, after changing the vector to one of pointers and adapting my code to use `->` instead of `.` in the right places it works! Seems I was creating copies instead of using references, and a change in ESPHome made the constructor which creates copies invisible.
