### PR TITLE
Fix SPI support for second bus on 2023.9.1

### LINKED ISSUE #4927: SPI broken in 2023.9.1 when 2 HW devices are used
### The problem

After upgrading from 2023.8.3 to 2023.9.1 it is not possible to compile 2 HW SPI buses.

```
src/main.cpp: In function 'void setup()':
src/main.cpp:156:28: error: expected primary-expression before 'return'
   spi_bus_2->set_interface(return new SPIClass(HSPI));
```

### Which version of ESPHome has the issue?

2023.9.1

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

NA

### What platform are you using?

ESP32

### Board

esp32dev

### Component causing the issue

SPI

### Example YAML snippet

```yaml
esphome:
  name: test
  platform: ESP32
  board: esp32dev

spi:
  - id: spi_bus_1
    clk_pin: GPIO32
    mosi_pin: GPIO33
    miso_pin: GPIO39
  - id: spi_bus_2
    clk_pin: GPIO15
    mosi_pin: GPIO13
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2023.9.1
INFO Reading configuration /config/test.yaml...
WARNING GPIO15 is a Strapping PIN and should be avoided.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
INFO Generating C++ source...
INFO Compiling app...
Processing test (board: esp32dev; framework: arduino; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Dependency Graph
|-- SPI @ 2.0.0
Compiling .pioenvs/test/src/main.cpp.o
Compiling .pioenvs/test/FrameworkArduino/HardwareSerial.cpp.o
Compiling .pioenvs/test/FrameworkArduino/IPAddress.cpp.o
Compiling .pioenvs/test/FrameworkArduino/IPv6Address.cpp.o
Compiling .pioenvs/test/FrameworkArduino/MD5Builder.cpp.o
Compiling .pioenvs/test/FrameworkArduino/Print.cpp.o
Compiling .pioenvs/test/FrameworkArduino/Stream.cpp.o
Compiling .pioenvs/test/FrameworkArduino/StreamString.cpp.o
src/main.cpp: In function 'void setup()':
src/main.cpp:156:28: error: expected primary-expression before 'return'
   spi_bus_2->set_interface(return new SPIClass(HSPI));
                            ^~~~~~
*** [.pioenvs/test/src/main.cpp.o] Error 1
========================== [FAILED] Took 2.71 seconds ==========================
```

### Additional information

Related to https://github.com/esphome/issues/issues/4922 but I found that is not depending on devices, just the SPI bus.

So it looks like the rewrite from @clydebarrow at https://github.com/esphome/esphome/pull/5311 unfortunately broke this as it worked fine in 2023.8.3.

I also tried to switch to use the IDF framework but my device (Shelly Pro 4PM) failed. So until this is addressed devices with 2 SPI buses need to stay in 2023.8.3

### PR DESCRIPTION
**Pull request by angelnu**
# What does this implement/fix?

When compiling devices with 2 or more SPI buses on 2023.9.1 with the default Arduino framework, the compilation breaks. This fixes the build error.

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes [<link to issue>](https://github.com/esphome/issues/issues/4927)

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** NA

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
esphome:
  name: test
  platform: ESP32
  board: esp32dev

spi:
  - id: spi_bus_1
    clk_pin: GPIO32
    mosi_pin: GPIO33
    miso_pin: GPIO39
  - id: spi_bus_2
    clk_pin: GPIO15
    mosi_pin: GPIO13
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by kbx81 — APPROVED** [review]
Weird, I swear I tested this case before...either way, thanks for the fix!

**Review by clydebarrow — APPROVED** [review]
Good catch! Thanks.

**Comment by angelnu** [comment]
Should I also add an extra test for this?

I added 2 buses to the PR at https://github.com/esphome/esphome/pull/5439/files#diff-27a7341eec029b586cf4fc61979caddb879768877bd83b5642277c471514eacf I could add a similar test for the arduino platform.

**Comment by kbx81** [comment]
> Should I also add an extra test for this?

Can't hurt 😄

**Comment by clydebarrow** [comment]
Yes there should be a test. Since it should fail at compile time.
