### PR TITLE
[async_tcp] Fix build conflicts and use IDF component for ESP32

### PR DESCRIPTION
**Pull request by dwmw2**
## What does this implement/fix?

Fix build issues introduced by #12337 where `async_tcp_socket.h` conflicts with the AsyncTCP library on platforms like LibreTiny (BK72xx).

### Changes:
- Guard `async_tcp_socket.h` content with platform checks to make it a no-op on platforms using AsyncTCP libraries (ESP32, ESP8266, RP2040, LibreTiny)
- Use `add_idf_component` for ESP32 (works for both Arduino and ESP-IDF frameworks)
- Add `esp32async/asynctcp` to `idf_component.yml` for clang-tidy support
- Remove AsyncTCP from `platformio.ini` since it's now handled by `add_idf_component`

### Root cause:
`esphome.h` includes all component headers, so both `async_tcp.h` (which includes `<AsyncTCP.h>` defining `class AsyncClient` globally) and `async_tcp_socket.h` (which has its own `AsyncClient` class) were being included, causing a conflict.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Developer breaking change (an API change that could break external components)
- [x] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes build failure on BK72xx introduced by #12337

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [x] BK72xx
- [ ] RTL87xx
- [ ] nRF52840

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

### CODE REVIEW

**Comment by dwmw2** [comment]
Error: /home/runner/work/esphome/esphome/esphome/components/async_tcp/async_tcp_socket.h:3:10: error: circular header file dependency detected while including 'async_tcp.h', please check the include path [misc-header-include-cycle,-warnings-as-errors]

Meh, I did that on purpose...

File: esphome/components/async_tcp/async_tcp.h
Comment (swoboda1337) [inline esphome/components/async_tcp/async_tcp.h:1]:
```
#if (defined(USE_ESP32) || defined(USE_LIBRETINY)) && !defined(CLANG_TIDY)
// Use AsyncTCP library for ESP32 (Arduino or ESP-IDF) and LibreTiny
// But not for clang-tidy as the header file isn't present in that case
```
Why would the header not be present??

Comment (swoboda1337) [reply esphome/components/async_tcp/async_tcp.h:1]: For clang tidy you are supposed to add components to https://github.com/esphome/esphome/blob/dev/esphome/idf_component.yml

Can you fix that and remove this comment and ifdef?

**Review by swoboda1337 — CHANGES_REQUESTED** [review]
See comments

File: esphome/components/async_tcp/async_tcp.h [hunk 1]
```diff
@@ -13,5 +13,5 @@
 #include <AsyncTCP_RP2040W.h>
 #else
 // Use socket-based implementation for other platforms and clang-tidy
-#include "async_tcp_socket.h"
+#define ESPHOME_ASYNC_TCP_SOCKET_IMPL
```
Comment (swoboda1337) [inline esphome/components/async_tcp/async_tcp.h]: Do we need this if clang tidy is fixed?

File: esphome/components/async_tcp/async_tcp.h
Comment (dwmw2) [reply esphome/components/async_tcp/async_tcp.h:1]: Will attempt that. Might be tomorrow now.

File: esphome/components/async_tcp/async_tcp.h (hunk 1 above)
Comment (dwmw2) [reply esphome/components/async_tcp/async_tcp.h]: Yes, there are still platforms (e.g. host) where we need the socket-based implementation. But we just might not need to fall back to it for clang-tidy.

File: esphome/components/async_tcp/async_tcp_socket.h [hunk 2]
```diff
@@ -2,7 +2,8 @@
 
 #include "esphome/core/defines.h"
 
-#if defined(USE_SOCKET_IMPL_LWIP_SOCKETS) || defined(USE_SOCKET_IMPL_BSD_SOCKETS)
+#if !defined(USE_ESP32) && !defined(USE_ESP8266) && !defined(USE_RP2040) && !defined(USE_LIBRETINY) && \
+    (defined(USE_SOCKET_IMPL_LWIP_SOCKETS) || defined(USE_SOCKET_IMPL_BSD_SOCKETS))
```
Comment (swoboda1337) [inline esphome/components/async_tcp/async_tcp_socket.h:6]: Python does this, better to just match it, dont need to create a new define:
```
def FILTER_SOURCE_FILES() -> list[str]:
    # Exclude socket implementation for platforms that use AsyncTCP libraries
    if CORE.is_esp32 or CORE.is_esp8266 or CORE.is_rp2040 or CORE.is_libretiny:
        return ["async_tcp_socket.cpp"]
    return []
```

**Review by swoboda1337 — DISMISSED** [review]

**Comment by swoboda1337** [comment]
The other issue is we shouldnt be using `CORE.using_esp_idf:` since Arduino also uses idf that is deprecated:
```
    @property
    def using_esp_idf(self):
        _LOGGER.warning(
            "CORE.using_esp_idf was deprecated in 2026.1, will change behavior in 2026.6. "
            "ESP32 Arduino builds on top of ESP-IDF, so ESP-IDF features are available in both frameworks. "
            "Use CORE.is_esp32 and/or CORE.using_arduino instead."
        )
        return self.target_framework == "esp-idf"
```

**Comment by bdraco** [comment]
compiles fine on esp32-ard now

**Review by bdraco — DISMISSED** [review]

**Review by swoboda1337 — DISMISSED** [review]

**Review by swoboda1337 — APPROVED** [review]

**Review by bdraco — APPROVED** [review]
