### PR TITLE
RFC: status_led: allow to share single light

### PR DESCRIPTION
**Pull request by ianchi**
# What does this implement/fix? 

For devices with only one led, allow to share it between `status_led` and as ordinary (binary) light.
This is the same behavior from most vendors' firmware.

The logic is that when there is no error condition, instead of *blindly turning off* the output every loop, we set the output to the current light state as set in config `light_id`. And this only when there is a change of global error condition, and not on every loop.

### To think over
`light_id` might be confused with the id of the light to use as output, it could be called `shared_light_id`.
Using this option, perhaps should replace the use of direct pin assignment, to avoid inconsistent pin definition between status_led and light. But `status_led` needs access to the output without changing the internal state of the light, to use it to restore on/off led status once global state is normal. But currently `LightSate` class doesn't allow this access. (should we add it?)

Save for this *conceptual* issue, this solution works perfectly well in my use cases.
Perhaps another (more intuitive?) approach could be for `status_led` itself to derive from `LightState` and output the internal error/warning status without changing the external on/off state for normal light usage, (as a kind of modified `binary light`). But in this case we move the *inconsistency* to another place: the `is_on`/`is_off` wouldn't reflect the real light state if in a global error status.

So there is always a tradeoff. 

Please share your view, and I can adapt the PR. 

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** https://github.com/esphome/feature-requests/issues/117

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** 
esphome/esphome-docs#1354

## Test Environment

- [ ] ESP32
- [x] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

light:
  - platform: status_led
    id: switch_led
    pin:
      number: GPIO13
      inverted: true

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs). esphome/esphome-docs#1354

### CODE REVIEW

File: esphome/components/status_led/status_led.cpp [hunk 1]
```diff
@@ -20,12 +20,22 @@ void StatusLED::dump_config() {
   LOG_PIN("  Pin: ", this->pin_);
 }
 void StatusLED::loop() {
-  if ((App.get_app_state() & STATUS_LED_ERROR) != 0u) {
+  static uint32_t last_led_state{0};
```
Comment (OttoWinter) [inline esphome/components/status_led/status_led.cpp]: This should be a member variable - global state variables like this should be avoided

File: esphome/components/status_led/status_led.cpp [hunk 2]
```diff
@@ -20,12 +20,22 @@ void StatusLED::dump_config() {
...
     this->pin_->digital_write(millis() % 1500u < 250u);
-  } else {
-    this->pin_->digital_write(false);
+    last_led_state = new_state;
+  } else if (new_state != last_led_state) {
+    // if no error/warning -> restore light state or turn off
+    bool state = false;
+    if (this->light_state_)
+      this->light_state_->current_values_as_binary(&state);
+    this->pin_->digital_write(state);
```
Comment (OttoWinter) [inline esphome/components/status_led/status_led.cpp]: This architecture does not look good. This is trying to "copy" the state of the light, right? `current_values_as_binary` is more of an internal API that light outputs can use to know what to output, but not for external use.

I think this component should rather _write_ to the LightState (using `turn_on/off`)

File: esphome/components/status_led/status_led.h [hunk 3]
```diff
@@ -2,6 +2,7 @@
 
 #include "esphome/core/component.h"
 #include "esphome/core/esphal.h"
+#include "esphome/components/light/light_state.h"
```
Comment (OttoWinter) [inline esphome/components/status_led/status_led.h]: All the code that references `light` needs to be wrapped in `#ifdef USE_LIGHT`. Otherwise a compile fails if you don't have a `light` declared in your config (just a status_led)

File: esphome/components/status_led/status_led.cpp (hunk 2 above)
Comment (ianchi) [reply esphome/components/status_led/status_led.cpp]: The problem is exactly that, we need to re-output the current state of the light, but status_led doesn't know it.
I found no way to ask LightState to write the current output again, without reading it first to know if we need to call `turn_on` or `turn_off`.
One could do two `toggle` in succession to go back to the original state, but I think that is really ugly.
There are other *"inconsistencies"* and possibilities, that I laid out in the first post under "to think over*, and it is why I sent this as a RFC.

File: esphome/components/status_led/status_led.cpp (hunk 1 above)
Comment (ianchi) [reply esphome/components/status_led/status_led.cpp]: Changed to member variable

File: esphome/components/status_led/status_led.h (hunk 3 above)
Comment (ianchi) [reply esphome/components/status_led/status_led.h]: added conditional compilation

File: esphome/components/status_led/status_led.cpp (hunk 2 above)
Comment (ianchi) [reply esphome/components/status_led/status_led.cpp]: Changed the way of the call to try to minimize this issue

File: esphome/components/status_led/status_led.h (hunk 3 above)
Comment (ianchi) [reply esphome/components/status_led/status_led.h]: ... but still having errors.
It seems I get different results for the `#ifdef` in the .h and the .cpp
Any suggestion?

File: esphome/components/status_led/status_led.cpp (hunk 2 above)
Comment (ianchi) [reply esphome/components/status_led/status_led.cpp]: An afterthought: if we write through the `light` and there is some inconsistency in the yaml and it doesn't use the same pin, it could happen that we write to a pin that is not yet setup, if it happens in the pre-setup phase

File: esphome/components/status_led/status_led.h (hunk 3 above)
Comment (ianchi) [reply esphome/components/status_led/status_led.h]: Think I figured it out

**Comment by ianchi** [comment]
Tough the above approach is working, it still has the potential inconsistencies in the `light` definition.
An alternative could be to also define `status_led` as a platform for light, something like this:

````YAML
status_led:
  pin: GPIO04

light:
  - platform: status_led
````
So if you want to have a shared status led, you explicitly shared the status_led as a light, and so it already knows which pin to use, and we ensure that it is indeed a binary light, and not any possible light attached to any possible output.

This is optional, and if not exposed as light you get the current behavior, so it remains backwards compatible.

I have two problems to implement this, on the python side, when checking the yaml:

1.  When there is a `platform: status_led` we need to check if there is also a first level `status_led`, and error if it is not present.
As adding an explicit ID reference to use the standard check would be redundant, I'm not sure how to check it. 

````YAML
# ERROR

# status_led:

light:
  - platform: status_led
````

2. Error if two instances of `platform: status_led` are defined
````YAML

# ERROR
status_led:
  pin: GPIO04

light:
  - platform: status_led
  - platform: status_led
````

@OttoWinter please your thoughts on the best approach, and eventually any hint on solving this issues.

**Comment by ianchi** [comment]
Hi @OttoWinter, any thoughts on this?
Please let me know if any change is needed.

**Comment by ianchi** [comment]
Friendly ping

**Comment by OttoWinter** [comment]
> When there is a platform: status_led we need to check if there is also a first level status_led, and error if it is not present.
> Error if two instances of platform: status_led are defined

Yes - but I think another equivalent way would solve this better:

Have `status_led` be a light platform, but don't modify the existing `status_led` in any way.

```python3
# esphome/components/status_led/light/__init__.py
from esphome import pins
import esphome.codegen as cg
import esphome.config_validation as cv
from esphome.components import light
from esphome.const import CONF_OUTPUT_ID, CONF_PIN
from .. import status_led_ns

StatusLEDLightOutput = status_led_ns.class_("StatusLEDLightOutput", light.LightOutput)

CONFIG_SCHEMA = light.BINARY_LIGHT_SCHEMA.extend(
    {
        cv.GenerateID(CONF_OUTPUT_ID): cv.declare_id(StatusLEDLightOutput),
        cv.Required(CONF_PIN): pins.gpio_output_pin_schema,
    }
)


async def to_code(config):
    var = cg.new_Pvariable(config[CONF_OUTPUT_ID])
    await light.register_light(var, config)
    # ...

    pin = await cg.gpio_pin_expression(config[CONF_PIN])
    cg.add(var.set_pin(pin))
```

```cpp
// esphome/components/status_led/light/status_led_light.h
#pragma once

#include "esphome/core/component.h"
#include "esphome/core/esphal.h"
#include "esphome/components/light/light_output.h"

namespace esphome {
namespace status_led {

class StatusLEDLightOutput : public light::LightOutput, public Component {
 public:
  void set_pin(GPIOPin *pin) { pin_ = pin; }
  light::LightTraits get_traits() override {
    auto traits = light::LightTraits();
    traits.set_supports_brightness(false);
    return traits;
  }
  void loop() {
	// figure out what to write to the pin
    // from this->chosen_value_ (what the user selected in the frontend)
    // and from App.get_app_state() as in your PR
    this->pin_->digital_write(binary);
  }
  void write_state(light::LightState *state) override {
    bool binary;
    state->current_values_as_binary(&binary);
    chosen_value_ = binary;
    
  }

 protected:
  GPIOPin *pin_;
  bool chosen_value_;
};

}  // namespace status_led
}  // namespace esphome
```

This way the main status led no longer needs to interact with light, you can even have multiple status LED lights, and so on. Let me know if that would work

**Comment by ianchi** [comment]
Hi @OttoWinter, I'm not sure I follow the idea.

As I see it, the situation is the following, we want to share a single output for two uses: `status_led` and a binary `light`.
This can be done in two broad ways:
+ *Use independently*: each one uses the led independently and without knowing of the other. The only change needed is just that `status_led` instead of continuously overwriting the led to the *off* position when on *normal* state, write only once (turn off) on change, and so leave the led alone to be used by any other service. When on *error/warning* `status_led` continuously updates led (overriding any `light` use) to indicate the abnormal state. The `light` is a normal binary light that writes to the led  whenever it needs, regardless of app status (it will only effectivly show if we are not on *error/warning*).
+ *Use coordinately*: Main difference is that if `status_led` knows the led is being shared, so when it returns to *normal* state, instead of blindly turning it off, it restores the current state of the `light`. In this way, when on *normal*  the led **always** reflects the `light` value, regardless of the order of events. For this, the main additional change in logic should be on the `status_led` side.

I don't see the need to coordinate from the `light` to the `status_led`. The `light` can write to the led independently of what the app status is, as anyhow the `status_led` would overwrite every few milliseconds if needed, so there is no practical use of knowing the app state inside the `light`.
So, in this context, if we go for *"use independently"*, we don't even need a new light platform for `status_led`. 
This would be a very small PR, changing only *status_led.cpp* and only adding the *new_state* check before writing.

If we go for *"use coordinately"* there are more things to consider to enssure a consistent coordination.

**Comment by OttoWinter** [comment]
The thing is, `status_led` is a very core component that is loaded even in OTA safe mode. The default `status_led` should not interact at all with other objects, as then it's easy to brick a device.

What I'm proposing is for the feature of controlling an LED _both_ for showing status, _and_ for use as a binary light (I think that's what you meant too, right?)

Instead of modifying the core `status_led` _component_, we can just _add_ a new `status_led` light platform. This new platform does pretty much the same thing as the normal status led:

1. Reads `App.get_app_state()`
2. Figure out what binary signal to write to the LED by combining the status together with the chosen binary light status (like in this PR)
3. Write the value to the GPIO pin.

Then you don't have any communication between different components - the status_led core is unchanged and the light platform only reads from `App.get_app_state()`.

**Comment by ianchi** [comment]
So, if I understand you correctly, if you want current *unshared* behavior you include a high level `status_led` *component* if you want the new  *shared* behavior you **don't** include that, but a new `status_led` light platform.

I'll try this out later and update the PR.

**Comment by ianchi** [comment]
Hi @OttoWinter, I changed the PR with the new approach.
If everything is OK I'll update docs accordingly and send a PR there.

**Review by OttoWinter — APPROVED** [review]
LGTM, thanks! :+1:

**Comment by ianchi** [comment]
Added documentation:
esphome/esphome-docs#1354

**Comment by ianchi** [comment]
Hi @OttoWinter, I need your help here.
This new approach is not working.

I added some debug logs and found out that Component's life cicle methods where not being called (`setup`, `dump_config`, `loop`).
I realized that the `register_component` call was missing, but even after adding it I still don't see any of the calls.
The `light` functionality is working, but not the `status_led` part.

I don't get why none of these methods are being called. Any hint?

**Comment by ianchi** [comment]
Error in the CI checks pointed to the problem.
I split the code into a .cpp file and now it seems to be working.

But after the first OTA update I'm getting a new strange error:

```
[W][ota:287]: Update end failed! Error: ERROR[10]: Magic byte is wrong, not 0xE9

```

**Comment by ianchi** [comment]
Everything is working ok now, after .cpp split. Only working on a strange failing test.

It was a faulty power supply causing issues on flash write. Completely unrelated to this PR.

**Comment by ianchi** [comment]
Hi @OttoWinter, I've spent quite some time and a lot of trials but can't find why I get this error on the CI Test:

```
Error: /__w/esphome/esphome/esphome/components/status_led/light/status_led_light.h:16:12: error: no member named 
'set_supports_brightness' in 'esphome::light::LightTraits' [clang-diagnostic-error]
    traits.set_supports_brightness(false);
           ^
```

I don't understand why the error, because the header is included and `esphome::light::LightTraits` does have a `set_supports_brightness` member.
This started when I split into .h and .cpp in order to solve other logging errors.
Despite the error, locally it compiles and runs OK.

I think this is the only thing left, could you please help me here with some hint?

**Review by OttoWinter — APPROVED** [review]
Thanks for working on this!

I've fixed the error (caused by upstream changes committed in between), and this looks done to me now, thanks!
