### ISSUE TITLE
[ESP32-C6] `component.h:3:10: fatal error: cmath: No such file or directory`

### ISSUE THREAD

**Issue by ireun** [OttoWinter/esphomeyaml#9623]
### The problem

After upgrading to 2025.7.1 (no error at 2025.7.0) I cannot compile ESPHome for ESP32-C6 

### Which version of ESPHome has the issue?

2025.7.1

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### YAML Config

```yaml
esphome:
  name: "esphome-esp32c6-sypialnia"
  friendly_name: Sypialnia

esp32:
  board: esp32-c6-devkitc-1
  flash_size: 16MB
  framework:
    type: esp-idf

i2c:
  scl: 6
  sda: 5
#  scan: false

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "XXX"

ota:
  - platform: esphome
    password: "XXX"

wifi:
  domain: ""
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32C6 Fallback Hotspot"
    password: "XXX"

captive_portal:

esp32_ble_tracker:

ble_client:
  - mac_address: XXX
    id: oclean

sensor:
  - platform: bme280_i2c
    temperature:
      name: "BME280 Temperature"
      accuracy_decimals: 2
      oversampling: 16x
    pressure:
      name: "BME280 Pressure"
      oversampling: 16x
    humidity:
      name: "BME280 Humidity"
      oversampling: 16x
    address: 0x76
    update_interval: 10s
    iir_filter: 16x
  - platform: ble_client
    type: characteristic
    ble_client_id: oclean
    name: "Oclean Air"
    service_uuid: '180f'
    characteristic_uuid: '2a19'
    device_class: "battery"
    unit_of_measurement: "%"
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2025.7.1
INFO Reading configuration /config/esphome-esp32c6-sypialnia.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing esphome-esp32c6-sypialnia (board: esp32-c6-devkitc-1; framework: espidf; platform: https://github.com/pioarduino/platform-espressif32/releases/download/53.03.13/platform-espressif32.zip)
--------------------------------------------------------------------------------
Library Manager: Installing esphome/noise-c @ 0.1.10
INFO Installing esphome/noise-c @ 0.1.10
Unpacking  [####################################]  100%
Library Manager: noise-c@0.1.10 has been installed!
INFO noise-c@0.1.10 has been installed!
Library Manager: Resolving dependencies...
INFO Resolving dependencies...
Library Manager: Installing esphome/libsodium @ 1.10020.7
INFO Installing esphome/libsodium @ 1.10020.7
Unpacking  [####################################]  100%
Library Manager: libsodium@1.10020.7 has been installed!
INFO libsodium@1.10020.7 has been installed!
HARDWARE: ESP32C6 160MHz, 320KB RAM, 8MB Flash
 - framework-espidf @ 3.50302.0 (5.3.2) 
 - tool-cmake @ 3.30.2 
 - tool-esptoolpy @ 4.8.6 
 - tool-mklittlefs @ 3.2.0 
 - tool-ninja @ 1.7.1 
 - tool-riscv32-esp-elf-gdb @ 14.2.0+20240403 
 - tool-xtensa-esp-elf-gdb @ 14.2.0+20240403 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-riscv32-esp @ 13.2.0+20240530
Reading CMake configuration...
Generating assembly for certificate bundle...
Dependency Graph
|-- noise-c @ 0.1.10
Compiling .pioenvs/esphome-esp32c6-sypialnia/src/esphome/components/api/api_connection.cpp.o
Compiling .pioenvs/esphome-esp32c6-sypialnia/src/esphome/components/api/api_frame_helper.cpp.o
In file included from src/esphome/components/api/api_connection.h:5,
                 from src/esphome/components/api/api_connection.cpp:1:
src/esphome/components/api/api_frame_helper.h:2:10: fatal error: cstdint: No such file or directory
    2 | #include <cstdint>
      |          ^~~~~~~~~
compilation terminated.
Compiling .pioenvs/esphome-esp32c6-sypialnia/src/esphome/components/api/api_pb2.cpp.o
*** [.pioenvs/esphome-esp32c6-sypialnia/src/esphome/components/api/api_connection.cpp.o] Error 1
In file included from src/esphome/components/api/api_frame_helper.cpp:1:
src/esphome/components/api/api_frame_helper.h:2:10: fatal error: cstdint: No such file or directory
    2 | #include <cstdint>
      |          ^~~~~~~~~
compilation terminated.
*** [.pioenvs/esphome-esp32c6-sypialnia/src/esphome/components/api/api_frame_helper.cpp.o] Error 1
In file included from src/esphome/components/api/proto.h:3,
                 from src/esphome/components/api/api_pb2.h:7,
                 from src/esphome/components/api/api_pb2.cpp:3:
src/esphome/core/component.h:3:10: fatal error: cmath: No such file or directory
    3 | #include <cmath>
      |          ^~~~~~~
compilation terminated.
*** [.pioenvs/esphome-esp32c6-sypialnia/src/esphome/components/api/api_pb2.cpp.o] Error 1
========================= [FAILED] Took 13.62 seconds =========================
```

**Comment by jesserockz** [comment]
Have you tried cleaning the build files?

**Comment by ireun** [comment]
I think so, I will try again just to be sure..

EDIT: Yes, still an issue
```txt
INFO ESPHome 2025.7.1
INFO Reading configuration /config/esphome-esp32c6-sypialnia.yaml...
INFO Deleting /config/.esphome/build/esphome-esp32c6-sypialnia/.pioenvs
INFO Deleting /config/.esphome/build/esphome-esp32c6-sypialnia/.piolibdeps
INFO Done!

====================

INFO ESPHome 2025.7.1
INFO Reading configuration /config/esphome-esp32c6-sypialnia.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing esphome-esp32c6-sypialnia (board: esp32-c6-devkitc-1; framework: espidf; platform: https://github.com/pioarduino/platform-espressif32/releases/download/53.03.13/platform-espressif32.zip)
--------------------------------------------------------------------------------
Library Manager: Installing esphome/noise-c @ 0.1.10
INFO Installing esphome/noise-c @ 0.1.10
Unpacking  [####################################]  100%
Library Manager: noise-c@0.1.10 has been installed!
INFO noise-c@0.1.10 has been installed!
Library Manager: Resolving dependencies...
INFO Resolving dependencies...
Library Manager: Installing esphome/libsodium @ 1.10020.7
INFO Installing esphome/libsodium @ 1.10020.7
Unpacking  [####################################]  100%
Library Manager: libsodium@1.10020.7 has been installed!
INFO libsodium@1.10020.7 has been installed!
HARDWARE: ESP32C6 160MHz, 320KB RAM, 8MB Flash
 - framework-espidf @ 3.50302.0 (5.3.2) 
 - tool-cmake @ 3.30.2 
 - tool-esptoolpy @ 4.8.6 
 - tool-mklittlefs @ 3.2.0 
 - tool-ninja @ 1.7.1 
 - tool-riscv32-esp-elf-gdb @ 14.2.0+20240403 
 - tool-xtensa-esp-elf-gdb @ 14.2.0+20240403 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-riscv32-esp @ 13.2.0+20240530
Reading CMake configuration...
Generating assembly for certificate bundle...
Dependency Graph
|-- noise-c @ 0.1.10
Compiling .pioenvs/esphome-esp32c6-sypialnia/src/esphome/components/api/api_connection.cpp.o
Compiling .pioenvs/esphome-esp32c6-sypialnia/src/esphome/components/api/api_frame_helper.cpp.o
In file included from src/esphome/components/api/api_connection.h:5,
                 from src/esphome/components/api/api_connection.cpp:1:
src/esphome/components/api/api_frame_helper.h:2:10: fatal error: cstdint: No such file or directory
    2 | #include <cstdint>
      |          ^~~~~~~~~
compilation terminated.
Compiling .pioenvs/esphome-esp32c6-sypialnia/src/esphome/components/api/api_pb2.cpp.o
*** [.pioenvs/esphome-esp32c6-sypialnia/src/esphome/components/api/api_connection.cpp.o] Error 1
In file included from src/esphome/components/api/api_frame_helper.cpp:1:
src/esphome/components/api/api_frame_helper.h:2:10: fatal error: cstdint: No such file or directory
    2 | #include <cstdint>
      |          ^~~~~~~~~
compilation terminated.
*** [.pioenvs/esphome-esp32c6-sypialnia/src/esphome/components/api/api_frame_helper.cpp.o] Error 1
In file included from src/esphome/components/api/proto.h:3,
                 from src/esphome/components/api/api_pb2.h:7,
                 from src/esphome/components/api/api_pb2.cpp:3:
src/esphome/core/component.h:3:10: fatal error: cmath: No such file or directory
    3 | #include <cmath>
      |          ^~~~~~~
compilation terminated.
*** [.pioenvs/esphome-esp32c6-sypialnia/src/esphome/components/api/api_pb2.cpp.o] Error 1
========================= [FAILED] Took 16.11 seconds =========================
```

**Comment by bdraco** [comment]
Try reinstalling the Home Assistant ESPHome add-on. It's likely your local build environment got corrupted somehow.

**Comment by ireun** [comment]
@bdraco nope.. I'm running official ESPHome docker image.. There is not much to 'reinstall' 
```yaml
services:
  esphome:
    dns:
    - "192.168.1.1"
    container_name: esphome
    image: ghcr.io/esphome/esphome:latest
    volumes:
      - /root/esphome/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
```

```
Image 	ghcr.io/esphome/esphome:latest@sha256:d064f3943865c0e4cea47b14c162ceb1c61695642dd02c239e80656a06eeeee0
```

**Comment by ssieb** [comment]
Then rebuild it or delete the platformio cache.

**Comment by ireun** [comment]
All right, recreated the container, removed `./config/.esphome/` dir and seems to fixed itself. Thanks!
