### PR TITLE
Support voluptuous 0.11.7

### LINKED ISSUE #580: cant start esphome wizzard
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
 Hassbian (installed with pip)

**ESP (ESP32/ESP8266, Board/Sonoff):**

**Affected component:**

**Description of problem:**
I am using Hassbian and installed esphome succesfully with `pip install esphome`
I tried to start esphome with `esphome livingroom.yaml wizard` for the first time but I get the following error:

**Problem-relevant YAML-configuration entries:**

**Logs (if applicable):**

```
pi@hassbian:/ $ esphome livingroom.yaml wizard
Traceback (most recent call last):
  File "/usr/local/bin/esphome", line 6, in <module>
    from esphome.__main__ import main
  File "/usr/local/lib/python2.7/dist-packages/esphome/__main__.py", line 10, in <module>
    from esphome import const, writer, yaml_util
  File "/usr/local/lib/python2.7/dist-packages/esphome/writer.py", line 7, in <module>
    from esphome.config import iter_components
  File "/usr/local/lib/python2.7/dist-packages/esphome/config.py", line 15, in <module>
    from esphome import core, core_config, yaml_util
  File "/usr/local/lib/python2.7/dist-packages/esphome/core_config.py", line 6, in <module>
    import esphome.config_validation as cv
  File "/usr/local/lib/python2.7/dist-packages/esphome/config_validation.py", line 1242, in <module>
    Optional(CONF_COMMAND_TOPIC): All(requires_component('mqtt'), subscribe_topic),
  File "/usr/local/lib/python2.7/dist-packages/esphome/voluptuous_schema.py", line 198, in extend
    ret = super(_Schema, self).extend(schema, extra=extra)
  File "/usr/local/lib/python2.7/dist-packages/voluptuous/schema_builder.py", line 782, in extend
    return result_cls(result, required=result_required, extra=result_extra)
TypeError: __init__() got an unexpected keyword argument 'required'

```

**Additional information and things you've tried:**

### PR DESCRIPTION
**Pull request by AlexMekkering**
## Description:

This adds support for voluptuous 0.11.7 (incompatibilities introduced by alecthomas/voluptuous#380). This change is verified to still work with voluptuous 0.11.5.

*This Pull Request also contains a fix for platformio 4 in travis-ci builds.*

**Related issue (if applicable):** fixes esphome/issues#580

## Checklist:
  - [x] The code change is tested and works locally.

### CODE REVIEW

**Comment by brandond** [comment]
LGTM. Merging since @OttoWinter  appears to be on holiday.
