### ISSUE TITLE
Error compilation with new version 2025.10.0

### ISSUE THREAD

**Issue by Hornett69** [OttoWinter/esphomeyaml#11256]
### The problem

The problem
After updating to 2025.10.0, i have a compilation error during wirelessly install on my ESP32. Before this version i have no problem during compilation and and firmware installation.

[Logs Détecteur WC.txt](https://github.com/user-attachments/files/22923216/Logs.Detecteur.WC.txt)

### Which version of ESPHome has the issue?

2025.10.0

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Component causing the issue

detecteur-wc

### YAML Config

```yaml
esphome:
  name: detecteur-wc
  friendly_name: Détecteur WC

esp32:
  board: lolin_s2_mini
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

ota:
- platform: esphome
  password: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Detecteur-Wc Fallback Hotspot"
    password: "XXXXXXXXXXXXXXXXX"

captive_portal:

# Indicateur de connection avec la LED carte ESP32 S2 --> GPIO15
light:
  - platform: status_led
    pin: GPIO15
    id: Led_connected_wifi
#    inverted: True

# Test WIFI si connecté et allume voyant led de ma carte
# Cela permet de constater visuellement lorsque la carte s'active et se connecte au wifi
interval:
  - interval: 60s
    then:
      if:
        condition:
          wifi.connected:
        then:
          - light.turn_on: Led_connected_wifi
          - logger.log: WiFi is connected!
          - delay: 1s
          - light.turn_off: Led_connected_wifi
        else:
          - light.turn_off: Led_connected_wifi
          - logger.log: WiFi is disconnected!

# Capteur HLK-LD2410C 24G
uart:
  tx_pin: GPIO18
  rx_pin: GPIO33
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

ld2410:

binary_sensor:
  - platform: ld2410
    has_target:
      name: Presence
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target
    out_pin_presence_status:
      name: out pin presence status
  - platform: gpio
    pin: GPIO16
    name: gpio out pin presence
    device_class: presence

sensor:
  - platform: ld2410
    light:
      name: light
    moving_distance:
      name : Moving Distance
    still_distance:
      name: Still Distance
    moving_energy:
      name: Move Energy
    still_energy:
      name: Still Energy
    detection_distance:
      name: Detection Distance
    g0:
      move_energy:
        name: g0 move energy
      still_energy:
        name: g0 still energy
    g1:
      move_energy:
        name: g1 move energy
      still_energy:
        name: g1 still energy
    g2:
      move_energy:
        name: g2 move energy
      still_energy:
        name: g2 still energy
    g3:
      move_energy:
        name: g3 move energy
      still_energy:
        name: g3 still energy
    g4:
      move_energy:
        name: g4 move energy
      still_energy:
        name: g4 still energy
    g5:
      move_energy:
        name: g5 move energy
      still_energy:
        name: g5 still energy
    g6:
      move_energy:
        name: g6 move energy
      still_energy:
        name: g6 still energy
    g7:
      move_energy:
        name: g7 move energy
      still_energy:
        name: g7 still energy
    g8:
      move_energy:
        name: g8 move energy
      still_energy:
        name: g8 still energy

switch:
  - platform: ld2410
    engineering_mode:
      name: "engineering mode"
    bluetooth:
      name: "control bluetooth"

number:
  - platform: ld2410
    timeout:
      name: timeout
    light_threshold:
      name: light threshold
    max_move_distance_gate:
      name: max move distance gate
    max_still_distance_gate:
      name: max still distance gate
    g0:
      move_threshold:
        name: g0 move threshold
      still_threshold:
        name: g0 still threshold
    g1:
      move_threshold:
        name: g1 move threshold
      still_threshold:
        name: g1 still threshold
    g2:
      move_threshold:
        name: g2 move threshold
      still_threshold:
        name: g2 still threshold
    g3:
      move_threshold:
        name: g3 move threshold
      still_threshold:
        name: g3 still threshold
    g4:
      move_threshold:
        name: g4 move threshold
      still_threshold:
        name: g4 still threshold
    g5:
      move_threshold:
        name: g5 move threshold
      still_threshold:
        name: g5 still threshold
    g6:
      move_threshold:
        name: g6 move threshold
      still_threshold:
        name: g6 still threshold
    g7:
      move_threshold:
        name: g7 move threshold
      still_threshold:
        name: g7 still threshold
    g8:
      move_threshold:
        name: g8 move threshold
      still_threshold:
        name: g8 still threshold

button:
  - platform: ld2410
    factory_reset:
      name: "factory reset"
    restart:
      name: "restart"
    query_params:
      name: query params

text_sensor:
  - platform: ld2410
    version:
      name: "firmware version"
    mac_address:
      name: "mac address"

select:
  - platform: ld2410
    distance_resolution:
      name: "distance resolution"
    baud_rate:
      name: "baud rate"
    light_function:
      name: light function
    out_pin_level:
      name: out pin level

# - bluetooth_password.set:
#     id: my_ld2410
#     password: "XXXXXXXXXXXXXX"
```

### Anything in the logs that might be useful for us?

```txt
Compiling .pioenvs/detecteur-wc/chip-debug-report.cpp.o
Compiling .pioenvs/detecteur-wc/esp32-hal-adc.c.o
Compiling .pioenvs/detecteur-wc/esp32-hal-bt.c.o
In file included from /config/.esphome/platformio/packages/framework-arduinoespressif32/cores/esp32/Arduino.h:202,
                 from /config/.esphome/platformio/packages/framework-arduinoespressif32/cores/esp32/chip-debug-report.cpp:17:
/config/.esphome/platformio/packages/framework-arduinoespressif32/cores/esp32/chip-debug-report.cpp: In function 'void printBeforeSetupInfo()':
/config/.esphome/platformio/packages/framework-arduinoespressif32/cores/esp32/HardwareSerial.h:416:16: error: 'USBSerial' was not declared in this scope; did you mean 'Serial'?
  416 | #define Serial USBSerial
      |                ^~~~~~~~~
/config/.esphome/platformio/packages/framework-arduinoespressif32/cores/esp32/chip-debug-report.cpp:294:3: note: in expansion of macro 'Serial'
  294 |   Serial.begin(0);
      |   ^~~~~~
Compiling .pioenvs/detecteur-wc/esp32-hal-cpu.c.o
*** [.pioenvs/detecteur-wc/chip-debug-report.cpp.o] Error 1
========================= [FAILED] Took 410.18 seconds =========================
```

**Comment by edwardtfn** [comment]
Have you tried changing the framework type to `esp-idf`?

**Comment by JamesDilan** [comment]
Good day, Same issue here. I'm also using a lolin_s2_mini board, so I think that's the common factor. I wasn't able to try the ESP-IDF framework since I'm using Arduino libraries.

**Comment by randybb** [comment]
Looks like the board profile is causing issues. By switching from `board:` to `variant:` it is compiling fine with arduino and esp-idf (preferred):

```yaml
esp32:
  variant: esp32s2
  framework:
    type: arduino
    # type: esp-idf
```

**Comment by Hornett69** [comment]
I did several tests..

**Test 1  : Compilation KO**
```
esp32:
  board: lolin_s2_mini
  #variant: esp32s2
  framework:
    type: arduino
    # type: esp-idf
```

**Test 2 : Compilation OK**
```
esp32:
  #board: lolin_s2_mini
  variant: esp32s2
  framework:
    type: arduino
    # type: esp-idf
```

**Test 3 : Compilation OK** 
```
esp32:
  board: lolin_s2_mini
  #variant: esp32s2
  framework:
    #type: arduino
     type: esp-idf
```

**Test 4 : Compilation OK**
```
esp32:
  #board: lolin_s2_mini
  variant: esp32s2
  framework:
   #type: arduino
    type: esp-idf
```

Tanks for your help.
