### PR TITLE
i2c: fix build on ESP-IDF >= 5.1

### PR DESCRIPTION
**Pull request by stintel**
# What does this implement/fix?

As of version 5.1, i2c_port_t is an enum.

Compile error before this change:

```
src/esphome/components/i2c/i2c_bus_esp_idf.cpp:18:33: error: invalid conversion from 'int' to 'i2c_port_t' [-fpermissive]
   18 |   static i2c_port_t next_port = 0;
      |                                 ^
      |                                 |
      |                                 int
src/esphome/components/i2c/i2c_bus_esp_idf.cpp:19:20: error: no 'operator++(int)' declared for postfix '++' [-fpermissive]
   19 |   port_ = next_port++;
      |           ~~~~~~~~~^~
```

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** NA

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** NA

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
esphome:
  name: bug

esp32:
  board: esp32-c3-devkitm-1
  framework:
    platform_version: https://github.com/platformio/platform-espressif32
    type: esp-idf
    version: 5.1.0

i2c:
  sda: 4
  scl: 5

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by jesserockz — CHANGES_REQUESTED** [review]
This still needs to increment the port in each setup...

**Comment by stintel** [comment]
> This still needs to increment the port in each setup...

Sorry about that. When I initially did this change I was in "let's just get things to compile" mode. Should have reviewed before opening the PR.

Should be better now. I don't like how it looks, but don't have any better ideas.

File: esphome/components/i2c/i2c_bus_esp_idf.cpp [hunk 1]
```diff
@@ -15,8 +15,18 @@ static const char *const TAG = "i2c.idf";
 
 void IDFI2CBus::setup() {
   ESP_LOGCONFIG(TAG, "Setting up I2C bus...");
+#if ESP_IDF_VERSION >= ESP_IDF_VERSION_VAL(5, 1, 0)
```
Comment (jesserockz) [inline esphome/components/i2c/i2c_bus_esp_idf.cpp]: I actually dont think we need to check for idf 5.1, all of the used "variables" are available on the current 4.4, just as defines instead of the enums

Comment (stintel) [reply esphome/components/i2c/i2c_bus_esp_idf.cpp]: Good catch! Updated and compile-tested with IDF 4.4 and 5.1.

File: esphome/components/i2c/i2c_bus_esp_idf.cpp [hunk 2]
```diff
@@ -15,8 +15,13 @@ static const char *const TAG = "i2c.idf";
...
   ESP_LOGCONFIG(TAG, "Setting up I2C bus...");
-  static i2c_port_t next_port = 0;
-  port_ = next_port++;
+  static i2c_port_t next_port = I2C_NUM_0;
+  port_ = next_port;
+#if I2C_NUM_MAX > 1
+  next_port = (next_port == I2C_NUM_0) ? I2C_NUM_1 : I2C_NUM_MAX;
+#else
+  next_port = I2C_NUM_MAX;
+#endif
```
Comment (jesserockz) [inline esphome/components/i2c/i2c_bus_esp_idf.cpp:25]:
```suggestion

if (port_ == I2C_NUM_MAX) {
  ESP_LOGE(TAG, "Too many I2C buses configured");
  this->mark_failed();
  return;
}

```

**Review by jesserockz — APPROVED** [review]
