### ISSUE TITLE
Install yaml fails with AttributeError: 'dict' object has no attribute 'move_to_end'

### ISSUE THREAD

**Issue by mikeygnyc** [OttoWinter/esphomeyaml#11182]
### The problem

Trying to install yaml on ESP32 results in a failure with error:
`AttributeError: 'dict' object has no attribute 'move_to_end'`

This occurs regardless of the method used to attempt installation.

### Which version of ESPHome has the issue?

2025.9.3

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Component causing the issue

substitutions

### YAML Config

```yaml
substitutions:
  name: ratgdo32disco-[redacted MAC address]
  friendly_name: Garage West
packages:
  ratgdo.esphome: github://ratgdo/esphome-ratgdo/v32disco_secplusv1.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: [redacted]
dashboard_import:
  package_import_url: github://ratgdo/esphome-ratgdov32disco_secplusv1.yaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


output:
  - id: !extend ${id_prefix}_beeper
    song: "Final Countdown:o=5,d=16,b=125,b=125:b,a,4b,4e,4p,8p,c6,b,8c6,8b,4a,4p,8p,c6,b,4c6,4e,4p,8p,a,g,8a,8g,8f#,8a,4g.,f#,g,4a.,g,a,8b,8a,8g,8f#,4e,4c6,2b.,b,c6,b,a,1b"
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2025.9.3
INFO Reading configuration /config/ratgdo32disco-[redacted MAC address].yaml...
ERROR Unexpected exception while reading configuration:
Traceback (most recent call last):
  File "/usr/local/bin/esphome", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/esphome/esphome/__main__.py", line 1269, in main
    return run_esphome(sys.argv)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 1247, in run_esphome
    config = read_config(dict(args.substitution) if args.substitution else {})
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/config.py", line 1184, in read_config
    res = load_config(command_line_substitutions)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/config.py", line 1041, in load_config
    return _load_config(command_line_substitutions)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/config.py", line 1031, in _load_config
    return validate_config(config, command_line_substitutions)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/config.py", line 880, in validate_config
    substitutions.do_substitution_pass(config, command_line_substitutions)
  File "/esphome/esphome/components/substitutions/__init__.py", line 194, in do_substitution_pass
    config.move_to_end(CONF_SUBSTITUTIONS, False)
    ^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'move_to_end'
```

**Comment by ssieb** [comment]
You can't have a `.` in the package key.

**Comment by ssieb** [comment]
Actually, my test was wrong, that's ok.

However, the pasted config must not be exactly what you have.  The import url is invalid and after I fixed that, it compiles with no issues.

**Comment by mikeygnyc** [comment]
Interesting. I am able to confirm the same thing you did and was able to get it compiled after tweaking those fields. I think the error is a red herring that could be related to bad syntax in the config. Wondering if there would be some kind of way to add a linter or something that would squawk if you had an invalid config. The editor wasn't calling anything out in this case.

**Comment by ssieb** [comment]
We certainly try to provide a nice error if something is wrong.  Can you reproduce the issue again?  What exactly was the change to fix it?

**Comment by mikeygnyc** [comment]
The change was to just eliminate the substitution section and directly name the attributes in the esphome section since I unfortunately couldn't figure out why I was getting `AttributeError: 'dict' has no attribute 'move_to_end' `.  I also ultimately fixed the bad urls. 

I tried looking through the code to see if that provided any clues and I found a similar section that parsed the config and forces a cast of the config to `OrderedDict`(if it's not already) to avoid this issue. I tried patching the code to do that but it didn't seem to help. My Python isn't great but I couldn't really understand why else the error was getting thrown.

**Comment by txwindsurfer** [comment]
Having the same error running Esphome 2025,10.1 dashboard on my Windows computer compiling ratgdo.  I have no problem compiling ratgdo with the HA esphome addon running HA OS.  I thought I needed to update python in Windows and updated to 3.13.9 but python gives the same complaint.  Odd that it works on home assistant running HA OS but not in the Windows dashboard.

**Comment by bdraco** [comment]
substitutions merges but doesn't keep it as an OrderedDict

**Comment by bdraco** [comment]
but that would mean its been broken since #1014

**Comment by bdraco** [comment]
pretty sure there is a merging bug in config and subs

But without a reproducing config I'm not 100% sure thats the issue here. I'll fix the bug regardless but it may not fix this issue without a real reproducer

**Comment by mikeygnyc** [comment]
I can try and repro the issue from scratch. Here's what I did initially.

1) Installed the default ratgdo ESPHome FW on the ratgdo via their[ OTA-installer](https://ratgdo.github.io/esphome-ratgdo/). This worked fine. Had a working build with I think 2025.8.3 ESPHome as the base.

2) Tried to adopt the ratgdo from the ESPHome Dashboard on my dockerized server to customize. It was auto-discovered by the dashboard.

3) Tried to take control of the ratgdo. I was served the malformed YAML I posted above and got the `AttribueError` mentioned instead of anything about it being malformed. Made a couple changes to it and tried to build and still got the errors shown.

4) Tried a couple hand-corrections that didn't work, then realized I just needed to use their published ESPHome YAMLs from [their repo](https://github.com/RATGDO/esphome-ratgdo/tree/main/static) and modified that.

5) Compiled the new version and uploaded to the device over wifi.

6) Issue solved.

There are two separate issues here, one is that attempting to adopt the ratgdo returned a malformed YAML (not an ESPHome issue per se as far as I can tell) and the other is that compiling a malformed YAML fails for the "wrong" reason (this issue). I'm happy to go through the whole process with the  [PR above](https://github.com/esphome/esphome/pull/11274). I'll see if I can build a docker image with it and test against that.

**Comment by txwindsurfer** [comment]
@jesserockz Updated to esphome 2025.10.1 and tried to update ratgdo from the dashboard.  Got a different error this time. 
```
INFO ESPHome 2025.10.1
INFO Reading configuration c:\esphome\home\ratgdo32-2a6440.yaml...
ERROR Unexpected exception while reading configuration:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\reaga\AppData\Local\Programs\Python\Python313\Scripts\esphome.exe\__main__.py", line 6, in <module>
    sys.exit(main())
             ~~~~^^
  File "C:\Users\reaga\AppData\Local\Programs\Python\Python313\Lib\site-packages\esphome\__main__.py", line 1385, in main
    return run_esphome(sys.argv)
  File "C:\Users\reaga\AppData\Local\Programs\Python\Python313\Lib\site-packages\esphome\__main__.py", line 1360, in run_esphome
    config = read_config(
        dict(args.substitution) if args.substitution else {},
        skip_external_update=skip_external,
    )
  File "C:\Users\reaga\AppData\Local\Programs\Python\Python313\Lib\site-packages\esphome\config.py", line 1238, in read_config
    res = load_config(command_line_substitutions, skip_external_update)
  File "C:\Users\reaga\AppData\Local\Programs\Python\Python313\Lib\site-packages\esphome\config.py", line 1095, in load_config
    return _load_config(command_line_substitutions, skip_external_update)
  File "C:\Users\reaga\AppData\Local\Programs\Python\Python313\Lib\site-packages\esphome\config.py", line 1083, in _load_config
    return validate_config(config, command_line_substitutions, skip_external_update)
  File "C:\Users\reaga\AppData\Local\Programs\Python\Python313\Lib\site-packages\esphome\config.py", line 974, in validate_config
    target_platform = core_config.preload_core_config(config, result)
  File "C:\Users\reaga\AppData\Local\Programs\Python\Python313\Lib\site-packages\esphome\core\config.py", line 323, in preload_core_config
    if _is_target_platform(domain):
       ~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\reaga\AppData\Local\Programs\Python\Python313\Lib\site-packages\esphome\core\config.py", line 284, in _is_target_platform
    return get_component(name, True).is_target_platform
           ~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\reaga\AppData\Local\Programs\Python\Python313\Lib\site-packages\esphome\loader.py", line 222, in get_component
    assert "." not in domain
           ^^^^^^^^^^^^^^^^^
AssertionError
```

**Comment by jesserockz** [comment]
@txwindsurfer Please open a new issue with your full config as it is unrelated to this issue.
