### PR TITLE
[i2c] Use new driver with IDF 5.4.2+

### LINKED ISSUE #6639: ESP32-C6 cannot compile with I2C
### The problem

When compiling a scatch of ESP32C6 with I2C support, we get a build error that `I2C_NUM_1 ` is not defined. This is caused by the introduction of Low Power and normal I2C interfaces

See ESP-IDF define [here](https://github.com/espressif/esp-idf/blob/b5ac4fbdf9e9fb320bb0a98ee4fbaa18f8566f37/components/soc/esp32c6/include/soc/soc_caps.h#L241)

Could the code be fixed that compiling for C6 with I2C will work?/

### Which version of ESPHome has the issue?

ESPHome 2024.12.2

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2024.12

### What platform are you using?

ESP32-IDF

### Board

ESP32 -c6 devkit

### Component causing the issue

i2c

### YAML Config

```yaml
esphome:
  name: esp-airquality
  friendly_name: ESP-AirQuality

esp32:
  board: esp32-c6-devkitm-1
  variant: esp32c6
  framework:
    type: esp-idf
    platform_version: 6.9.0
    version: 5.3.1
    
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y

# Enable logging
logger:
  level: DEBUG


# Enable Home Assistant API
api:
  encryption:
    key: "8iXBbbHx0q/pJ2M6vluoet2YYJt08Aisku5o7985xwE="

ota:
  - platform: esphome
    password: "cc6e98f638c7ea1d1ac2827b0fb20aac"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Airquality Fallback Hotspot"
    password: "oBrE5snHIMtw"

captive_portal:
    
switch:
   - platform: gpio
     name: "on board LED"
     pin: GPIO15 

i2c:
  sda: GPIO6
  scl: GPIO7
  scan: true
  id: bus_a  

# Example configuration entry
sensor:
  - platform: scd4x
    co2:
      name: "CO2"
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2024.12.2
INFO Reading configuration config/esp-airquality.yaml...
WARNING The selected ESP-IDF framework version is not the recommended one. If there are connectivity or build issues please remove the manual version.
WARNING The selected ESP-IDF framework version is not the recommended one. If there are connectivity or build issues please remove the manual version.
WARNING GPIO15 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
INFO Generating C++ source...
INFO Updating https://github.com/espressif/esp-protocols.git@mdns-v1.3.2
INFO Compiling app...
Processing esp-airquality (board: esp32-c6-devkitm-1; framework: espidf; platform: platformio/espressif32@6.9.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32C6 160MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.50301.0 (5.3.1) 
 - tool-cmake @ 3.16.4 
 - tool-ninja @ 1.7.1 
 - tool-riscv32-esp-elf-gdb @ 12.1.0+20221002 
 - tool-xtensa-esp-elf-gdb @ 12.1.0+20221002 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-riscv32-esp @ 13.2.0+20240530
Reading CMake configuration...
Dependency Graph
|-- noise-c @ 0.1.6
Compiling .pioenvs/esp-airquality/src/esphome/components/i2c/i2c_bus_esp_idf.cpp.o
Compiling .pioenvs/esp-airquality/src/esphome/components/mdns/mdns_component.cpp.o
Compiling .pioenvs/esp-airquality/src/esphome/components/mdns/mdns_esp32.cpp.o
Compiling .pioenvs/esp-airquality/src/esphome/components/mdns/mdns_esp8266.cpp.o
Compiling .pioenvs/esp-airquality/src/esphome/components/mdns/mdns_host.cpp.o
Compiling .pioenvs/esp-airquality/src/esphome/components/mdns/mdns_libretiny.cpp.o
Compiling .pioenvs/esp-airquality/src/esphome/components/mdns/mdns_rp2040.cpp.o
Compiling .pioenvs/esp-airquality/src/esphome/components/network/util.cpp.o
src/esphome/components/i2c/i2c_bus_esp_idf.cpp: In member function 'virtual void esphome::i2c::IDFI2CBus::setup()':
src/esphome/components/i2c/i2c_bus_esp_idf.cpp:21:42: error: 'I2C_NUM_1' was not declared in this scope; did you mean 'I2C_NUM_0'?
   21 |   next_port = (next_port == I2C_NUM_0) ? I2C_NUM_1 : I2C_NUM_MAX;
      |                                          ^~~~~~~~~
      |                                          I2C_NUM_0
Compiling .pioenvs/esp-airquality/src/esphome/components/ota/ota_backend.cpp.o
*** [.pioenvs/esp-airquality/src/esphome/components/i2c/i2c_bus_esp_idf.cpp.o] Error 1
========================== [FAILED] Took 8.12 seconds ==========================
```

### Additional information

It seems that ESP32-C6 is handling Low Power I2C differently with other defines.

### PR DESCRIPTION
**Pull request by swoboda1337**
# What does this implement/fix?

The current i2c driver is being deprecated and is no longer being updated. Issues with the legacy/current driver:
- scan causes a watchdog on newer variants like P4 and C6
- low power ports are not supported in the legacy driver
- esp32 s2 had a bug limiting the max frequency to 50khz, fixed in 5.4.2

To use:
```
esp32:
  framework:
    type: esp-idf
    version: 5.4.2
    platform_version: 54.03.21

external_components:    
  - source: github://pr#8483
    components: [ i2c ]
```

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes https://github.com/esphome/issues/issues/6639

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by swoboda1337** [comment]
Noticed i2c started to fail after 24 on one device. Seems there is some instability.

**Comment by swoboda1337** [comment]
To summarize there are some stability issues but the driver is useable

**Comment by alex3305** [comment]
Maybe it's OT here, please tell me if it is. But I have tested this driver with my (very likely) fake BMP280 and what should be a real CCS811 and SCD40. The SCD40 is recognized correctly and works fine. But both the CCS811 and BMP280 report that the chip ID is wrong and don't initialize. Regardless of scanning, frequency or preset addresses in the sensor configuration.

I get that this is probably considered a hardware issue. On the other hand it can be considered a regression. Because these devices work with the current/legacy driver. Is there any way to get these sensors working with the new driver? Especially before it gets merged and enabled by default. Because I can imagine it is smart to get ahead of possibly large amount of bug reports or support requests of devices that 'suddenly' stopped working.

**Comment by swoboda1337** [comment]
> Maybe it's OT here, please tell me if it is. But I have tested this driver with my (very likely) fake BMP280 and what should be a real CCS811 and SCD40. The SCD40 is recognized correctly and works fine. But both the CCS811 and BMP280 report that the chip ID is wrong and don't initialize. Regardless of scanning, frequency or preset addresses in the sensor configuration.
> 
> I get that this is probably considered a hardware issue. On the other hand it can be considered a regression. Because these devices work with the current/legacy driver. Is there any way to get these sensors working with the new driver? Especially before it gets merged and enabled by default. Because I can imagine it is smart to get ahead of possibly large amount of bug reports or support requests of devices that 'suddenly' stopped working.

Which idf version did you try? You could try 5.5 and see if its any better. The never driver could still have some issues:
```
esp32:
  framework:
    type: esp-idf
    version: 5.5.0
    release: "ard33a"
    platform_version: 54.03.20

external_components:    
  - source: github://pr#8483
    components: [ i2c ]
```

**Comment by alex3305** [comment]
> Which idf version did you try? You could try 5.5 and see if its any better. The never driver could still have some issues:

Switching to IDF 5.5 did the trick 👍. Thanks!

I wanted to test it for some time before reporting back. But All I2C sensors seem to work now. The CCS811 is reporting some nonsense values, but I think that's something completely different. Perhaps some endianness that messed up my previous baseline value 🤷? Because restarting without baseline seems to fix it. I don't know, just a guess.

I'm going to keep this running for the foreseeable future to test stability, but it seems pretty darn good 😄. Thanks for your efforts and contribution!

**Comment by martijnbuts** [comment]
I also find out that the i2c port scan does not work on esp32 c6. I will use the pr and try again. Thanks for the time and effort 

Question: is there a difference in normal and low power i2c? Both in configuration and performance

**Comment by swoboda1337** [comment]
> I also find out that the i2c port scan does not work on esp32 c6. I will use the pr and try again. Thanks for the time and effort 
> 
> Question: is there a difference in normal and low power i2c? Both in configuration and performance 

FYI scan on C6 should work in 5.5 with the existing I2C driver, I made an IDF PR to fix that and it was merged:
```
esp32:
  framework:
    type: esp-idf
    version: 5.5.0
    release: "20250510"
    platform_version: 55.03.30-alpha1
```

**Comment by martijnbuts** [comment]
> > I also find out that the i2c port scan does not work on esp32 c6. I will use the pr and try again. Thanks for the time and effort
> > Question: is there a difference in normal and low power i2c? Both in configuration and performance
> 
> FYI scan on C6 should work in 5.5 with the existing I2C driver, I made an IDF PR to fix that and it was merged:
> 
> ```
> esp32:
>   framework:
>     type: esp-idf
>     version: 5.5.0
>     release: "20250510"
>     platform_version: 55.03.30-alpha1
> ```

Thanks, i give it a try tomorrow.  I really like the work you do for esphome!

**Comment by martijnbuts** [comment]
> > I also find out that the i2c port scan does not work on esp32 c6. I will use the pr and try again. Thanks for the time and effort
> > Question: is there a difference in normal and low power i2c? Both in configuration and performance
> 
> FYI scan on C6 should work in 5.5 with the existing I2C driver, I made an IDF PR to fix that and it was merged:
> 
> ```
> esp32:
>   framework:
>     type: esp-idf
>     version: 5.5.0
>     release: "20250510"
>     platform_version: 55.03.30-alpha1
> ```

if i use the version i get the following error

src/esphome/components/web_server_idf/web_server_idf.cpp: In static member function 'static esp_err_t esphome::web_server_idf::AsyncWebServer::request_post_handler(httpd_req_t*)':
src/esphome/components/web_server_idf/web_server_idf.cpp:85:24: error: 'HTTPD_MAX_REQ_HDR_LEN' was not declared in this scope; did you mean 'CONFIG_HTTPD_MAX_REQ_HDR_LEN'?
   85 |   if (r->content_len > HTTPD_MAX_REQ_HDR_LEN) {
      |                        ^~~~~~~~~~~~~~~~~~~~~
      |                        CONFIG_HTTPD_MAX_REQ_HDR_LEN
Compiling .pioenvs/esp32-c6_2/src/esphome/components/wifi/wifi_component_libretiny.cpp.o
Compiling .pioenvs/esp32-c6_2/src/esphome/components/wifi/wifi_component_pico_w.cpp.o
*** [.pioenvs/esp32-c6_2/src/esphome/components/web_server_idf/web_server_idf.cpp.o] Error 1

it does compile with by excluding the webserver v3 and the captive portal so i think a small change is needed in webserver or captive portal. 

But with the ESP-IDF 5.5.0 the scan does work
[08:42:43][I][app:115]: ESPHome version 2025.6.0-dev compiled on May 25 2025, 08:42:23
[08:42:43][I][i2c.idf:102]: Results from i2c bus scan:
[08:42:43][I][i2c.idf:108]: Found i2c device at address 0x3C

**Comment by alex3305** [comment]
Today I encountered something odd. Using the configuration that previously worked, suddenly ESPHome refused to compile with 5.5.0.

```yaml
esp32:
  board: esp32-c6-devkitm-1
  flash_size: 4MB
  variant: ESP32C6
  framework:
    type: esp-idf
    version: 5.5.0
    release: "ard33a"
    platform_version: 54.03.20

external_components:
  - source: github://pr#8483
    components: [i2c]
```

I also tried using `release: "20250510"`, but to no avail. The compiler kept complaining about a missing Python Module named rich in ESP-IDF 5.5.0. Cleaning the build files or even just removing the `.esphome` directory also did not work.

As a last resort I opted to manually install rich in my container:

```bash
# Enter the container
docker exec -it esphome bash

# Go to the build directory with the virtualenv
cd /root/.platformio/penv/.espidf-5.5.0

# Activate the virtual env
source bin/activate

# Install the missing dependency: rich
pip install rich
```

Really ugly, but that made ESPHome compile again 🤷. I don't know if it's caused by my configuration or ESP-IDF 5.5.0, but I suspect the latter since all of my devices refused to compile all of a sudden. And AFAIK those should all be in a separate virtualenv. Rolling back to a previous ESP-IDF version <5.4.0 also worked, but that undoes this PR 😒 .

In the mean time this PR seems rock solid on my ESP32-C6 with 5.5.0 👍 . I still experience connection stability issues, which I suspect are related to Bluetooth / Wi-Fi. But I2C is solid!

**Comment by swoboda1337** [comment]
Looking into the rich issue now

**Comment by swoboda1337** [comment]
> Today I encountered something odd. Using the configuration that previously worked, suddenly ESPHome refused to compile with 5.5.0.

Can build with:
```
    type: esp-idf
    version: 5.4.1
    platform_version: 55.03.30-alpha1
```
or
```
    type: esp-idf
    version: 5.5.0
    platform_version: 55.03.30-alpha1
```
For some reason 54.03.20 didnt pin esp-idf-kconfig and a recent upgrade broke things

**Comment by alex3305** [comment]
@swoboda1337 Thanks for looking into the 'rich issue'. I only posted it here as an FYI to others that want to try out your PR 🙂. I don't want to get too much off-topic, but the other platform version doesn't work for me either 😐 .

With
```yaml
esp32:
  board: esp32-c6-devkitm-1
  flash_size: 4MB
  variant: ESP32C6
  framework:
    type: esp-idf
    version: 5.5.0
    release: "20250510"
    platform_version: 55.03.30-alpha1
```

I have the same issue.
```
ModuleNotFoundError: No module named 'rich'
CMake Error at /config/.esphome/platformio/packages/framework-espidf/tools/cmake/kconfig.cmake:217 (message):
```

Same goes for `release: "ard33a"`

And without setting a release I simply get a 404 even earlier.
```
INFO Installing https://github.com/pioarduino/esp-idf/releases/download/v5.5.0/esp-idf-v5.5.0.zip
PackageException: Got the unrecognized status code '404' when downloaded https://github.com/pioarduino/esp-idf/releases/download/v5.5.0/esp-idf-v5.5.0.zip
```

I haven't tried 5.4.1 because that breaks my I2C devices.

**Comment by swoboda1337** [comment]
> @swoboda1337 Thanks for looking into the 'rich issue'. I only posted it here as an FYI to others that want to try out your PR 🙂. I don't want to get too much off-topic, but the other platform version doesn't work for me either 😐 .

This will work although you might have to clean your platformio folder:
```
    type: esp-idf
    version: 5.5.0
    release: "20250510"
    platform_version: "https://github.com/pioarduino/platform-espressif32.git#develop"
```
They fixed it this morning: https://github.com/pioarduino/platform-espressif32/commit/17b022cfc82c89b234ba92617fa7fafc267a3273

**Comment by alex3305** [comment]
@swoboda1337 Just wondering if building with this PR is still working for you?

After having some free time I tried it yesterday with the latest ESPHome release, but I couldn't get it to compile on 5.5.0. I only gotsome nonsense error about main.cpp on line 0. I'm currently back at 5.3.2 with the old driver which worked without any hassle.

**Comment by swoboda1337** [comment]
I merged dev and tested with this, works fine: 
```
esp32:
  board: esp32-c6-devkitc-1
  framework:
    type: esp-idf
    version: 5.4.2
    platform_version: 54.03.21
```

**Comment by kbx81** [comment]
Tested & working on my Adafruit Funhouse (ESP32-S2) board! 🎉
Seems to solve whatever the long-standing issue was with the old driver, I think related to this: https://github.com/esphome/issues/issues/6718 ...where I2C was totally unusable on this board.
Thanks @swoboda1337 🍻

File: esphome/components/i2c/i2c_bus_esp_idf.cpp [hunk 1]
```diff
@@ -20,20 +21,71 @@ static const char *const TAG = "i2c.idf";
...
-  next_port = (next_port == I2C_NUM_0) ? I2C_NUM_1 : I2C_NUM_MAX;
+  this->port_ = next_port;
+  if (this->port_ == I2C_NUM_MAX) {
+    ESP_LOGE(TAG, "No more than %u buses supported", I2C_NUM_MAX);
+    this->mark_failed();
+    return;
+  }
+
+  if (this->timeout_ > 13000) {
+    ESP_LOGW(TAG, "i2c timeout of %" PRIu32 "us greater than max of 13ms on esp-idf, setting to max", this->timeout_);
```
Comment (kbx81) [inline esphome/components/i2c/i2c_bus_esp_idf.cpp]: Can be a bit shorter & save a few bytes. 🙂 (`TAG` already tells us it's the IDF I2C code 😉)
```suggestion
    ESP_LOGW(TAG, "Using max allowed timeout: 13 ms");
```
Is this milliseconds or microseconds? I see both `us` and `ms` in the original message. I'm assuming microseconds is correct because 13000.

...also...what a seemingly arbitrary value. 😅

File: esphome/components/i2c/i2c_bus_esp_idf.cpp [hunk 2]
```diff
@@ -20,20 +21,71 @@ static const char *const TAG = "i2c.idf";
...
+    ESP_LOGW(TAG, "i2c_master_bus_add_device failed: %s", esp_err_to_name(err));
     this->mark_failed();
     return;
   }
 
-  recover_();
+  this->initialized_ = true;
+
+  if (this->scan_) {
+    ESP_LOGV(TAG, "Scanning i2c bus for active devices...");
```
Comment (kbx81) [inline esphome/components/i2c/i2c_bus_esp_idf.cpp]: Shorter & let `TAG` do its job. 🙂
```suggestion
    ESP_LOGV(TAG, "Scanning for devices");
```

**Review by kbx81 — COMMENTED** [review]
Couple nitpicks, otherwise LGTM 😄

File: esphome/components/i2c/i2c_bus_esp_idf.cpp [hunk 3]
```diff
@@ -123,6 +174,64 @@ ErrorCode IDFI2CBus::readv(uint8_t address, ReadBuffer *buffers, size_t cnt) {
...
+  jobs[num].command = I2C_MASTER_CMD_WRITE;
+  jobs[num].write.ack_check = true;
+  jobs[num].write.data = &read;
+  jobs[num].write.total_bytes = 1;
+  num++;
+
+  for (size_t i = 0; i < cnt; i++) {
+    const auto &buf = buffers[i];
+    if (buf.len == 0)
+      continue;
```
Comment (swoboda1337) [inline esphome/components/i2c/i2c_bus_esp_idf.cpp:195]: Also realize I should probably fix this. If the last buf has a len of zero the following code to ensure the last entity has a len of 1 doesn't work. Very annoying the user can pass in len == 0.

**Review by kbx81 — APPROVED** [review]
Thanks @swoboda1337 👍🏻
