### PR TITLE
[scheduler] Fix LibreTiny compilation error due to missing atomic operations

### PR DESCRIPTION
**Pull request by bdraco**
# What does this implement/fix?

This PR fixes a compilation error on LibreTiny platforms (BK72xx, RTL87xx) that was introduced in #9624. The error occurs because LibreTiny's toolchain doesn't support atomic operations (`__atomic_compare_exchange_4`), which are now used in the scheduler's rollover detection code.

The fix implements a platform-specific solution for LibreTiny that:
- Uses regular non-atomic operations for normal time updates
- Only takes locks when near the 32-bit rollover boundary (±10 seconds every 49.7 days)
- Maintains thread safety for the critical rollover detection while minimizing performance impact

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- Regression from #9624

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- Not applicable (internal implementation detail)

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [x] BK72xx
- [ ] RTL87xx
- [ ] nRF52840

## Example entry for `config.yaml`:

```yaml
# No configuration changes needed - this is an internal fix
esphome:
  name: test-device
  
bk72xx:
  board: generic-bk7231n-qfn32-tuya
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

## Additional Notes

The implementation accepts minor time inconsistencies (microseconds) during normal operation, which is acceptable because:
1. The scheduler operates at millisecond resolution
2. The critical rollover detection (every 49.7 days) is fully protected
3. Any backwards time movement is negligible compared to typical scheduler delays

A TODO comment has been added to remove this special handling once LibreTiny adds atomic support.

### CODE REVIEW

**Comment by bdraco** [comment]
links ok now with `./script/test_build_components -t bk72xx-ard -c homeassistant `

**Comment by bdraco** [comment]
reflashing a real device before marking it ready

**Comment by bdraco** [comment]
[14:53:11][C][lt.component:013]: LibreTiny:
[14:53:11][C][lt.component:013]:   Version: v1.9.1 on generic-bk7231n-qfn32-tuya, compiled at Jul 17 2025 14:45:14, GCC 10.3.1 (-O1)
[14:53:11][C][lt.component:013]:   Loglevel: 3


👍

File: esphome/core/scheduler.cpp [hunk 1]
```diff
@@ -507,8 +507,49 @@ uint64_t Scheduler::millis_64_(uint32_t now) {
...
+#ifdef USE_LIBRETINY
+  // LibreTiny: Multi-threaded but lacks atomic operation support
+  // TODO: If LibreTiny ever adds atomic support, remove this entire block and
+  // let it fall through to the atomic-based implementation below
+  // We need to use a lock when near the rollover boundary to prevent races
+  uint32_t last = this->last_millis_;
+
+  // Define a safe window around the rollover point (10 seconds)
+  // This covers any reasonable scheduler delays or thread preemption
+  static const uint32_t ROLLOVER_WINDOW = 10000;  // 10 seconds in milliseconds
```
[the remark this answers is not in the document]
Comment (bdraco) [reply esphome/core/scheduler.cpp:520]: I don't think that makes sense since its implementation specific

File: esphome/core/scheduler.cpp [hunk 2]
```diff
@@ -507,8 +507,49 @@ uint64_t Scheduler::millis_64_(uint32_t now) {
...
+
+  // Check if we're near the rollover boundary (close to 0xFFFFFFFF or just past 0)
+  bool near_rollover = (last > (0xFFFFFFFF - ROLLOVER_WINDOW)) || (now < ROLLOVER_WINDOW);
```
[the remark this answers is not in the document]
Comment (bdraco) [reply esphome/core/scheduler.cpp]: b2b05c99c

**Review by jesserockz — APPROVED** [review]
