### ISSUE TITLE
Compilation error in 2025.7.0b5

### ISSUE THREAD

**Issue by Plawasan** [OttoWinter/esphomeyaml#9539]
### The problem

I tried to compile the yaml for one of my devices with the new sub-config setup and ran into an complier issue (same code complies ok on 2025.6.0) - all relevant info below.

From what I can tell this line alone is enough to cause the error (when I comment it out, it compiles ok)

```
- homeassistant.tag_scanned: !lambda 'return x.c_str();'
```

I'm fully aware I might be using x vs x.c_str() incorrectly however the same exact code compiles OK on 2025.6.0 .. did something change?

### Which version of ESPHome has the issue?

2025.7.0b5

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### YAML Config

```yaml
substitutions:
  devicename: ESP Front Door Keypad
  esp_name: ESP Front Door Keypad #Device Name
  esp_hostname: esp-front-door-keypad
  ip_address: 192.168.5.115
  ip_gw: 192.168.5.1
  ip_netmask: 255.255.255.0

esphome:
  name: ${esp_hostname}

  areas:
    - id: entry_area
      name: "Entry"

  devices:
      - id: front_door_keypad
        name: "Front Door Keypad"
        area_id: entry_area

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: ${ip_address}
    gateway: ${ip_gw}
    subnet: ${ip_netmask}
  ap:
    ssid: "${esp_name} Hotspot"
    password: !secret ap_password

ota:
  platform: esphome
  password: !secret ota_password

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

captive_portal:

web_server:
  port: 80
  include_internal: true  

wiegand:
  - id: mykeypad
    d0: GPIO34
    d1: GPIO35
    on_key:
      - lambda: ESP_LOGI("KEY", "received key %d", x);
      - if:
          condition:
              lambda: |-
                return (x == 11);
          then:
            - homeassistant.event:
                event: esphome.doorbell_clicked

    on_tag:
      - lambda: ESP_LOGI("TAG", "received tag %s", x.c_str());
      - text_sensor.template.publish:
          id: last_tag
          state: !lambda 'return x.c_str();'
      - homeassistant.tag_scanned: !lambda 'return x.c_str();'      

key_collector:
  - id: pincode_reader
    source_id: mykeypad
    min_length: 4
    max_length: 4
    end_key_required: false
    clear_keys: "*"
    allowed_keys: "0123456789"
    timeout: 3s
    on_result:
      - logger.log:
          format: "input result: '%s', started by '%c', ended by '%c'"
          args: [ 'x.c_str()', "(start == 0 ? '~' : start)", "(end == 0 ? '~' : end)" ]
      - text_sensor.template.publish:
          id: last_pin
          state: !lambda 'return x;'
      - homeassistant.tag_scanned: !lambda 'return x;'
    on_timeout:
      - logger.log:
          format: "input timeout: '%s', started by '%c'"
          args: [ 'x.c_str()', "(start == 0 ? '~' : start)" ]

text_sensor:
  - platform: template
    device_id: front_door_keypad
    id: last_tag
    name: "${esp_name} Last Tag"
    icon: mdi:tag 

  - platform: template
    device_id: front_door_keypad
    id: last_pin
    name: "${esp_name} Last PIN"
    icon: mdi:dialpad 


button:
  - platform: restart
    name: "${esp_name} Restart"
```

### Anything in the logs that might be useful for us?

```txt

```

### Additional information

```
INFO ESPHome 2025.7.0b5
INFO Reading configuration /config/esphome/esp-entry-keypad.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing esp-front-door-keypad (board: esp32dev; framework: arduino; platform: https://github.com/pioarduino/platform-espressif32/releases/download/53.03.13/platform-espressif32.zip)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - framework-arduinoespressif32 @ 3.1.3 
 - framework-arduinoespressif32-libs @ 5.3.0+sha.489d7a2b3a 
 - tool-esptoolpy @ 4.8.6 
 - tool-mklittlefs @ 3.2.0 
 - tool-riscv32-esp-elf-gdb @ 14.2.0+20240403 
 - tool-xtensa-esp-elf-gdb @ 14.2.0+20240403 
 - toolchain-xtensa-esp-elf @ 13.2.0+20240530
Dependency Graph
|-- Networking @ 3.1.3
|-- AsyncTCP @ 3.4.5
|-- WiFi @ 3.1.3
|-- FS @ 3.1.3
|-- Update @ 3.1.3
|-- ESPAsyncWebServer @ 3.7.10
|-- ESP32 Async UDP @ 3.1.3
|-- DNSServer @ 3.1.3
|-- ESPmDNS @ 3.1.3
|-- noise-c @ 0.1.10
|-- ArduinoJson @ 7.4.2
Compiling .pioenvs/esp-front-door-keypad/src/main.cpp.o
In file included from src/esphome.h:10,
                 from src/main.cpp:3:
src/esphome/components/api/homeassistant_service.h: In instantiation of 'esphome::api::TemplatableStringValue<X>::TemplatableStringValue(F) [with F = setup()::<lambda(std::string)>; typename std::enable_if<std::is_invocable<F, X ...>::value, int>::type <anonymous> = 0; X = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >}]':
src/esphome/components/api/homeassistant_service.h:27:97:   required from 'esphome::api::TemplatableKeyValuePair<Ts>::TemplatableKeyValuePair(std::string, T) [with T = setup()::<lambda(std::string)>; Ts = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >}; std::string = std::__cxx11::basic_string<char>]'
src/esphome/components/api/homeassistant_service.h:39:27:   required from 'void esphome::api::HomeAssistantServiceCallAction<Ts>::add_data(std::string, T) [with T = setup()::<lambda(std::string)>; Ts = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >}; std::string = std::__cxx11::basic_string<char>]'
/config/esphome/esp-entry-keypad.yaml:78:52:   required from here
src/esphome/components/api/homeassistant_service.h:22:90: error: no matching function for call to 'to_string(std::string)'
   22 |       : TemplatableValue<std::string, X...>([f](X... x) -> std::string { return to_string(f(x...)); }) {}
      |                                                                                 ~~~~~~~~~^~~~~~~~~
In file included from /data/cache/platformio/packages/toolchain-xtensa-esp-elf/xtensa-esp-elf/include/c++/13.2.0/string:54,
                 from /data/cache/platformio/packages/toolchain-xtensa-esp-elf/xtensa-esp-elf/include/c++/13.2.0/bits/locale_classes.h:40,
                 from /data/cache/platformio/packages/toolchain-xtensa-esp-elf/xtensa-esp-elf/include/c++/13.2.0/bits/ios_base.h:41,
                 from /data/cache/platformio/packages/toolchain-xtensa-esp-elf/xtensa-esp-elf/include/c++/13.2.0/ios:44,
                 from /data/cache/platformio/packages/toolchain-xtensa-esp-elf/xtensa-esp-elf/include/c++/13.2.0/ostream:40,
                 from /data/cache/platformio/packages/toolchain-xtensa-esp-elf/xtensa-esp-elf/include/c++/13.2.0/bits/unique_ptr.h:42,
                 from /data/cache/platformio/packages/toolchain-xtensa-esp-elf/xtensa-esp-elf/include/c++/13.2.0/memory:78,
                 from src/esphome/components/socket/socket.h:2,
                 from src/esphome/components/api/api_frame_helper.h:16,
                 from src/esphome/components/api/api_connection.h:5,
                 from src/esphome.h:3:
/data/cache/platformio/packages/toolchain-xtensa-esp-elf/xtensa-esp-elf/include/c++/13.2.0/bits/basic_string.h:4249:3: note: candidate: 'std::string std::__cxx11::to_string(long double)'
 4249 |   to_string(long double __val)
      |   ^~~~~~~~~
/data/cache/platformio/packages/toolchain-xtensa-esp-elf/xtensa-esp-elf/include/c++/13.2.0/bits/basic_string.h:4249:25: note:   no known conversion for argument 1 from 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'long double'
 4249 |   to_string(long double __val)
      |             ~~~~~~~~~~~~^~~~~
/data/cache/platformio/packages/toolchain-xtensa-esp-elf/xtensa-esp-elf/include/c++/13.2.0/bits/basic_string.h:4239:3: note: candidate: 'std::string std::__cxx11::to_string(double)'
 4239 |   to_string(double __val)
      |   ^~~~~~~~~
/data/cache/platformio/packages/toolchain-xtensa-esp-elf/xtensa-esp-elf/include/c++/13.2.0/bits/basic_string.h:4239:20: note:   no known conversion for argument 1 from 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'double'
 4239 |   to_string(double __val)
      |             ~~~~~~~^~~~~
/data/cache/platformio/packages/toolchain-xtensa-esp-elf/xtensa-esp-elf/include/c++/13.2.0/bits/basic_string.h:4229:3: note: candidate: 'std::string std::__cxx11::to_string(float)'
 4229 |   to_string(float __val)
      |   ^~~~~~~~~
/data/cache/platformio/packages/toolchain-xtensa-esp-elf/xtensa-esp-elf/include/c++/13.2.0/bits/basic_string.h:4229:19: note:   no known conversion for argument 1 from 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'float'
 4229 |   to_string(float __val)
      |             ~~~~~~^~~~~
/data/cache/platformio/packages/toolchain-xtensa-esp-elf/xtensa-esp-elf/include/c++/13.2.0/bits/basic_string.h:4217:3: note: candidate: 'std::string std::__cxx11::to_string(long long unsigned int)'
 4217 |   to_string(unsigned long long __val)
      |   ^~~~~~~~~
/data/cache/platformio/packages/toolchain-xtensa-esp-elf/xtensa-esp-elf/include/c++/13.2.0/bits/basic_string.h:4217:32: note:   no known conversion for argument 1 from 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'long long unsigned int'
 4217 |   to_string(unsigned long long __val)
      |             ~~~~~~~~~~~~~~~~~~~^~~~~
/data/cache/platformio/packages/toolchain-xtensa-esp-elf/xtensa-esp-elf/include/c++/13.2.0/bits/basic_string.h:4204:3: note: candidate: 'std::string std::__cxx11::to_string(long long int)'
 4204 |   to_string(long long __val)
      |   ^~~~~~~~~
/data/cache/platformio/packages/toolchain-xtensa-esp-elf/xtensa-esp-elf/include/c++/13.2.0/bits/basic_string.h:4204:23: note:   no known conversion for argument 1 from 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'long long int'
 4204 |   to_string(long long __val)
      |             ~~~~~~~~~~^~~~~
/data/cache/platformio/packages/toolchain-xtensa-esp-elf/xtensa-esp-elf/include/c++/13.2.0/bits/basic_string.h:4192:3: note: candidate: 'std::string std::__cxx11::to_string(long unsigned int)'
 4192 |   to_string(unsigned long __val)
      |   ^~~~~~~~~
/data/cache/platformio/packages/toolchain-xtensa-esp-elf/xtensa-esp-elf/include/c++/13.2.0/bits/basic_string.h:4192:27: note:   no known conversion for argument 1 from 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'long unsigned int'
 4192 |   to_string(unsigned long __val)
      |             ~~~~~~~~~~~~~~^~~~~
/data/cache/platformio/packages/toolchain-xtensa-esp-elf/xtensa-esp-elf/include/c++/13.2.0/bits/basic_string.h:4177:3: note: candidate: 'std::string std::__cxx11::to_string(long int)'
 4177 |   to_string(long __val)
      |   ^~~~~~~~~
/data/cache/platformio/packages/toolchain-xtensa-esp-elf/xtensa-esp-elf/include/c++/13.2.0/bits/basic_string.h:4177:18: note:   no known conversion for argument 1 from 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'long int'
 4177 |   to_string(long __val)
      |             ~~~~~^~~~~
/data/cache/platformio/packages/toolchain-xtensa-esp-elf/xtensa-esp-elf/include/c++/13.2.0/bits/basic_string.h:4165:3: note: candidate: 'std::string std::__cxx11::to_string(unsigned int)'
 4165 |   to_string(unsigned __val)
      |   ^~~~~~~~~
/data/cache/platformio/packages/toolchain-xtensa-esp-elf/xtensa-esp-elf/include/c++/13.2.0/bits/basic_string.h:4165:22: note:   no known conversion for argument 1 from 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'unsigned int'
 4165 |   to_string(unsigned __val)
      |             ~~~~~~~~~^~~~~
/data/cache/platformio/packages/toolchain-xtensa-esp-elf/xtensa-esp-elf/include/c++/13.2.0/bits/basic_string.h:4150:3: note: candidate: 'std::string std::__cxx11::to_string(int)'
 4150 |   to_string(int __val)
      |   ^~~~~~~~~
/data/cache/platformio/packages/toolchain-xtensa-esp-elf/xtensa-esp-elf/include/c++/13.2.0/bits/basic_string.h:4150:17: note:   no known conversion for argument 1 from 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'int'
 4150 |   to_string(int __val)
      |             ~~~~^~~~~
*** [.pioenvs/esp-front-door-keypad/src/main.cpp.o] Error 1
========================== [FAILED] Took 9.40 seconds ==========================
```

**Comment by bdraco** [comment]
esphome/components/api/homeassistant_service.h unconditionally calls to_string() on lambda return values

~~This likely broke with c74e5e0f0~~

**Comment by bdraco** [comment]
actually its caused by 30f61b26ff150e97b29adead8dae13e04d165510 removing the overload https://github.com/esphome/esphome/commit/30f61b26ff150e97b29adead8dae13e04d165510#diff-c9434bebeff9b540a10362d005937b7cadff3fb5ef6c89be6f68e0f771fab290L280
