### PR TITLE
[api] Eliminate heap allocation in ``process_batch_`` using stack-allocated PacketInfo array

### PR DESCRIPTION
**Pull request by bdraco**
# What does this implement/fix?

This PR optimizes the API connection's `process_batch_` method by eliminating heap allocations for the `PacketInfo` vector. Instead of dynamically allocating memory for each batch, it now uses a stack-allocated array with platform-specific size limits.

**Performance improvements:**
- Eliminates heap allocation overhead for PacketInfo array
- Saves ~200-1000 CPU cycles per batch from malloc/free operations
- Reduces memory fragmentation
- Provides deterministic memory usage
- No allocation failures possible

**Resource usage:**
- **Flash**: Reduced by 380 bytes (removing vector operations)
- **RAM**: No change (stack allocation is temporary)
- ESP32/HOST: 512 bytes stack (64 packets max)
- ESP8266/RP2040/LibreTiny: 256 bytes stack (32 packets max)

Based on real-world analysis, typical batches contain 2-26 items, well within both limits.

**Additional changes:**
- Increased `MAX_INITIAL_PER_BATCH` from 20 to 24 to take advantage of smaller entity info messages after the removal of the unique_id field
- Added `static_assert` to ensure `PacketInfo` remains trivially destructible

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):** N/A

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** N/A

fixes https://github.com/home-assistant/core/issues/145293

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx
- [ ] nRF52840

## Example entry for `config.yaml`:

```yaml
# No configuration changes needed - this is an internal optimization
api:
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by bdraco** [comment]
| Batch Size | Heap (ns/iter) | Stack (ns/iter) | Speedup | Heap Allocations |
  |------------|----------------|-----------------|---------|------------------|
  | 2 items    | 22 ns          | 2 ns            | 11x     | 100,000          |
  | 5 items    | 31 ns          | 5 ns            | 6.2x    | 100,000          |
  | 10 items   | 41 ns          | 10 ns           | 4.1x    | 100,000          |
  | 20 items   | 50 ns          | 29 ns           | 1.7x    | 100,000          |
  | 26 items   | 65 ns          | 38 ns           | 1.7x    | 100,000          |
  | 32 items   | 71 ns          | 49 ns           | 1.5x    | 100,000          |

File: esphome/components/api/api_connection.h [hunk 1]
```diff
@@ -19,7 +19,15 @@ namespace api {
 // Keepalive timeout in milliseconds
 static constexpr uint32_t KEEPALIVE_TIMEOUT_MS = 60000;
 // Maximum number of entities to process in a single batch during initial state/info sending
-static constexpr size_t MAX_INITIAL_PER_BATCH = 20;
+static constexpr size_t MAX_INITIAL_PER_BATCH = 24;
```
Comment (bdraco) [inline esphome/components/api/api_connection.h:24]: bump this up a bit higher now that we removed unique ids which were huge chunk of the batch

File: esphome/components/api/api_connection.cpp [hunk 2]
```diff
@@ -1708,9 +1708,12 @@ void APIConnection::process_batch_() {
     return;
   }
 
-  // Pre-allocate storage for packet info
-  std::vector<PacketInfo> packet_info;
-  packet_info.reserve(num_items);
+  size_t packets_to_process = std::min(num_items, MAX_PACKETS_PER_BATCH);
+
+  // Stack-allocated array for packet info
+  alignas(PacketInfo) char packet_info_storage[MAX_PACKETS_PER_BATCH * sizeof(PacketInfo)];
```
[the remark this answers is not in the document]
Comment (bdraco) [reply esphome/components/api/api_connection.cpp:1718]: std::aligned_storage was deprecated in C++23 and will be removed in C++26
https://en.cppreference.com/w/cpp/types/aligned_storage.html

File: esphome/components/api/api_connection.cpp [hunk 3]
```diff
@@ -1757,7 +1760,9 @@ void APIConnection::process_batch_() {
     // Message was encoded successfully
     // payload_size is header_padding + actual payload size + footer_size
     uint16_t proto_payload_size = payload_size - header_padding - footer_size;
-    packet_info.emplace_back(item.message_type, current_offset, proto_payload_size);
+    // Use placement new to construct PacketInfo in pre-allocated stack array
+    // This avoids default-constructing all MAX_PACKETS_PER_BATCH elements
+    new (&packet_info[packet_count++]) PacketInfo(item.message_type, current_offset, proto_payload_size);
```
[the remark this answers is not in the document]
Comment (bdraco) [reply esphome/components/api/api_connection.cpp:1771]: PacketInfo contains only trivial types

File: esphome/components/api/api_connection.h [hunk 4]
```diff
@@ -19,7 +19,15 @@ namespace api {
 // Keepalive timeout in milliseconds
 static constexpr uint32_t KEEPALIVE_TIMEOUT_MS = 60000;
 // Maximum number of entities to process in a single batch during initial state/info sending
```
[the remark this answers is not in the document]
Comment (bdraco) [reply esphome/components/api/api_connection.h:21]: Yeah -- should explain that

[the remark this answers is not in the document]
Comment (bdraco) [reply esphome/components/api/api_connection.h:21]: 8223db761

File: esphome/components/api/api_connection.cpp (hunk 3 above)
[the remark this answers is not in the document]
Comment (bdraco) [reply esphome/components/api/api_connection.cpp:1771]: We could add
```
static_assert(std::is_trivially_destructible<PacketInfo>::value,
              "PacketInfo must remain trivially destructible with this placement-new approach");
```

File: esphome/components/api/api_connection.cpp [hunk 5]
```diff
@@ -1783,8 +1792,8 @@ void APIConnection::process_batch_() {
   }
 
   // Send all collected packets
```
[the remark this answers is not in the document]
Comment (bdraco) [reply esphome/components/api/api_connection.cpp:1796]: That's impossible and also if we log there we would overwrite the protobuf buffer

File: esphome/components/api/api_connection.cpp [hunk 6]
```diff
@@ -1708,9 +1712,12 @@ void APIConnection::process_batch_() {
...
   }
 
-  // Pre-allocate storage for packet info
-  std::vector<PacketInfo> packet_info;
-  packet_info.reserve(num_items);
+  size_t packets_to_process = std::min(num_items, MAX_PACKETS_PER_BATCH);
+
+  // Stack-allocated array for packet info
+  alignas(PacketInfo) char packet_info_storage[MAX_PACKETS_PER_BATCH * sizeof(PacketInfo)];
+  PacketInfo *packet_info = reinterpret_cast<PacketInfo *>(packet_info_storage);
```
[the remark this answers is not in the document]
Comment (bdraco) [reply esphome/components/api/api_connection.cpp:1719]: This doesn't work because we need placement new to avoid default construction.

**Comment by SeByDocKy** [comment]
I tried to compile with this PR & idf 5.5.0. Got compilation error
```Compiling .pioenvs\pvbrain2\src\main.cpp.o
src/esphome/core/component_iterator.cpp: In member function 'void esphome::ComponentIterator::advance()':
src/esphome/core/component_iterator.cpp:153:48: error: 'class esphome::api::APIServer' has no member named 'get_user_service '
  153 |       if (this->at_ >= api::global_api_server->get_user_services().size()) {
      |                                                ^~~~~~~~~~~~~~~~~
src/esphome/core/component_iterator.cpp:156:49: error: 'class esphome::api::APIServer' has no member named 'get_user_service '
  156 |         auto *service = api::global_api_server->get_user_services()[this->at_];```

**Comment by bdraco** [comment]
> I tried to compile with this PR & idf 5.5.0. Got compilation error
> 
> ```
> src/esphome/core/component_iterator.cpp: In member function 'void esphome::ComponentIterator::advance()':
> src/esphome/core/component_iterator.cpp:153:48: error: 'class esphome::api::APIServer' has no member named 'get_user_service '
>   153 |       if (this->at_ >= api::global_api_server->get_user_services().size()) {
>       |                                                ^~~~~~~~~~~~~~~~~
> src/esphome/core/component_iterator.cpp:156:49: error: 'class esphome::api::APIServer' has no member named 'get_user_service '
>   156 |         auto *service = api::global_api_server->get_user_services()[this->at_];```
> ```

You can't use the api version from this PR without using dev

**Comment by SeByDocKy** [comment]
> > I tried to compile with this PR & idf 5.5.0. Got compilation error
> > ```
> > src/esphome/core/component_iterator.cpp: In member function 'void esphome::ComponentIterator::advance()':
> > src/esphome/core/component_iterator.cpp:153:48: error: 'class esphome::api::APIServer' has no member named 'get_user_service '
> >   153 |       if (this->at_ >= api::global_api_server->get_user_services().size()) {
> >       |                                                ^~~~~~~~~~~~~~~~~
> > src/esphome/core/component_iterator.cpp:156:49: error: 'class esphome::api::APIServer' has no member named 'get_user_service '
> >   156 |         auto *service = api::global_api_server->get_user_services()[this->at_];```
> > ```
> 
> You can't use the api version from this PR without using dev

I am on the last dev

**Comment by bdraco** [comment]
That compile error is unrelated to this change

**Comment by SeByDocKy** [comment]
> That compile error is unrelated to this change

Can't tell you... but without this PR, it's compiling. With no more... I will try with 5.4.2... Thx anyway

**Review by jesserockz — APPROVED** [review]
