### PR TITLE
[core] Fix compilation errors when platform sections have no entities

### PR DESCRIPTION
**Pull request by bdraco**
# What does this implement/fix?

This fixes a compilation error introduced in #10018 where empty platform sections (e.g., `text:`, `binary_sensor:`) in YAML configurations would cause build failures due to missing `ESPHOME_ENTITY_*_COUNT` defines.

**More importantly**, this PR also fixes a significant code bloat issue: Previously, if a component loaded a platform (like `binary_sensor:`) but created no entities, ESPHome would still compile all the binary sensor code into the firmware. This resulted in unnecessary flash usage and memory overhead from dead code that could never be used.

The issue occurred because:
1. Empty platform sections still load their components, which previously added `USE_*` defines unconditionally
2. These `USE_*` defines caused all platform-specific code to be compiled, even with zero entities
3. After #10018, this also caused compilation errors due to missing `ESPHOME_ENTITY_*_COUNT` defines

This PR moves the responsibility of adding `USE_*` defines from individual platform components to the core config system, ensuring they are only defined when actual entities exist. This means:
- No compilation errors from missing count defines
- No dead code compiled for platforms with zero entities
- Reduced flash usage and memory footprint

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- Fixes compilation errors when using empty platform sections after #10018

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- N/A (no documentation changes needed)

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx
- [ ] nRF52840

## Example entry for `config.yaml`:

```yaml
# This configuration would previously fail to compile after #10018
esphome:
  name: test-device

esp32:
  board: esp32dev

# Empty platform sections - no actual entities defined
binary_sensor:
switch:
text:
sensor:

# Platform with actual entities
datetime:
  - platform: template
    id: my_date
    type: date
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by kbx81 — APPROVED** [review]
Thanks!

**Comment by bdraco** [comment]
Thanks
