### PR TITLE
Bump aioesphomeapi to 17.0.1

### LINKED ISSUE #4936: After upgrading to 2023.9.1 it's not possible to view the logs remote over wifi
### The problem

After upgrading to latest version of ESPHome it can't connect to any logs on any of my devices over wifi.

If I rebuild a device and flash it OTA it will flash and then boot and send the logs to ESPHome. But after disconnecting it is not possible to reconnect instead I get the following log:

```
INFO ESPHome 2023.9.1
INFO Reading configuration /config/esphome/heatpump.yaml...
INFO Starting log output from heatpump.local using esphome API
WARNING Can't connect to ESPHome API for heatpump.local: Unexpected error while connecting to heatpump.local: 'AsyncServiceInfo' object has no attribute 'addresses_by_version' (APIConnectionError)
INFO Trying to connect to heatpump.local in the background
```

Not sure if it related but in my network there is a IPv6 enabled but I haven't configured anything on the ESPHome devices to use IPv6 and disable IPv6 on HA don't change anything.

I got the problem before flashing the new firmware to the board.

### Which version of ESPHome has the issue?

2023.9.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.9.3

### What platform are you using?

ESP32

### Board

ESP32-WROOM-32

### Component causing the issue

_No response_

### Example YAML snippet

```yaml
esphome:
  name: "heatpump"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "xxxxxxxx"

ota:
  password: "xxxxxxxx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Heatpump Fallback Hotspot"
    password: "xxxxxxxx"

captive_portal:

dallas:
  - pin: 32
    update_interval: 10s

sensor:
  - platform: dallas
    address: 0x79xxxxxx
    name: "temp1"
  - platform: dallas
    address: 0x79xxxxxx
    name: "temp2"
  - platform: dallas
    address: 0x79xxxxxx
    name: "temp3"
  - platform: dallas
    address: 0x79xxxxxx
    name: "temp4"
  - platform: wifi_signal
    name: "Wi-Fi Signal"
    update_interval: 60s

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
    ssid:
      name: "Wi-Fi SSID"
    bssid:
      name: "Wi-Fi BSSID"
  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true


esp32_ble_tracker:
bluetooth_proxy:
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2023.9.1
INFO Reading configuration /config/esphome/heatpump.yaml...
INFO Starting log output from heatpump.local using esphome API
WARNING Can't connect to ESPHome API for heatpump.local: Unexpected error while connecting to heatpump.local: 'AsyncServiceInfo' object has no attribute 'addresses_by_version' (APIConnectionError)
INFO Trying to connect to heatpump.local in the background
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by bdraco**
# What does this implement/fix?

fixes https://github.com/home-assistant/core/issues/101039
Fixes https://github.com/esphome/issues/issues/4936

An alternative fix would also be to bump zeroconf to 0.115.1

bug fixes for zeroconf resolution

changelog: https://github.com/esphome/aioesphomeapi/compare/v17.0.0...v17.0.1

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by jesserockz** [comment]
The `cryptography` package is holding this back, but it also has a native apt package that is installed and I have not been able to test it successfully on the different architectures.

#5450

**Comment by bdraco** [comment]
Should we bump zeroconf to 0.115.1 and backport instead to fix the linked issue?

**Comment by jesserockz** [comment]
Yeah if that will fix it, I can push that bump out #5470

**Comment by bdraco** [comment]
> Yeah if that will fix it, I can push that bump out #5470

Yes it will.  I fixed it the problem in zeroconf and I also updated aioesphomeapi to use the newer api that does not have the problem so either bump will solve it

**Comment by bdraco** [comment]
replaced by #5557
