### ISSUE TITLE
Syslog2.0 component is not working on 2025.7.2

### ISSUE THREAD

**Issue by alting** [OttoWinter/esphomeyaml#9713]
### Which version of ESPHome has the issue?

2025.7.2

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Component causing the issue

Syslog2.0

### YAML Config

```yaml

```

### Anything in the logs that might be useful for us?

```txt
src/esphome/components/syslog/syslog_component.cpp: In member function 'virtual void esphome::syslog::SyslogComponent::setup()':
src/esphome/components/syslog/syslog_component.cpp:44:10: error: cannot convert 'esphome::syslog::SyslogComponent::setup()::<lambda(int, const char*, const char*)>' to 'std::function<void(unsigned char, const char*, const char*, unsigned int)>&&'
   44 |         });
      |          ^
In file included from src/esphome/components/syslog/syslog_component.cpp:7:
src/esphome/components/logger/logger.h:146:95: note:   initializing argument 1 of 'void esphome::logger::Logger::add_on_log_callback(std::function<void(unsigned char, const char*, const char*, unsigned int)>&&)'
  146 |   void add_on_log_callback(std::function<void(uint8_t, const char *, const char *, size_t)> &&callback);
      |                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
*** [.pioenvs/sonoff_mini_light_bathroom/src/esphome/components/syslog/syslog_component.cpp.o] Error 1
========================= [FAILED] Took 85.62 seconds =========================
```

**Comment by jesserockz** [comment]
Please provide your entire config. Are you using external components?

In future, there is a box in the form for logs, please fill out the issue form entirely and properly to make diagnosing the issue easier and cause less back and forward requesting more information.

**Comment by andrewjswan** [comment]
This is an external component:
https://github.com/TheStaticTurtle/esphome_syslog/tree/main/components/syslog 
The Issue must be opened in its repository, or switch to using the standard component.
https://esphome.io/components/syslog.html
