### PR TITLE
[core] get_log_str: fix false-positive error on null-terminated strings with stricter compilers

### PR DESCRIPTION
**Pull request by diorcety**
# What does this implement/fix?

After the changes introduced in e88c9ba0661131f39d5ee3c9de77a6e48204b4c5, the compiler may incorrectly report an issue with a non–null-terminated string, depending on the compiler and optimization flags:

```
logger.cpp:268:19: error: '%s' directive argument is not a nul-terminated string [-Werror=format-overflow=]
  268 |     ESP_LOGW(TAG, "Cannot set log level higher than pre-compiled %s"
```

This can be reproduced here: https://godbolt.org/z/x8aa9qMEG
The same code compiles correctly without -Os: https://godbolt.org/z/e4qzP4dbj

One possible fix is to use __attribute__((noinline)) (suggested by @bdraco): https://godbolt.org/z/1qzGPG8Tb
Another option is to use a laundering mechanism: https://godbolt.org/z/q5KcfGvvY
The second approach allows the code to remain optimized without triggering the compiler issue.

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) — [policy](https://developers.esphome.io/contributing/code/#what-constitutes-a-c-breaking-change)
- [ ] Developer breaking change (an API change that could break external components) — [policy](https://developers.esphome.io/contributing/code/#what-is-considered-public-c-api)
- [ ] Undocumented C++ API change (removal or change of undocumented public methods that lambda users may depend on) — [policy](https://developers.esphome.io/contributing/code/#c-user-expectations)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

## Test Environment

- [X] ESP32
- [X] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040/RP2350
- [ ] BK72xx
- [ ] RTL87xx
- [ ] LN882x
- [ ] nRF52840

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

File: esphome/core/progmem.h [hunk 1]
```diff
@@ -104,7 +125,7 @@ struct LogString;
     static const char *get_(uint8_t idx, uint8_t fallback) { \
       if (idx >= COUNT) \
         idx = fallback; \
-      return &BLOB[::esphome::progmem_read_byte(&OFFSETS[idx])]; \
+      return LAUNDER_STR(&BLOB[::esphome::progmem_read_byte(&OFFSETS[idx])]); \
```
Comment (bdraco) [inline esphome/core/progmem.h]:
```suggestion
      return std::launder(&BLOB[::esphome::progmem_read_byte(&OFFSETS[idx])]); \
```

File: esphome/core/progmem.h [hunk 2]
```diff
@@ -90,6 +91,26 @@ template<FixedString... Strs> struct ProgmemStringTable {
...
+#define LAUNDER_STR(p) \
+  ([](auto x) { \
+    __asm__("" : "+r"(x)); \
+    return x; \
+  }(p))
+#else
+// Fallback for other compilers/versions
+#define LAUNDER_STR(p) (p)
+#endif
+
```
Comment (bdraco) [inline esphome/core/progmem.h]:
```suggestion
```

All builds are c++20 or later

File: esphome/core/progmem.h [hunk 3]
```diff
@@ -3,6 +3,7 @@
 #include <array>
 #include <cstddef>
 #include <cstdint>
+#include <new>
```
Comment (bdraco) [inline esphome/core/progmem.h:6]:
```suggestion
```

Comment (bdraco) [reply esphome/core/progmem.h:6]: actually its not pulled in so we need to keep

File: esphome/core/progmem.h (hunk 1 above)
Comment (bdraco) [reply esphome/core/progmem.h]: And a comment that we are using it to prevent the inter-procedural analysis that causes the false positive

File: esphome/core/progmem.h [hunk 4]
```diff
@@ -104,7 +105,7 @@ struct LogString;
     static const char *get_(uint8_t idx, uint8_t fallback) { \
       if (idx >= COUNT) \
         idx = fallback; \
-      return &BLOB[::esphome::progmem_read_byte(&OFFSETS[idx])]; \
+      return std::launder(&BLOB[::esphome::progmem_read_byte(&OFFSETS[idx])]); \
```
Comment (bdraco) [inline esphome/core/progmem.h]:
```suggestion
       // std::launder is used here to prevent the inter-procedural analysis that
       // causes the false positive that the string is not null terminated
      return std::launder(&BLOB[::esphome::progmem_read_byte(&OFFSETS[idx])]); \
```

**Review by bdraco — DISMISSED** [review]

**Review by bdraco — APPROVED** [review]

**Comment by bdraco** [comment]
thanks @diorcety
