### ISSUE TITLE
M5Stack CoreS3: SCL held LOW on Port A (GPIO1/GPIO2) after full power cycle with I2C sensor connected

### ISSUE THREAD

**Issue by jbaquien-sketch** [OttoWinter/esphomeyaml#16185]
### Problem description

After a **complete power cycle** (full mains power loss, not USB reset) with an I2C sensor connected to Port A, the CoreS3 boots with SCL held LOW on the external bus, making the sensor permanently unreachable until the sensor is physically disconnected, the device rebooted, and the sensor reconnected.

```
[I][i2c.idf:205]: Performing bus recovery
[E][i2c.idf:242]: Recovery failed: SCL is held LOW on the bus
[E][bme68x_bsec2.sensor:036]: bme68x_init failed: status -2
```

This is a **hardware architectural problem** specific to the CoreS3: Port A power rails (ALDO3/BLDO1/BLDO2) are controlled by the AXP2101 PMU, which itself is on the internal I2C bus (GPIO11/GPIO12). The external bus (GPIO1/GPIO2) has no power until the AXP2101 activates ALDO3. However, ESPHome initializes the I2C bus driver (priority ~1000, hardcoded) **before** any user component can activate the PMU rails.

---

### Root cause analysis

The CoreS3 Port A power-up sequence creates an impossible dependency with ESPHome's initialization order:

1. **ESPHome boot:** `i2c.idf` bus recovery runs at hardcoded priority ~1000
2. **At this point:** ALDO3 (Port A VCC) is not yet active — AXP2101 hasn't run
3. **BME688 state:** Partially powered via GPIO protection diodes (parasitic powering), SCL stuck LOW
4. **AXP2101 setup:** Runs at priority 970 — too late, bus already marked FAILED
5. **BSEC2 setup:** Runs at default priority — finds bus FAILED, marks itself FAILED permanently

The key finding: **`setup_priority` on the I2C bus component is ignored by ESPHome core**, which hardcodes bus initialization at `setup_priority::BUS` (~1000). Setting `setup_priority: 600` in YAML for `bus_a` has no effect.

We confirmed this by adding an `on_boot` at `priority: 1100` with a 9-clock GPIO pulse recovery sequence — the pulses execute before bus recovery, but ALDO3 is still not active, so they have no effect on the sensor.

---

### What we tried (esp-idf framework)

All tests with ESPHome 2026.3.1 + esp-idf:

| Attempt | Result |
|---------|--------|
| `setup_priority: 600` on bus_a | Ignored — bus still initializes at priority ~1000 |
| `on_boot priority: 900` with GPIO reset | Too late — bus already attempted recovery |
| `on_boot priority: 1100` with 9-clock pulse recovery | Executes before bus recovery ✅ but ALDO3 not yet active — no effect |
| Custom `axp2101.cpp` with `disableWatchdog` + ALDO3/BLDO1/BLDO2 + GPIO reset + 200ms delay | AXP2101 setup correct but bus_a recovery happens before AXP2101 setup() runs |
| `scan: false` on bus_a | Prevents scan but recovery still runs and fails |

---

### Working solution found (Arduino framework only)

Using **ESPHome 2025.6.3 + framework Arduino** with the `board_m5cores3` component from [@terpasaurus-midwest's fork](https://github.com/terpasaurus-midwest/esphome-fork/tree/m5cores3/my_components):

```yaml
esphome:
  platformio_options:
    board_build.flash_mode: dio
    board_build.mcu: esp32s3
    board_build.f_cpu: 240000000L
  libraries:
    - m5stack/M5Unified

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  framework:
    type: arduino

external_components:
  - source:
      type: git
      url: https://github.com/terpasaurus-midwest/esphome-fork
      ref: m5cores3
      path: my_components
    components: [board_m5cores3]

board_m5cores3:
  id: m5_board
```

This works because `board_m5cores3` calls `M5.begin()` and `M5.Power.setExtOutput(true)` in a pre-initialization phase that runs before ESPHome's component initialization loop, properly activating Port A power before any I2C communication is attempted.

**Limitation:** This solution only works with ESPHome 2025.6.3 (Arduino 2.0.5). ESPHome 2025.7.0+ upgraded to Arduino 3.1.3 which causes `esp_lcd_panel_io.h` compilation errors with M5GFX/M5Unified. The solution cannot be replicated with any ESPHome version after 2025.6.x.

---

### Proposed fix for esp-idf framework

The cleanest solution would be one of:

1. **Make `setup_priority` configurable for I2C bus components** — allow users to set a value lower than the hardcoded `setup_priority::BUS` so the bus can be delayed until PMU rails are active.

2. **Add a `power_pin` or `enable_pin` option to `i2c`** — similar to how some display components handle power, allow specifying a GPIO or expander pin that must be HIGH before the bus initializes.

3. **Add `on_before_setup` hook** — a phase that runs before component setup() calls, allowing raw GPIO manipulation to prepare hardware.

The `on_boot priority: 1100` approach is the right direction but fails because there is no way to activate the AXP2101 PMU from a lambda at that priority without conflicting with the bus driver that ESPHome will install moments later.

### Which version of ESPHome has the issue?

2026.3.1 (esp-idf) / 2025.6.3 (Arduino)

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Component causing the issue

Board: M5Stack CoreS3 (ESP32-S3, 16MB flash, 8MB PSRAM) Sensor: BME688 via M5Stack ENV Pro unit, Port A (SDA=GPIO2, SCL=GPIO1, address 0x77) Component: `bme68x_bsec2_i2c`

### YAML Config

```yaml
esphome:
  name: sensor-resina-2
  friendly_name: "Sensor Resina 2"
  on_boot:
    priority: 1100.0
    then:
      - lambda: |-
          // 9-clock pulse recovery on Port A before i2c.idf takes control
          gpio_config_t io_conf = {};
          io_conf.pin_bit_mask = (1ULL << 1);
          io_conf.mode = GPIO_MODE_OUTPUT_OD;
          io_conf.pull_up_en = GPIO_PULLUP_ENABLE;
          gpio_config(&io_conf);
          for (int i = 0; i < 9; i++) {
            gpio_set_level(GPIO_NUM_1, 0);
            esp_rom_delay_us(10);
            gpio_set_level(GPIO_NUM_1, 1);
            esp_rom_delay_us(10);
          }
          // STOP condition
          gpio_config_t io_conf2 = {};
          io_conf2.pin_bit_mask = (1ULL << 2);
          io_conf2.mode = GPIO_MODE_OUTPUT_OD;
          io_conf2.pull_up_en = GPIO_PULLUP_ENABLE;
          gpio_config(&io_conf2);
          gpio_set_level(GPIO_NUM_2, 0);
          esp_rom_delay_us(10);
          gpio_set_level(GPIO_NUM_1, 1);
          esp_rom_delay_us(10);
          gpio_set_level(GPIO_NUM_2, 1);
          esp_rom_delay_us(100);
          // Release pins
          io_conf.mode = GPIO_MODE_INPUT;
          gpio_config(&io_conf);
          io_conf2.mode = GPIO_MODE_INPUT;
          gpio_config(&io_conf2);
          ESP_LOGI("preboot", "Port A bus kick done at priority 1100");

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_ESP32S3_INSTRUCTION_CACHE_32KB: "y"
      CONFIG_SPIRAM_RODATA: "y"
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: "y"

psram:
  mode: quad
  speed: 80MHz

external_components:
  - source: custom_components
    components: [axp2101]
  - source:
      type: git
      url: https://github.com/m5stack/esphome-yaml
      ref: 53c01b0ebe36be9238ca75120d43ff63a95db34e
      path: components
    components: [aw9523b]

wifi:
  ssid: "REDACTED_SSID"
  password: "REDACTED_PASSWORD"
  ap:
    ssid: "CoreS3-Fallback"
    password: "REDACTED_PASSWORD"

captive_portal:
logger:

api:
  encryption:
    key: "REDACTED_API_KEY"

ota:
  - platform: esphome
    password: "REDACTED_OTA_PASSWORD"

safe_mode:
  num_attempts: 20

i2c:
  - id: bus_internal
    sda: GPIO12
    scl: GPIO11
    scan: false
    setup_priority: 1002

  - id: bus_a
    sda: GPIO2
    scl: GPIO1
    scan: false
    setup_priority: 600

axp2101:
  id: axp2101_pmu
  i2c_id: bus_internal
  setup_priority: 970

aw9523b:
  - id: aw9523b_hub
    i2c_id: bus_internal
    setup_priority: 1001

switch:
  - platform: gpio
    name: "BUS OUT EN"
    id: bus_out_en
    pin:
      aw9523b: aw9523b_hub
      number: 1
      mode: OUTPUT
    restore_mode: ALWAYS_ON
    setup_priority: 950
    internal: true

  - platform: gpio
    name: "EXT PWR EN"
    id: ext_pwr_en
    pin:
      aw9523b: aw9523b_hub
      number: 2
      mode: OUTPUT
    restore_mode: ALWAYS_ON
    setup_priority: 950
    internal: true

  - platform: gpio
    name: "USB OTG EN"
    id: usb_otg_en
    pin:
      aw9523b: aw9523b_hub
      number: 4
      mode: OUTPUT
    restore_mode: ALWAYS_OFF
    setup_priority: 950
    internal: true

  - platform: gpio
    name: "BOOST EN"
    id: boost_en
    pin:
      aw9523b: aw9523b_hub
      number: 14
      mode: OUTPUT
    restore_mode: ALWAYS_ON
    setup_priority: 950
    internal: true

bme68x_bsec2_i2c:
  model: bme688
  address: 0x77
  i2c_id: bus_a
  sample_rate: lp
  state_save_interval: 6h

sensor:
  - platform: bme68x_bsec2
    temperature:
      name: "Temperatura"
    humidity:
      name: "Humedad relativa"
    pressure:
      name: "Presion atmosferica"
    iaq:
      name: "IAQ"
    iaq_accuracy:
      name: "Precision IAQ"
    co2_equivalent:
      name: "CO2 equivalente"
    breath_voc_equivalent:
      name: "VOC equivalente"
    gas_resistance:
      name: "Resistencia gas"

  - platform: uptime
    name: "Uptime"
```

### Anything in the logs that might be useful for us?

```txt
### Device details

- **AXP2101 PMU** at address 0x34, internal I2C (GPIO11/GPIO12) — controls all power rails
- **AW9523B IO expander** at address 0x58, internal I2C — controls BUS_OUT_EN (pin 1), EXT_PWR_EN (pin 2), USB_OTG_EN (pin 4), BOOST_EN (pin 14)
- **Port A power rail:** ALDO3 (3.3V) must be enabled by AXP2101 before GPIO1/GPIO2 can be used
- **BLDO1 (2.8V) and BLDO2 (1.5V)** also required for stable Port A operation

---

### Related issues / references

- M5Stack CoreS3-Esphome repo: https://github.com/m5stack/M5CoreS3-Esphome/issues/28
- Terpasaurus forum post (Jul 2025): https://community.m5stack.com/topic/7681/core-s3-i2c-issue-scl-is-held-low-on-the-bus
- ESPHome Devices CoreS3 page: https://devices.esphome.io/devices/m5stack-cores3/
- Feature request for configurable I2C priority: https://github.com/esphome/feature-requests/issues/3069
```

**Comment by jbaquien-sketch** [comment]
https://github.com/m5stack/M5CoreS3-Esphome/issues/36
