### PR TITLE
Fix upload command. MQTT user and password is missing from configuration. #5093

### LINKED ISSUE #5093: Error uploading binary using esphome command line
### The problem

Stayed a long time on version 2022.10.1. After updating to 2023.10.4 I am unable to upload firmware to device using command line `esphome upload CONFIGURATION`. Error: `AttributeError: 'Namespace' object has no attribute 'username'`
Complete Traceback:
```
Traceback (most recent call last):
  File "/usr/local/bin/esphome", line 33, in <module>
    sys.exit(load_entry_point('esphome', 'console_scripts', 'esphome')())
  File "/esphome/esphome/__main__.py", line 1015, in main
    return run_esphome(sys.argv)
  File "/esphome/esphome/__main__.py", line 1002, in run_esphome
    rc = POST_CONFIG_ACTIONS[args.command](args, config)
  File "/esphome/esphome/__main__.py", line 404, in command_upload
    exit_code = upload_program(config, args, port)
  File "/esphome/esphome/__main__.py", line 316, in upload_program
    config, args.username, args.password, args.client_id
AttributeError: 'Namespace' object has no attribute 'username'
```

I tried different esphome versions and found the first version where I get this error is 2023.6.1. 
Tried to find something in the release notes. The only entry I found was PR https://github.com/esphome/esphome/pull/3887. But thats marked as non breaking change

Maybe someone has a hint what I have to change in my configuration to get OTA upload working with versions past 2023.6.1.

 

### Which version of ESPHome has the issue?

2023.6.1 and newer

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2023.10.5

### What platform are you using?

ESP8266

### Board

esp01_1m

### Component causing the issue

esphome CLI

### Example YAML snippet

```yaml
substitutions:
  node_name: wz-aq-vindriktning
  id_prefix: wz_aq_vindriktning
  name_prefix: wz_aq_vindriktning
  psm: HIGH
  node_comment: "IKEA Vindriktning Air Quality Sensor."


wifi:
  ssid: "H3N1"
  password: !secret h3n1_passwd
  domain: .XXXX.XXXXXX.de
  power_save_mode: ${psm}

  ap:
    ssid: ${node_name} fallback
    password: !secret fallback_ap_passwd

mdns:
  disabled: true

web_server:
  port: 80
  version: 1
  auth:
    username: XXXXXXXX
    password: !secret web_passwd

mqtt:
  broker: XXXX.XXXX.XXXXXX.de
  username: XXXXXX
  password: !secret mqtt_passwd
  discovery: true
  topic_prefix: esphome/${id_prefix}
  reboot_timeout: 60 min

time:
  - platform: sntp
    id: sntp_time
    servers: XXXX.XXXX.XXXXXX.de
    timezone: Europe/Berlin

ota:
  password: !secret ota_passwd

captive_portal:

switch:
  - platform: safe_mode
    id: ${id_prefix}_safe_restart
    name: ${name_prefix} Safe Restart
    
  - platform: restart
    id: ${id_prefix}_restart
    name: ${name_prefix} Restart


esphome:
  name: ${node_name}
  comment: ${node_comment}

esp8266:
  board: esp01_1m
  
logger:
  level: INFO
  baud_rate: 0

uart:
  rx_pin: GPIO3
  baud_rate: 9600

sensor:
  - platform: pm1006
    pm_2_5:
      name: pm25
      accuracy_decimals: 2
      filters:
        - or:
          - delta: 3
          - heartbeat: 10s
        - sliding_window_moving_average:
            window_size: 20
            send_every: 10
            send_first_at: 10
```

### Anything in the logs that might be useful for us?

```txt
Traceback (most recent call last):
  File "/usr/local/bin/esphome", line 33, in <module>
    sys.exit(load_entry_point('esphome', 'console_scripts', 'esphome')())
  File "/esphome/esphome/__main__.py", line 1015, in main
    return run_esphome(sys.argv)
  File "/esphome/esphome/__main__.py", line 1002, in run_esphome
    rc = POST_CONFIG_ACTIONS[args.command](args, config)
  File "/esphome/esphome/__main__.py", line 404, in command_upload
    exit_code = upload_program(config, args, port)
  File "/esphome/esphome/__main__.py", line 316, in upload_program
    config, args.username, args.password, args.client_id
AttributeError: 'Namespace' object has no attribute 'username'
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by dylan09**
# Fix missing MQTT parameters for CLI command upload

Fix one of two glitches introduced with esphome 2023.6.0. https://github.com/esphome/esphome/pull/3887

There is another bug since esphome 2023.6.0. The parameter `--device IP` isn't working. It only accepts serial ports. If MQTT is configured for the project, it always try to discover the IP address via MQTT. 
My python experience is not sufficient to fix this bug.
 
## Types of changes

- [ x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes [Error uploading binary using esphome command line](https://github.com/esphome/issues/issues/5093#issue-1986435065)

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ x] ESP32
- [ ] ESP32 IDF
- [ x] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

File: esphome/__main__.py [hunk 1]
```diff
@@ -65,7 +65,7 @@ def choose_prompt(options, purpose: str = None):
         f'Found multiple options{f" for {purpose}" if purpose else ""}, please choose one:'
     )
     for i, (desc, _) in enumerate(options):
-        safe_print(f"  [{i+1}] {desc}")
+        safe_print(f"  [{i + 1}] {desc}")
```
Comment (jesserockz) [inline esphome/__main__.py]: Please put unrelated changes in their own PR
```suggestion
        safe_print(f"  [{i+1}] {desc}")
```

**Review by jesserockz — APPROVED** [review]
