### PR TITLE
Fix format string warnings in Web Server OTA component

### LINKED ISSUE #9562: Compilation failing after update to 2025.7.0 when treating warnings as errors
### The problem

Today I updated ESPHome to version 2025.7.0 and configuration passing on 2025.6.3 can no longer be compiled.

Logs mention error in:

```
src/esphome/components/web_server/ota/ota_web_server.cpp: In member function 'void esphome::web_server::OTARequestHandler::report_ota_progress_(esphome::web_server_idf::AsyncWebServerRequest*)':
src/esphome/components/web_server/ota/ota_web_server.cpp:60:21: error: format '%u' expects argument of type 'unsigned int', but argument 5 has type 'uint32_t' {aka 'long unsigned int'} [-Werror=format=]
```

Details with example are provided in environment information.

### Which version of ESPHome has the issue?

2025.7.0

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Component causing the issue

web_server/ota

### YAML Config

```yaml
esphome:
  name: esp32-c6-compilation-error
  friendly_name: ESP32-C6 Compilation error

esp32:
  board: esp32-c6-devkitc-1
  flash_size: 8MB
  variant: esp32c6
  framework:
    type: esp-idf
    version: "5.2.1"
    platform_version: 6.6.0
    sdkconfig_options:
      CONFIG_OPENTHREAD_ENABLED: n
      CONFIG_ENABLE_WIFI_STATION: y
      CONFIG_USE_MINIMAL_MDNS: y
      CONFIG_ESPTOOLPY_FLASHSIZE_8MB: y

# Enable logging
logger:

ota:
  platform: esphome
  password: "failingcompile"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-C6-compilation-error"
    password: "compileError"

captive_portal:
```

### Anything in the logs that might be useful for us?

```txt
Generating LD script .pioenvs\esp32-c6-compilation-error\memory.ld
In file included from src/esphome/components/web_server/ota/ota_web_server.cpp:6:
src/esphome/components/web_server/ota/ota_web_server.cpp: In member function 'void esphome::web_server::OTARequestHandler::report_ota_progress_(esphome::web_server_idf::AsyncWebServerRequest*)':
src/esphome/components/web_server/ota/ota_web_server.cpp:60:21: error: format '%u' expects argument of type 'unsigned int', but argument 5 has type 'uint32_t' {aka 'long unsigned int'} [-Werror=format=]
   60 |       ESP_LOGD(TAG, "OTA in progress: %u bytes read", this->ota_read_length_);
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/esphome/core/log.h:76:36: note: in definition of macro 'ESPHOME_LOG_FORMAT'
   76 | #define ESPHOME_LOG_FORMAT(format) format
      |                                    ^~~~~~
src/esphome/core/log.h:156:28: note: in expansion of macro 'esph_log_d'
  156 | #define ESP_LOGD(tag, ...) esph_log_d(tag, __VA_ARGS__)
      |                            ^~~~~~~~~~
src/esphome/components/web_server/ota/ota_web_server.cpp:60:7: note: in expansion of macro 'ESP_LOGD'
   60 |       ESP_LOGD(TAG, "OTA in progress: %u bytes read", this->ota_read_length_);
      |       ^~~~~~~~
src/esphome/components/web_server/ota/ota_web_server.cpp:60:40: note: format string is defined here
   60 |       ESP_LOGD(TAG, "OTA in progress: %u bytes read", this->ota_read_length_);
      |                                       ~^
      |                                        |
      |                                        unsigned int
      |                                       %lu
src/esphome/components/web_server/ota/ota_web_server.cpp: In member function 'virtual void esphome::web_server::OTARequestHandler::handleUpload(esphome::web_server_idf::AsyncWebServerRequest*, const esphome::web_server_idf::String&, size_t, uint8_t*, size_t, bool)':
src/esphome/components/web_server/ota/ota_web_server.cpp:155:19: error: format '%u' expects argument of type 'unsigned int', but argument 7 has type 'uint32_t' {aka 'long unsigned int'} [-Werror=format=]
  155 |     ESP_LOGD(TAG, "OTA final chunk: index=%u, len=%u, total_read=%u, contentLength=%u", index, len,
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/esphome/core/log.h:76:36: note: in definition of macro 'ESPHOME_LOG_FORMAT'
   76 | #define ESPHOME_LOG_FORMAT(format) format
      |                                    ^~~~~~
src/esphome/core/log.h:156:28: note: in expansion of macro 'esph_log_d'
  156 | #define ESP_LOGD(tag, ...) esph_log_d(tag, __VA_ARGS__)
      |                            ^~~~~~~~~~
src/esphome/components/web_server/ota/ota_web_server.cpp:155:5: note: in expansion of macro 'ESP_LOGD'
  155 |     ESP_LOGD(TAG, "OTA final chunk: index=%u, len=%u, total_read=%u, contentLength=%u", index, len,
      |     ^~~~~~~~
src/esphome/components/web_server/ota/ota_web_server.cpp:155:67: note: format string is defined here
  155 |     ESP_LOGD(TAG, "OTA final chunk: index=%u, len=%u, total_read=%u, contentLength=%u", index, len,
      |                                                                  ~^
      |                                                                   |
      |                                                                   unsigned int
      |                                                                  %lu
Compiling .pioenvs\esp32-c6-compilation-error\app_trace\app_trace.o
Compiling .pioenvs\esp32-c6-compilation-error\app_trace\app_trace_util.o
Compiling .pioenvs\esp32-c6-compilation-error\app_trace\host_file_io.o
Compiling .pioenvs\esp32-c6-compilation-error\app_trace\port\port_uart.o
cc1plus.exe: some warnings being treated as errors
Compiling .pioenvs\esp32-c6-compilation-error\app_update\esp_ota_ops.o
*** [.pioenvs\esp32-c6-compilation-error\src\esphome\components\web_server\ota\ota_web_server.o] Error 1
========================= [FAILED] Took 20.84 seconds =========================
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by bdraco**
# What does this implement/fix?

This PR fixes format string warnings in the Web Server OTA component that were causing compilation failures when building with `-Werror=format=`. The format specifiers were mismatched with their corresponding argument types.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes #9562

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- N/A

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# No configuration changes required
web_server:
  port: 80
  ota: true
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

## Summary of changes:

Fixed format string specifiers in `esphome/components/web_server/ota/ota_web_server.cpp`:
- Line 155: Changed format specifiers to correctly match types:
  - `%u` → `%zu` for `size_t index`
  - `%u` → `%zu` for `size_t len`
  - `%u` (unchanged) for `uint32_t ota_read_length_`
  - `%u` → `%zu` for `contentLength()` return value (size_t)

These changes ensure the format specifiers match their actual types and resolve compilation warnings when building with `-Werror=format=`.

### CODE REVIEW

**Review by jesserockz — DISMISSED** [review]

**Comment by bdraco** [comment]
Looks like there is another

**Review by jesserockz — APPROVED** [review]
