### ISSUE TITLE
After 2025.09.0 Update: E][bme68x_bsec2.sensor:071]: Communication failed (BSEC2 status: 0, BME68X status: -2)

### ISSUE THREAD

**Issue by djviruss** [OttoWinter/esphomeyaml#10778]
### The problem

I am getting "E][bme68x_bsec2.sensor:071]: Communication failed (BSEC2 status: 0, BME68X status: -2)" error message on my bme680 sensor after updating to 2025.09.0 firmware. Only change was going from 2025-08-? I forgot the latest to 2025-09-0

Board:
ESP32 DevKit Basic.

YAML:
`i2c:
  scan: false

bme68x_bsec2_i2c:
  id: bme680_internal
  model: bme680
  address: 0x77
  temperature_offset: 0
  sample_rate: LP
  state_save_interval: 4h`

Log:
[16:47:57.229][C][bme68x_bsec2_i2c.sensor:030]:   Address: 0x77
[16:47:57.236][C][bme68x_bsec2.sensor:059]: BME68X via BSEC2:
[16:47:57.236][C][bme68x_bsec2.sensor:059]:   BSEC2 version: 2.6.1.0
[16:47:57.236][C][bme68x_bsec2.sensor:059]:   BSEC2 configuration blob:
[16:47:57.236][C][bme68x_bsec2.sensor:059]:     Configured: NO
[16:47:57.237][C][bme68x_bsec2.sensor:067]:     Size: 1943
[16:47:57.241][E][bme68x_bsec2.sensor:071]: **Communication failed (BSEC2 status: 0, BME68X status: -2)**
[16:47:57.251][C][bme68x_bsec2.sensor:078]:   Operating age: 28 days
[16:47:57.251][C][bme68x_bsec2.sensor:078]:   Sample rate: LP
[16:47:57.251][C][bme68x_bsec2.sensor:078]:   Voltage: 3.3V
[16:47:57.251][C][bme68x_bsec2.sensor:078]:   State save interval: 14400000ms
[16:47:57.251][C][bme68x_bsec2.sensor:078]:   Temperature offset: 0.00
[16:47:57.264][C][bme68x_bsec2.sensor:015]:   Temperature 'Temperature'
[16:47:57.264][C][bme68x_bsec2.sensor:015]:     State Class: 'measurement'
[16:47:57.264][C][bme68x_bsec2.sensor:015]:     Unit of Measurement: '°C'
[16:47:57.264][C][bme68x_bsec2.sensor:015]:     Accuracy Decimals: 1
[16:47:57.265][C][bme68x_bsec2.sensor:025]:     Device Class: 'temperature'
[16:47:57.292][C][bme68x_bsec2.sensor:029]:     Icon: 'mdi:thermometer'
[16:47:57.292][C][bme68x_bsec2.sensor:089]:     Sample rate: LP
[16:47:57.305][C][bme68x_bsec2.sensor:015]:   Pressure 'Pressure'
[16:47:57.305][C][bme68x_bsec2.sensor:015]:     State Class: 'measurement'
[16:47:57.305][C][bme68x_bsec2.sensor:015]:     Unit of Measurement: 'hPa'
[16:47:57.305][C][bme68x_bsec2.sensor:015]:     Accuracy Decimals: 1
[16:47:57.306][C][bme68x_bsec2.sensor:025]:     Device Class: 'atmospheric_pressure'
[16:47:57.306][C][bme68x_bsec2.sensor:091]:     Sample rate: LP
[16:47:57.326][C][bme68x_bsec2.sensor:015]:   Humidity 'Humidity'
[16:47:57.326][C][bme68x_bsec2.sensor:015]:     State Class: 'measurement'
[16:47:57.326][C][bme68x_bsec2.sensor:015]:     Unit of Measurement: '%'
[16:47:57.326][C][bme68x_bsec2.sensor:015]:     Accuracy Decimals: 1
[16:47:57.327][C][bme68x_bsec2.sensor:025]:     Device Class: 'humidity'
[16:47:57.327][C][bme68x_bsec2.sensor:029]:     Icon: 'mdi:water-percent'
[16:47:57.337][C][bme68x_bsec2.sensor:093]:     Sample rate: LP
[16:47:57.344][C][bme68x_bsec2.sensor:015]:   Gas resistance 'Gas Resistance'
[16:47:57.344][C][bme68x_bsec2.sensor:015]:     State Class: 'measurement'
[16:47:57.344][C][bme68x_bsec2.sensor:015]:     Unit of Measurement: 'Ω'
[16:47:57.344][C][bme68x_bsec2.sensor:015]:     Accuracy Decimals: 0
[16:47:57.353][C][bme68x_bsec2.sensor:029]:     Icon: 'mdi:gas-cylinder'
[16:47:57.363][C][bme68x_bsec2.sensor:015]:   CO2 equivalent 'CO2 Equivalent'
[16:47:57.363][C][bme68x_bsec2.sensor:015]:     State Class: 'measurement'
[16:47:57.363][C][bme68x_bsec2.sensor:015]:     Unit of Measurement: 'ppm'
[16:47:57.363][C][bme68x_bsec2.sensor:015]:     Accuracy Decimals: 1
[16:47:57.374][C][bme68x_bsec2.sensor:025]:     Device Class: 'carbon_dioxide'
[16:47:57.384][C][bme68x_bsec2.sensor:015]:   Breath VOC equivalent 'Breath VOC Equivalent'
[16:47:57.384][C][bme68x_bsec2.sensor:015]:     State Class: 'measurement'
[16:47:57.384][C][bme68x_bsec2.sensor:015]:     Unit of Measurement: 'ppm'
[16:47:57.384][C][bme68x_bsec2.sensor:015]:     Accuracy Decimals: 1
[16:47:57.400][C][bme68x_bsec2.sensor:025]:     Device Class: 'volatile_organic_compounds_parts'
[16:47:57.405][C][bme68x_bsec2.sensor:015]:   IAQ 'IAQ'
[16:47:57.405][C][bme68x_bsec2.sensor:015]:     State Class: 'measurement'
[16:47:57.405][C][bme68x_bsec2.sensor:015]:     Unit of Measurement: 'IAQ'
[16:47:57.405][C][bme68x_bsec2.sensor:015]:     Accuracy Decimals: 1
[16:47:57.415][C][bme68x_bsec2.sensor:029]:     Icon: 'mdi:gauge'
[16:47:57.430][E][component:144]:   [16:47:57.229][C][bme68x_bsec2_i2c.sensor:030]:   Address: 0x77
[16:47:57.236][C][bme68x_bsec2.sensor:059]: BME68X via BSEC2:
[16:47:57.236][C][bme68x_bsec2.sensor:059]:   BSEC2 version: 2.6.1.0
[16:47:57.236][C][bme68x_bsec2.sensor:059]:   BSEC2 configuration blob:
[16:47:57.236][C][bme68x_bsec2.sensor:059]:     Configured: NO
[16:47:57.237][C][bme68x_bsec2.sensor:067]:     Size: 1943
[16:47:57.241][E][bme68x_bsec2.sensor:071]: **Communication failed (BSEC2 status: 0, BME68X status: -2)**
[16:47:57.251][C][bme68x_bsec2.sensor:078]:   Operating age: 28 days
[16:47:57.251][C][bme68x_bsec2.sensor:078]:   Sample rate: LP
[16:47:57.251][C][bme68x_bsec2.sensor:078]:   Voltage: 3.3V
[16:47:57.251][C][bme68x_bsec2.sensor:078]:   State save interval: 14400000ms
[16:47:57.251][C][bme68x_bsec2.sensor:078]:   Temperature offset: 0.00
[16:47:57.264][C][bme68x_bsec2.sensor:015]:   Temperature 'Temperature'
[16:47:57.264][C][bme68x_bsec2.sensor:015]:     State Class: 'measurement'
[16:47:57.264][C][bme68x_bsec2.sensor:015]:     Unit of Measurement: '°C'
[16:47:57.264][C][bme68x_bsec2.sensor:015]:     Accuracy Decimals: 1
[16:47:57.265][C][bme68x_bsec2.sensor:025]:     Device Class: 'temperature'
[16:47:57.292][C][bme68x_bsec2.sensor:029]:     Icon: 'mdi:thermometer'
[16:47:57.292][C][bme68x_bsec2.sensor:089]:     Sample rate: LP
[16:47:57.305][C][bme68x_bsec2.sensor:015]:   Pressure 'Pressure'
[16:47:57.305][C][bme68x_bsec2.sensor:015]:     State Class: 'measurement'
[16:47:57.305][C][bme68x_bsec2.sensor:015]:     Unit of Measurement: 'hPa'
[16:47:57.305][C][bme68x_bsec2.sensor:015]:     Accuracy Decimals: 1
[16:47:57.306][C][bme68x_bsec2.sensor:025]:     Device Class: 'atmospheric_pressure'
[16:47:57.306][C][bme68x_bsec2.sensor:091]:     Sample rate: LP
[16:47:57.326][C][bme68x_bsec2.sensor:015]:   Humidity 'Humidity'
[16:47:57.326][C][bme68x_bsec2.sensor:015]:     State Class: 'measurement'
[16:47:57.326][C][bme68x_bsec2.sensor:015]:     Unit of Measurement: '%'
[16:47:57.326][C][bme68x_bsec2.sensor:015]:     Accuracy Decimals: 1
[16:47:57.327][C][bme68x_bsec2.sensor:025]:     Device Class: 'humidity'
[16:47:57.327][C][bme68x_bsec2.sensor:029]:     Icon: 'mdi:water-percent'
[16:47:57.337][C][bme68x_bsec2.sensor:093]:     Sample rate: LP
[16:47:57.344][C][bme68x_bsec2.sensor:015]:   Gas resistance 'Gas Resistance'
[16:47:57.344][C][bme68x_bsec2.sensor:015]:     State Class: 'measurement'
[16:47:57.344][C][bme68x_bsec2.sensor:015]:     Unit of Measurement: 'Ω'
[16:47:57.344][C][bme68x_bsec2.sensor:015]:     Accuracy Decimals: 0
[16:47:57.353][C][bme68x_bsec2.sensor:029]:     Icon: 'mdi:gas-cylinder'
[16:47:57.363][C][bme68x_bsec2.sensor:015]:   CO2 equivalent 'CO2 Equivalent'
[16:47:57.363][C][bme68x_bsec2.sensor:015]:     State Class: 'measurement'
[16:47:57.363][C][bme68x_bsec2.sensor:015]:     Unit of Measurement: 'ppm'
[16:47:57.363][C][bme68x_bsec2.sensor:015]:     Accuracy Decimals: 1
[16:47:57.374][C][bme68x_bsec2.sensor:025]:     Device Class: 'carbon_dioxide'
[16:47:57.384][C][bme68x_bsec2.sensor:015]:   Breath VOC equivalent 'Breath VOC Equivalent'
[16:47:57.384][C][bme68x_bsec2.sensor:015]:     State Class: 'measurement'
[16:47:57.384][C][bme68x_bsec2.sensor:015]:     Unit of Measurement: 'ppm'
[16:47:57.384][C][bme68x_bsec2.sensor:015]:     Accuracy Decimals: 1
[16:47:57.400][C][bme68x_bsec2.sensor:025]:     Device Class: 'volatile_organic_compounds_parts'
[16:47:57.405][C][bme68x_bsec2.sensor:015]:   IAQ 'IAQ'
[16:47:57.405][C][bme68x_bsec2.sensor:015]:     State Class: 'measurement'
[16:47:57.405][C][bme68x_bsec2.sensor:015]:     Unit of Measurement: 'IAQ'
[16:47:57.405][C][bme68x_bsec2.sensor:015]:     Accuracy Decimals: 1
[16:47:57.415][C][bme68x_bsec2.sensor:029]:     Icon: 'mdi:gauge'
[16:47:57.430][E][component:144]:   **bme68x_bsec2 is marked FAILED: unspecified**

### Which version of ESPHome has the issue?

2025-09-0

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Component causing the issue

I2c, bme68x_bsec2_i2c

### YAML Config

```yaml
esphome:
  name: poc
  friendly_name: POC

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:
  
# Enable Home Assistant API
api:
  encryption:
    key: "REMOVED"

ota:
  - platform: esphome
    password: "REMOVED"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Poc Fallback Hotspot"
    password: "REMOVED"

captive_portal:

i2c:
  scan: false

bme68x_bsec2_i2c:
  id: bme680_internal
  model: bme680
  address: 0x77
  temperature_offset: 0
  sample_rate: LP
  state_save_interval: 4h


debug:
  update_interval: 5s

web_server:
  port: 80

sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
    device_class: ""
  
  - platform: uptime
    type: seconds
    id: uptime_s
    update_interval: 15s

  - platform: debug
    free: 
      name: "Heap Free"
      id: esp32_heap
      filters:
      - lambda: return x / 1024; # Convert bytes to megabytes
      unit_of_measurement: "MB"
    # loop_time: 
    #   name: "Loop Time"
    #   id: esp32_loop
    # # cpu_frequency:
    #   id: esp32_cpu_freq
    #   filters:
    #    - lambda: return x / 1000000.0;           
    #   unit_of_measurement: "Mhz"
    #   accuracy_decimals: 1

  # - platform: template
  #   name: "CPU Usage"
  #   lambda: |-
  #     float current_freq_mhz = id(esp32_cpu_freq).state;
  #     float custom_value = current_freq_mhz / 240.0 * 100.0;
  #     return custom_value;
  #   unit_of_measurement: "%"
  #   accuracy_decimals: 1
  #   entity_category: "diagnostic"

  - platform: bme68x_bsec2
    # bme68x_bsec2_id: bme680_internal
    temperature:
      id: temperature
      name: "Temperature"
      sample_rate: LP
      filters: 
        - median 
    pressure:
      id: pressure
      name: "Pressure"
      sample_rate: LP
      filters: 
        - median
    humidity:
      id: "humidity"
      name: "Humidity"
      sample_rate: LP
      filters: 
        - median
    gas_resistance:
      id: "gas_resistance"
      name: "Gas Resistance"
      filters: 
        - median
    iaq: 
      name: "IAQ"
      id: iaq
      filters: 
        - median
      accuracy_decimals: 1
    co2_equivalent:
      id: co2_equivalent 
      name: "CO2 Equivalent"
      filters: 
        - median
    breath_voc_equivalent:
      id: breath_voc_equivalent 
      name: "Breath VOC Equivalent"
      filters: 
        - median
  
  # - platform: template
  #   name: "Air Quality"
  #   id: iaq_accuracy
  #   icon: "mdi:gauge"
  #   # calculation: comp_gas = log(R_gas[ohm]) + 0.04 log(Ohm)/%rh * hum[%rh]
  #   lambda: |-
  #     return log(id(gas_resistance).state) + 0.04 *  id(humidity).state;
  #   state_class: "measurement"

  - platform: adc
    pin: GPIO34
    name: Soil Moisture
    id: soil_moisture
    accuracy_decimals: 1
    update_interval: 1s
    icon: mdi:flower
    unit_of_measurement: '%'
    attenuation: auto
    filters:
      - sliding_window_moving_average:
          window_size: 15
          send_every: 5
      - lambda: |-
          if (x > 2.4) {
            return 0;
          } else if (x < 1.0) {
            return 100;
          } else {
            return ((2.4 - x) / (2.4 - 1.0) * 100.0);
          }

      - delta: 2.0%

binary_sensor:
  - platform: status
    name: "POC Status"
    
text_sensor:
  # - platform: debug
  #   reset_reason: 
  #     name: "Reset Reason"

  - platform: template
    name: "Uptime"
    update_interval: 30s
    lambda: |-
      auto s = millis() / 1000;
      return str_snprintf("%02d:%02d:%02d:%02d", 11, s / 86400, s / 3600 % 24, s / 60 % 60, s % 60);
  
  - platform: template
    name: "Air Quality"
    icon: "mdi:checkbox-marked-circle-outline"
    lambda: |-
      if ( int(id(iaq).state) <= 50) {
        return {"Excellent"};
      }
      else if (int(id(iaq).state) >= 51 && int(id(iaq).state) <= 100) {
        return {"Good"};
      }
      else if (int(id(iaq).state) >= 101 && int(id(iaq).state) <= 150) {
        return {"Lightly polluted"};
      }
      else if (int(id(iaq).state) >= 151 && int(id(iaq).state) <= 200) {
        return {"Moderately polluted"};
      }
      else if (int(id(iaq).state) >= 201 && int(id(iaq).state) <= 250) {
        return {"Heavily polluted"};
      }
      else if (int(id(iaq).state) >= 251 && int(id(iaq).state) <= 350) {
        return {"Severely polluted"};
      }
      else if (int(id(iaq).state) >= 351) {
        return {"Extremely polluted"};
      }
      else {
        return {"error"};
      }

  - platform: template
    name: "Soil Moisture *Generic Flowers, Trees, Shrubs*"
    icon: "mdi:flower"
    lambda: |-
      if (int(id(soil_moisture).state) <= 15) {
        return {"Very Dry"};
      }
      else if (int(id(soil_moisture).state) <= 21) {
        return {"Dry"};
      }
      else if (int(id(soil_moisture).state) <= 81) {
        return {"Wet"};
      }
      else if (int(id(soil_moisture).state) <= 89) {
        return {"Very Wet"};
      }
      else if (int(id(soil_moisture).state) <= 100) {
        return {"Soaked"};
      }
      else {
        return {"error"};
      } 

button:
  - platform: restart
    name: Restart
    id: restart_button
```

### Anything in the logs that might be useful for us?

```txt
Was working before 2025-09-0 update, Nothing changes just applied update.
```

**Comment by ginjo** [comment]
Also getting errors in 2025.9.0.

For example:

`src/esphome/esphome/components/esp32/core.cpp:59:46: error: 'esp_cpu_get_cycle_count' was not declared in this scope`

and

`/esphome/esphome/components/light/light_color_values.h:94:21: error: 'lerp' is not a member of 'std'`

My project has nothing to do with lighting, and I don't call `esp_cpu_get_cycle_count`, at least not directly. I haven't dug extensively into this yet, but my previous build with 2024.7.3 has been working flawlessly. I'll update if i find out more.

EDIT: I see that my issue is completely different from OP's, sorry bout that! If I find more information, I'll post/comment in an appropriate thread.

**Comment by ssieb** [comment]
@ginjo do you have a `custom_components` directory?

**Comment by ssieb** [comment]
@djviruss get serial logs from boot

**Comment by ginjo** [comment]
@ssieb No `custom_components` directory, but I am loading an external component that I developed. That could be part of my particular error set, but again, it's been building and running without errors until I updated esphome.

Since I skipped so many versions, I should probably find out if previous releases (after 2024.7.3) exhibit the same errors when I build.

**Comment by djviruss** [comment]
@ssieb, Thank you. I went and pulled the power from the ESP32 board and did a hard reboot fixed this issue for me. I don't know why but it is working again after a full power (hard) reboot. 

Thank you all and good luck.
