### ISSUE TITLE
Compile with DM9051 failed since 2026.04 (SPI interface issue)

### ISSUE THREAD

**Issue by B48D81EFCC** [OttoWinter/esphomeyaml#16035]
### The problem

Compilation fails since `2026.04` with `DM9051` `ethernet` component.
I suspect https://github.com/esphome/esphome/pull/10285 causing the issue.

Compilation with `2026.03` works fine.

### Which version of ESPHome has the issue?

2026.04

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Component causing the issue

ethernet/DM9051

### YAML Config

```yaml
esp32:
  variant: esp32c3
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

ethernet:
  type: DM9051
  clk_pin: GPIO07
  mosi_pin: GPIO10
  miso_pin: GPIO03
  cs_pin: GPIO09
  interrupt_pin: GPIO08
  reset_pin: GPIO06
  clock_speed: 8MHz
```

### Anything in the logs that might be useful for us?

```txt
In file included from src/esphome/components/network/util.h:9,
                 from src/esphome/components/api/api_connection.cpp:21:
src/esphome/components/ethernet/ethernet_component.h:224:32: error: 'SPI3_HOST' was not declared in this scope; did you mean 'SPI2_HOST'?
  224 |   spi_host_device_t interface_{SPI3_HOST};
      |                                ^~~~~~~~~
      |                                SPI2_HOST
src/esphome/components/ethernet/ethernet_component.h:224:41: error: cannot convert '<brace-enclosed initializer list>' to 'spi_host_device_t' in initialization
  224 |   spi_host_device_t interface_{SPI3_HOST};
```

**Comment by swoboda1337** [comment]
Are you using 2026.4.0? That should have been fixed already in 2026.4.1 https://github.com/esphome/esphome/pull/15809

**Comment by B48D81EFCC** [comment]
Thanks. Did not realise that I still used 2026.04.
It is working with 2026.04.2
