### PR TITLE
[ethernet] Fix SPI3_HOST default breaking compile on variants without SPI3

### LINKED ISSUE #15798: ethernet: W5500 on ESP32-C3 fails to compile in 2026.4.0 (SPI3_HOST undeclared)
## The problem

Starting with ESPHome 2026.4.0 (PR #10285, commit c7a163441e), compilation fails for ESP32-C3 devices using the W5500 SPI ethernet component under esp-idf. The Python-side default / validator added by #10285 works correctly (defaults to `spi2` on C3 and calls `set_interface(SPI2_HOST)` at runtime), but the C++ class member in `ethernet_component.h` was given an unconditional default initializer of `SPI3_HOST`, which is not a defined enum value on variants without SPI3 hardware. The header therefore fails to compile on ESP32-C3 (and should also fail on C5/C6/C61/H2).

## Environment

- **ESPHome version**: 2026.4.0
- **Installation**: Docker (esphome/esphome:2026.4.0)
- **Platform**: ESP32 (specifically ESP32-C3 via esp-idf)
- **Component**: ethernet (W5500)

## YAML Config (minimal reproduction)

```yaml
esphome:
  name: test-c3-w5500

esp32:
  board: esp32-c3-devkitc-02
  framework:
    type: esp-idf

ethernet:
  type: W5500
  mosi_pin: GPIO06
  miso_pin: GPIO04
  clk_pin: GPIO7
  cs_pin: GPIO10
  reset_pin: GPIO05
  interrupt_pin: GPIO03
  clock_speed: 40MHz
```

## Logs

```
Compiling .pioenvs/test/src/esphome/components/api/api_connection.cpp.o
In file included from src/esphome/components/network/util.h:9,
                 from src/esphome/components/api/api_connection.cpp:21:
src/esphome/components/ethernet/ethernet_component.h:224:32: error: 'SPI3_HOST' was not declared in this scope; did you mean 'SPI2_HOST'?
  224 |   spi_host_device_t interface_{SPI3_HOST};
      |                                ^~~~~~~~~
      |                                SPI2_HOST
src/esphome/components/ethernet/ethernet_component.h:224:41: error: cannot convert '<brace-enclosed initializer list>' to 'spi_host_device_t' in initialization
  224 |   spi_host_device_t interface_{SPI3_HOST};
      |                                         ^
*** [.pioenvs/test/src/esphome/components/api/api_connection.cpp.o] Error 1
========================= [FAILED] =========================
```

## Root cause

PR #10285 added:

```cpp
// esphome/components/ethernet/ethernet_component.h
spi_host_device_t interface_{SPI3_HOST};
```

On ESP-IDF targets where `SOC_SPI_PERIPH_NUM <= 2` (ESP32-C3, C5, C6, C61, H2), `SPI3_HOST` is not declared in the `spi_host_device_t` enum — only `SPI2_HOST` exists. The Python validator (`_validate_spi_interface`) correctly defaults C3/C5/C6/H2/etc. to `spi2` and calls `set_interface(SPI2_HOST)` during setup, but that only affects the runtime value. The compiler still needs `SPI3_HOST` to be a defined symbol at header-parse time.

The PR's own compatibility table identifies ESP32-H2 as an explicit bugfix target for the same "no SPI3 HW" reason — but the header initializer was missed.

Setting `interface: spi2` in YAML does **not** work around this — the symbol is baked into the class declaration regardless of the runtime value.

## Suggested fix

Change the default initializer to a symbol that exists on all variants:

```cpp
spi_host_device_t interface_{SPI2_HOST};
```

This is safe: on classic ESP32, the Python validator calls `set_interface(SPI3_HOST)` during setup so the default is overwritten before `interface_` is read. Same pattern the PR already relies on for the no-SPI3 variants.

Alternative: guard with a preprocessor conditional, e.g.

```cpp
#if SOC_SPI_PERIPH_NUM >= 3
  spi_host_device_t interface_{SPI3_HOST};
#else
  spi_host_device_t interface_{SPI2_HOST};
#endif
```

but the plain `SPI2_HOST` default is simpler since the Python codegen always sets the correct value.

## Additional information

Workaround until a fix lands: pin to ESPHome 2026.3.3 (last release before #10285) for any ESP32-C3/C5/C6/C61/H2 device with SPI ethernet.

### PR DESCRIPTION
**Pull request by swoboda1337**
# What does this implement/fix?

The class member `interface_` in `ethernet_component.h` is initialized to `SPI3_HOST`, which is not a declared enum value of `spi_host_device_t` on ESP32 variants where `SOC_SPI_PERIPH_NUM <= 2` (C3, C5, C6, C61, H2). The header is included transitively from many translation units (e.g. `network/util.h` → `api_connection.cpp`), so the build fails on those chips even when ethernet isn't in the user's YAML.

The Python codegen always calls `var.set_interface(SPI_INTERFACE_MAP[config[CONF_INTERFACE]])` and the validator picks the right host per variant, so the C++ default initializer is never read at runtime. Replacing the default with `SPI2_HOST` (which exists on every variant that supports SPI ethernet) is sufficient and behavior-preserving.

Regression introduced in 2026.4.0 by #10285.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) — [policy](https://developers.esphome.io/contributing/code/#what-constitutes-a-c-breaking-change)
- [ ] Developer breaking change (an API change that could break external components) — [policy](https://developers.esphome.io/contributing/code/#what-is-considered-public-c-api)
- [ ] Undocumented C++ API change (removal or change of undocumented public methods that lambda users may depend on) — [policy](https://developers.esphome.io/contributing/code/#c-user-expectations)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes https://github.com/esphome/esphome/issues/15798

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#N/A

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040/RP2350
- [ ] BK72xx
- [ ] RTL87xx
- [ ] LN882x
- [ ] nRF52840

## Example entry for `config.yaml`:

```yaml
esp32:
  board: esp32-c3-devkitc-02
  framework:
    type: esp-idf

ethernet:
  type: W5500
  mosi_pin: GPIO06
  miso_pin: GPIO04
  clk_pin: GPIO7
  cs_pin: GPIO10
  reset_pin: GPIO05
  interrupt_pin: GPIO03
  clock_speed: 40MHz
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by bdraco — DISMISSED** [review]

**Review by bdraco — APPROVED** [review]

**Comment by bdraco** [comment]
target branch is missing base config so its expected to fail memory impact. This is ok as this PR will fix it

**Comment by swoboda1337** [comment]
Thanks
