### ISSUE TITLE
compilation fails if mdns: added in config

### ISSUE THREAD

**Issue by vit5041** [OttoWinter/esphomeyaml#10770]
### The problem

cannot compile config if it contains mdns:  line (if mdns is enabled)

### Which version of ESPHome has the issue?

2025.9.0

### What type of installation are you using?

Docker

### What platform are you using?

ESP8266

### Component causing the issue

mdns

### YAML Config

```yaml
esphome:
  name: test
  friendly_name: test

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  - platform: esphome
    password: !secret ota_password

mdns:
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: "vPq3uGLJkIj8"

captive_portal:
```

### Anything in the logs that might be useful for us?

```txt
In file included from /config/.esphome/platformio/packages/framework-arduinoespressif8266/libraries/ESP8266mDNS/src/ESP8266mDNS.h:48,
                 from /config/.esphome/platformio/packages/framework-arduinoespressif8266/libraries/ESP8266mDNS/src/ESP8266mDNS.cpp:23:
/config/.esphome/platformio/packages/framework-arduinoespressif8266/libraries/ESP8266mDNS/src/LEAmDNS.h:116:10: fatal error: WiFiUdp.h: No such file or directory

*****************************************************************
* Looking for WiFiUdp.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:WiFiUdp.h"
* Web  > https://registry.platformio.org/search?q=header:WiFiUdp.h
*
*****************************************************************

  116 | #include "WiFiUdp.h"
      |          ^~~~~~~~~~~
compilation terminated.
*** [.pioenvs/test/libfb2/ESP8266mDNS/ESP8266mDNS.cpp.o] Error 1
========================= [FAILED] Took 26.48 seconds =========================
```

**Comment by bdraco** [comment]
workaround
```diff
diff --git a/esphome/components/mdns/__init__.py b/esphome/components/mdns/__init__.py
index a21ef9d97..d3118f3ea 100644
--- a/esphome/components/mdns/__init__.py
+++ b/esphome/components/mdns/__init__.py
@@ -81,6 +81,7 @@ async def to_code(config):
         if CORE.is_esp32:
             cg.add_library("ESPmDNS", None)
         elif CORE.is_esp8266:
+            cg.add_library("ESP8266WiFi", None)
             cg.add_library("ESP8266mDNS", None)
         elif CORE.is_rp2040:
             cg.add_library("LEAmDNS", None)
```

**Comment by bdraco** [comment]
regressed in d1276dc6df07f4af76cba228c063c3faea6c132b. will do a fix shortly
