### PR TITLE
[audio, resampler] Add new resampler microphone component

### LINKED ISSUE #3072: Microphone Resampler Component (to cope with a shared I2S bus)
**Describe the problem you have/What new integration you would like**

The [Onju Voice](https://github.com/justLV/onju-voice) board I'm working with supports only one I2S bus for the microphones and speaker. As I'd like to use the on-device MircoWakeWord engine, which requires a 16khz input signal (see [this code line](https://github.com/esphome/esphome/blob/1d6d0d66dca39d1fedf7b2496da4e19835679a12/esphome/components/micro_wake_word/preprocessor_settings.h#L15) and [this code line](https://github.com/esphome/home-assistant-voice-pe/blob/4b31449b8b6df943320ba91d476b7edc488f7d82/esphome/components/micro_wake_word/preprocessor_settings.h#L19)), the whole I2S bus must run at 16khz (see [this comment](https://github.com/tetele/onju-voice-satellite/issues/52#issuecomment-2225751543) and [this comment](https://github.com/tetele/onju-voice-satellite/discussions/113#discussioncomment-12349993) and [this comment](https://github.com/esphome/issues/issues/6599#issuecomment-2667595576) and [this discussion](https://github.com/tetele/onju-voice-satellite/discussions/100#discussion-7673704)). This is no issue to audio input, but decreases the perceived quality of audio output (e.g. music through a media_player), which is now restricted to 16khz as well.

The recently introduced resample speaker (see [this PR](https://github.com/esphome/esphome/pull/8169)) offers to resample audio output up and down. Thus, I think a similar resample microphone is desirable, which could reuse most of the code of the resample speaker and underlying resampler implementation (see [this repo](https://github.com/esphome/esp-audio-libs/tree/main)). This would allow to resample the received audio from the I2S bus (48kHz) to 16kHz before publishing it as output of the microphone. Thus, the chain would be i2s_input -> resampler -> microphone, while the resampler carries over any needed settings from the microphone (like the d_in_pin). 

While downsampling seems to be computationally expensive (see "facts" in [this discussion](https://github.com/tetele/onju-voice-satellite/discussions/100#discussion-7673704)), I have not seen an implemented experiment yet, that allows to draw the conclusion that is too expensive for an ESP32S3. In contrast, I've used an experiment that implemented downsampling, which works just fine on an ESP32S3 (see the non-standard approach below).

**Please describe your use case for this integration and alternatives you've tried:**

Use Case: Decent audio output quality (at least 44.1khz) from a shared I2S bus (speaker and microphone sharing the bus), while allowing to utilize the on-device MicroWakeWord engine (requiring 16khz). 

A non-standard/-stable approach (see  [this code](https://github.com/dreimer1986/onju-voice-satellite/blob/cc87ace008a7d7f0b6b7ceba3aac8d984b31819e/esphome/onju-voice-microwakeword.yaml#L171) and [this repo](https://github.com/gnumpi/esphome_audio/tree/dev-next)) allows setting the I2S bus to 48khz while resampling the audio input from the bus to 16khz before making it available as output of the esphome microphone, effectively meeting the requirements of the MicroWakeWord engine. I got this setup running and it works as expected. The I2S bus is now running at 48khz, which restores the perceived output audio quality to "good". Nevertheless, this specific code approach was abandoned, it requires the v4 esp-idf, and isn't usable with the recent speaker and media_player PRs from 2025.02 (requiring to fall back to at least 2024.12).

**Additional context**

According to some discussion I read, it should be possible to tune esphome's I2S implementation for dynamically configuring it to either 16kHz or 48kHz based on current requirements. Unfortunately, this appears to be rather complex and one would need to touch many components due to breaking changes. Thus, an input resampler seems to be the easier option or at least an intermediate option until someone reworks the I2S implementation.

Code example of an envisioned config:

```yaml
i2s_audio:
  - id: i2s_shared
    i2s_lrclk_pin:
      number: GPIO...
    i2s_bclk_pin:
      number: GPIO...

speaker:
  - platform: i2s_audio
    id: i2s_audio_speaker
    sample_rate: 48000
    i2s_dout_pin: GPIO...
    bits_per_sample: 32bit
    i2s_audio_id: i2s_shared
    ...

- platform: resampler
    id: resampling_microphone
    input_bus: i2s_shared
    i2s_sampling_rate: 48000
    i2s_bits_per_sample: 32bit
    # output sampling_rate inherited from downstream microphone
    # output bits_per_second inherited from downstream microphone

microphone:
  - platform: nabu_microphone # from voice-pe
    i2s_din_pin: GPIO...
    ...
    sample_rate: 16000 # output_sample_rate
    bits_per_sample: 32bit # output_bits_per_second
    i2s_audio_id: resampling_microphone
    channel_0:
      id: asr_micr
    channel_1:
      id: mww_mic

micro_wake_word: # from voice-pe
  id: mww
  models: ...
  vad: ...
  microphone: mww_mic

voice_assistant: # from voice-pe
  id: va
  microphone: asr_mic
  ...
```

The following people might be interested in this component: @tetele , @dreimer1986 , @kahrendt , @jhbruhn

### PR DESCRIPTION
**Pull request by kahrendt**
# What does this implement/fix?

Adds a callback sink option to the ``AudioSinkTransferBuffer`` class.

Adds a resampler microphone component that uses the ``esp-audio-libs``'s resampler (which is a combination of cascaded biquad filters and an FIR filter). 

At the moment, this is not particularly useful, as it is much better to read the microphone at 16 kHz directly for the voice assistant and microWakeWord components. This will be more useful in the future, once we add support for duplex audio on a single I2S bus, as the microphone and speaker need to use the same sample rate to work at the same time. 

Note that I doubt this resampler will produce good results on devices that don't actually read audio with a true 48 kHz sample rate; e.g., some Respeaker Lite XMOS firmwares send audio at 48 kHz, but the samples are just replicated three times from a signal with a true sample rate of 16 kHz. Additionally, this resampler is very computational expensive compared to dropping 2 out of 3 samples on that type of device!

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- closes https://github.com/esphome/feature-requests/issues/3072

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#5130

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx
- [ ] nRF52840

## Example entry for `config.yaml`:

```yaml
# Example config.yaml


microphone:
  - platform: i2s_audio
    id: box_mic
    sample_rate: 48000
    i2s_din_pin: GPIO16
    bits_per_sample: 16bit
    adc_type: external
  - platform: resampler
    id: resampler_mic
    sample_rate: 16000
    microphone: box_mic


```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by kahrendt** [comment]
Requires https://github.com/esphome/esphome/pull/9688 to fix the CI failure on the untouched microphone component.

File: esphome/components/resampler/microphone/__init__.py [hunk 1]
```diff
@@ -0,0 +1,104 @@
...
+
+    cg.add(var.set_buffer_duration(config[CONF_BUFFER_DURATION]))
+
+    if task_stack_in_psram := config.get(CONF_TASK_STACK_IN_PSRAM):
+        cg.add(var.set_task_stack_in_psram(task_stack_in_psram))
+        if task_stack_in_psram:
+            if config[CONF_TASK_STACK_IN_PSRAM]:
+                esp32.add_idf_sdkconfig_option(
+                    "CONFIG_SPIRAM_ALLOW_STACK_EXTERNAL_MEMORY", True
+                )
```
Comment (kbx81) [inline esphome/components/resampler/microphone/__init__.py]: I think you can simplify this to:
```suggestion
        esp32.add_idf_sdkconfig_option("CONFIG_SPIRAM_ALLOW_STACK_EXTERNAL_MEMORY", task_stack_in_psram)
```

File: esphome/components/resampler/microphone/resampler_microphone.h [hunk 2]
```diff
@@ -0,0 +1,82 @@
...
+  StackType_t *task_stack_buffer_{nullptr};
+
+  audio::AudioStreamInfo source_stream_info_;
+
+  uint16_t taps_;
+  uint16_t filters_;
+
+  uint32_t target_sample_rate_;
+
+  uint32_t buffer_duration_ms_;
```
Comment (kbx81) [inline esphome/components/resampler/microphone/resampler_microphone.h]: If you reorder these from widest to narrowest, it should reduce padding. Something like this maybe?:
```suggestion
  uint32_t target_sample_rate_;
  uint32_t buffer_duration_ms_;
  uint16_t taps_;
  uint16_t filters_;
  bool task_stack_in_psram_{false};

  EventGroupHandle_t event_group_{nullptr};
  SemaphoreHandle_t active_listeners_semaphore_{nullptr};
  microphone::MicrophoneSource *microphone_source_{nullptr};
  TaskHandle_t task_handle_{nullptr};
  StackType_t *task_stack_buffer_{nullptr};

  StaticTask_t task_stack_;
  std::weak_ptr<RingBuffer> ring_buffer_;
  audio::AudioStreamInfo source_stream_info_;
```

File: esphome/components/resampler/microphone/__init__.py (hunk 1 above)
Comment (kahrendt) [reply esphome/components/resampler/microphone/__init__.py]: You're right that this can be simplified. I took out the unnecessary line 96, but kept the if statement in line 95. Other components may want to set this sdkconfig option to true. Since the sdkconfig option defaults to false, this avoids contradicting options between two components.

File: esphome/components/resampler/microphone/resampler_microphone.cpp [hunk 3]
```diff
@@ -0,0 +1,302 @@
...
+      break;
+  }
+}
+
+void ResamplerMicrophone::start() {
+  if (this->is_failed())
+    return;
+
+  xSemaphoreTake(this->active_listeners_semaphore_, 0);
+}
```
Comment (jesserockz) [inline esphome/components/resampler/microphone/resampler_microphone.cpp:172]: Maybe in here you can enable the loop `this->enable_loop()` and also disable it after stopping is complete. No need to run it when nothing is happening.

**Comment by rmeissn** [comment]
Just to let you know: I'm interested in this functionality and a proper filter would be much better in quality than dropping each third sample (causing artifacts).

**Comment by bdraco** [comment]
Marking draft as there are conflicts

**Comment by mrbubble62** [comment]
Unfortunately the PR will not compile 
ghcr.io/esphome/esphome:latest

```
external_components:
  - source: github://pr#9675
    components: [audio, resampler]
    refresh: 1h
```
```
In file included from src/esphome/components/audio/audio_reader.cpp:1:
src/esphome/components/audio/audio_reader.h:12:10: fatal error: esp_http_client.h: No such file or directory

*******************************************************************************
* Looking for esp_http_client.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:esp_http_client.h"
* Web  > https://registry.platformio.org/search?q=header:%1B%5Bm%1B%5BKesp_http_client.h
*
*******************************************************************************

   12 | #include <esp_http_client.h>
      |          ^~~~~~~~~~~~~~~~~~~
```

**Comment by mrbubble62** [comment]
> Unfortunately the PR will not compile ghcr.io/esphome/esphome:latest
> 
> ```
> external_components:
>   - source: github://pr#9675
>     components: [audio, resampler]
>     refresh: 1h
> ```
> 
> ```
> In file included from src/esphome/components/audio/audio_reader.cpp:1:
> src/esphome/components/audio/audio_reader.h:12:10: fatal error: esp_http_client.h: No such file or directory
> 
> *******************************************************************************
> * Looking for esp_http_client.h dependency? Check our library registry!
> *
> * CLI  > platformio lib search "header:esp_http_client.h"
> * Web  > https://registry.platformio.org/search?q=header:%1B%5Bm%1B%5BKesp_http_client.h
> *
> *******************************************************************************
> 
>    12 | #include <esp_http_client.h>
>       |          ^~~~~~~~~~~~~~~~~~~
> ```

works with esphome:2026.1.4

**Comment by kahrendt** [comment]
Closing this as I don't have the time to get it over the finish line in the near future.
