### ISSUE TITLE
ethernet: W5500 on ESP32-C3 fails to compile in 2026.4.0 (SPI3_HOST undeclared)

### ISSUE THREAD

**Issue by dbl-0** [OttoWinter/esphomeyaml#15798]
## The problem

Starting with ESPHome 2026.4.0 (PR #10285, commit c7a163441e), compilation fails for ESP32-C3 devices using the W5500 SPI ethernet component under esp-idf. The Python-side default / validator added by #10285 works correctly (defaults to `spi2` on C3 and calls `set_interface(SPI2_HOST)` at runtime), but the C++ class member in `ethernet_component.h` was given an unconditional default initializer of `SPI3_HOST`, which is not a defined enum value on variants without SPI3 hardware. The header therefore fails to compile on ESP32-C3 (and should also fail on C5/C6/C61/H2).

## Environment

- **ESPHome version**: 2026.4.0
- **Installation**: Docker (esphome/esphome:2026.4.0)
- **Platform**: ESP32 (specifically ESP32-C3 via esp-idf)
- **Component**: ethernet (W5500)

## YAML Config (minimal reproduction)

```yaml
esphome:
  name: test-c3-w5500

esp32:
  board: esp32-c3-devkitc-02
  framework:
    type: esp-idf

ethernet:
  type: W5500
  mosi_pin: GPIO06
  miso_pin: GPIO04
  clk_pin: GPIO7
  cs_pin: GPIO10
  reset_pin: GPIO05
  interrupt_pin: GPIO03
  clock_speed: 40MHz
```

## Logs

```
Compiling .pioenvs/test/src/esphome/components/api/api_connection.cpp.o
In file included from src/esphome/components/network/util.h:9,
                 from src/esphome/components/api/api_connection.cpp:21:
src/esphome/components/ethernet/ethernet_component.h:224:32: error: 'SPI3_HOST' was not declared in this scope; did you mean 'SPI2_HOST'?
  224 |   spi_host_device_t interface_{SPI3_HOST};
      |                                ^~~~~~~~~
      |                                SPI2_HOST
src/esphome/components/ethernet/ethernet_component.h:224:41: error: cannot convert '<brace-enclosed initializer list>' to 'spi_host_device_t' in initialization
  224 |   spi_host_device_t interface_{SPI3_HOST};
      |                                         ^
*** [.pioenvs/test/src/esphome/components/api/api_connection.cpp.o] Error 1
========================= [FAILED] =========================
```

## Root cause

PR #10285 added:

```cpp
// esphome/components/ethernet/ethernet_component.h
spi_host_device_t interface_{SPI3_HOST};
```

On ESP-IDF targets where `SOC_SPI_PERIPH_NUM <= 2` (ESP32-C3, C5, C6, C61, H2), `SPI3_HOST` is not declared in the `spi_host_device_t` enum — only `SPI2_HOST` exists. The Python validator (`_validate_spi_interface`) correctly defaults C3/C5/C6/H2/etc. to `spi2` and calls `set_interface(SPI2_HOST)` during setup, but that only affects the runtime value. The compiler still needs `SPI3_HOST` to be a defined symbol at header-parse time.

The PR's own compatibility table identifies ESP32-H2 as an explicit bugfix target for the same "no SPI3 HW" reason — but the header initializer was missed.

Setting `interface: spi2` in YAML does **not** work around this — the symbol is baked into the class declaration regardless of the runtime value.

## Suggested fix

Change the default initializer to a symbol that exists on all variants:

```cpp
spi_host_device_t interface_{SPI2_HOST};
```

This is safe: on classic ESP32, the Python validator calls `set_interface(SPI3_HOST)` during setup so the default is overwritten before `interface_` is read. Same pattern the PR already relies on for the no-SPI3 variants.

Alternative: guard with a preprocessor conditional, e.g.

```cpp
#if SOC_SPI_PERIPH_NUM >= 3
  spi_host_device_t interface_{SPI3_HOST};
#else
  spi_host_device_t interface_{SPI2_HOST};
#endif
```

but the plain `SPI2_HOST` default is simpler since the Python codegen always sets the correct value.

## Additional information

Workaround until a fix lands: pin to ESPHome 2026.3.3 (last release before #10285) for any ESP32-C3/C5/C6/C61/H2 device with SPI ethernet.

**Comment by sensy-one** [comment]
I’m running into the same issue here after upgrading to ESPHome 2026.4.0.

Using ESP32 + W5500 over SPI, and the build fails with the same `SPI3_HOST` not declared error coming from `ethernet_component.h`.

I also tried adding:

```
interface: spi2
```

but that doesn’t help, it still fails during compile, so it looks like the problem happens before the config is even applied.

Downgraded back to 2026.2.2 and everything builds and works fine again with the exact same config.

So yeah, definitely looks like something introduced in 2026.4.0.

Let me know if you want me to test anything!
