### PR TITLE
Upgrade rweather/Crypto from 0.2.0 to 0.4.0

### LINKED ISSUE #3392: DSMR fails to compile on Arduino 2.0.3 + platform 4.4.0: missing hwcrypto/aes.h
### The problem

Using ESPHome with Arduino @ 2.0.3 and platform-espressif32 @ 4.4.0 breaks compilation of the DSMR component. I try to build the project with `esphome run thefile.yaml`, but it fails because it cannot find `hwcrypto/aes.h`.

I installed the development version of ESPHome via `pip install git+https://github.com/esphome/esphome.git@dev` to see if this was recently fixed.

I get the same error with ESPHome 2022.6.1 and any 4.x.x platform. Deleting the `.esphome` and `$HOME/.platformio/.cache` directories doesn't help to fix this.

### Which version of ESPHome has the issue?

2022.7.0-dev

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

n/a

### What platform are you using?

ESP32

### Board

frogboard

### Component causing the issue

DSMR

### Example YAML snippet

```yaml
esp32:
  board: frogboard
  framework:
    type: arduino
    version: 2.0.3
    platform_version: 4.4.0

# ... snip common config, like device name, wifi parameters, etc.

dsmr:
  uart_id: uart_dsmr
  request_interval: 5s

uart:
  id: uart_dsmr
  baud_rate: 115200
  rx_pin:
    number: GPIO21
    inverted: true
  rx_buffer_size: 1700
```

### Anything in the logs that might be useful for us?

```txt
In file included from src/esphome/components/dsmr/dsmr.cpp:6:
.piolibdeps/dsmr/Crypto/AES.h:200:10: fatal error: hwcrypto/aes.h: No such file or directory
 #include "hwcrypto/aes.h"
          ^~~~~~~~~~~~~~~~
compilation terminated.
*** [.pioenvs\dsmr\src\esphome\components\dsmr\dsmr.cpp.o] Error 1
```

### Additional information

The entire build log: [bugreport-build-log.txt](https://github.com/esphome/issues/files/8956063/bugreport-build-log.txt)

### PR DESCRIPTION
**Pull request by sybrenstuvel**
# What does this implement/fix?

This fixes esphome/issues#3392 by upgrading `rweather/Crypto` from 0.2.0 to 0.4.0 (the latest release as of this date).

Not only does it solve the compiler issue, but I've also tested it on the actual hardware (ESP32 connecting to Dutch Smart Meter) and it works like a charm.

Fortunately, the DSMR component seems to be the only one that depends on `rweather/Crypto`, fortunately making this a relatively simple fix.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes esphome/issues#3392

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
esp32:
  board: frogboard
  framework:
    type: arduino
    version: 2.0.3
    platform_version: 4.4.0

# ... snip common config, like device name, wifi parameters, etc.

dsmr:
  uart_id: uart_dsmr
  request_interval: 5s

uart:
  id: uart_dsmr
  baud_rate: 115200
  rx_pin:
    number: GPIO21
    inverted: true
  rx_buffer_size: 1700

sensor:
  - platform: dsmr
    energy_delivered_tariff1:
      name: Energieverbruik Laagtarief
    energy_delivered_tariff2:
      name: Energieverbruik Hoogtarief
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

### CODE REVIEW

**Comment by jesserockz** [comment]
Duplicate of #3548

**Review by jesserockz — CHANGES_REQUESTED** [review]
You will also need to bump this in /platformio.ini to match.

**Review by jesserockz — APPROVED** [review]
