### PR TITLE
updated DHT22 delay time

### PR DESCRIPTION
**Pull request by pixitha**
## Description:

I had issues with DHT22 (+breakout board) that I just got (4 different DHTs). 4 different ESP8266 NodeMCU boards. All had the same problem, could never get any data from them.

Tested another DHT library, and they worked just fine.

https://github.com/beegee-tokyo/DHTesp

We (ssieb on discord) and I noticed the timing was the main difference between the two libraries. ESPHome uses 800 microseconds, and DHTesp uses 2000 microseconds (2 milliseconds).

I went in and setup a custom_component for the DHT library so we could edit the timing and I tested changing it to 2000 microseconds to match the other library and It works 100%.

`[17:14:05][D][dht:048]: Got Temperature=22.2°C Humidity=35.1%`

I tested various amounts of milliseconds. 0.8, 1, 1.2, 1.5, 2, 18

Only the 2+ milliseconds has worked for the DHT22. (note its milliseconds, not microseconds)

I also tested telling ESPHome it was a DHT11, but only ever got highly irregular results back.

It would be nice to see if we can get someone to test with a working setup, to see if it works for both systems, and that it does not break existing polling?

**Related issue (if applicable):** fixes #926 

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by pixitha** [comment]
Notes for doing the custom_component folder for anyone who happens to stumble on this post, thanks to @Bastian on discord for giving me the directions.

Having SSH access turned on will make things easier.

- Download a copy of the ESPhome repo from github (https://github.com/esphome/esphome)
- Grab the folder from the zip/clone from github (esphome/esphome/components/dht/)
- On your HA server that has esphome installed (I'm using the esphome-dev addon), go to /config/esphome/ directory.
- Create a new folder named `custom_components` inside of that directory.
- FTP or wget or scp the dht folder from the repo download inside of the custom_components folder.
- You should have this structure now on the HA server: `config/esphome/custom_components/dht`
- There should be 4 files in the DHT directory: `__init__.py, dht.cpp, dht.h, sensor.py`
- Open the dht.cpp file with vim: `vim +96 /config/esphome/custom_components/dht/dht.cpp`
- You should see this line of code: `    delayMicroseconds(800);`
- Change the value from 800 to 2000
- The line should now look like this: `      delayMicroseconds(2000);`
- Save and close the file
- Go to the ESPhome dashboard, find the board you have setup
- Hit the menu in the upper right for that board and choose, "Clean Build"
- Then once that is complete, use the same menu and choose "Compile"
- From here you can either download the binary for manual upload or just upload OTA to the existing device.
- To validate that the code is using the new value, you should see a new file being created in the `/config/esphome/custom_components/dht/` directory named `__pycache__`

Assuming this was the problem with your ESP and DHT22 in the first place, you should start to get temps/humidity now!

**Comment by Bastian** [comment]
> thanks to @Bastian on discord for giving me the directions.

You're welcome!
I'm always happy to take credit for things I didn't do :wink:

**Comment by andilge** [comment]
Thank you Kyle for all the assistance you provided.

Changing the delay from 800 to 2000 microseconds made my 3 dht22 work in esphome, all test were positive after changing this => ready to roll it out to productive environment.

**Comment by Basti-Fantasti** [comment]
@Bastian I assume he talked about me ;-)

But yes, I tested it with the 2000ms and it works for me as well!

**Comment by andilge** [comment]
works with esphome dev v1.15. but causes compiling errors in esphome stale v1.14.3.

Obviously not directly related to
delayMicroseconds(800);
Change the value from 800 to 2000

but maybe a stopper for fast rolling out to production

**Comment by Basti-Fantasti** [comment]
for me it works on the 1.14.3. What error does it throw up?

**Comment by andilge** [comment]
@Basti-Fantasti I get permanently

src/esphome/components/dht/dht.cpp: In member function 'bool esphome::dht::DHT::readsensor(float, float, bool)':
src/esphome/components/dht/dht.cpp:83:5: error: 'InterruptLock' was not declared in this scope
     InterruptLock lock;
     ^
src/esphome/components/dht/dht.cpp:83:19: error: expected ';' before 'lock'
     InterruptLock lock;
                   ^
*** [/data/esp_water_softener/.pioenvs/esp_water_softener/src/esphome/components/dht/dht.cpp.o] Error 1

with 1.14.3 stable.

**Comment by Basti-Fantasti** [comment]
@andilge can you post your dht.cpp, dht.h and sensor.py file? Or did you compare them to the original version which comes with 1.14.3?

and did you copy all needed files into the custom_components/dht esphome subfolder (dht.cpp, dht.h, sensor.py and __init__py)?

**Comment by andilge** [comment]
@Basti-Fantasti I downloaded to complete zipped repo from
https://github.com/esphome/esphome
extracted folder dht with the 4 contained files and copied it to
config/esphome/custom_components/dht

Then changed  dhc.cpp in line 96 from
      delayMicroseconds(800);
to
      delayMicroseconds(2000);

I'm using RasPi 3, Home Assistant 0.105.2, OS version 3.9 and esphome as official add-on from HA supervisor app store. This way esphome v 1.15 dev works fine form me, esphome 1.14.3 stable brings failures when compiling.

**Comment by glmnet** [comment]
There is a conversation going on about this issue and PR is already in review: https://github.com/esphome/esphome/pull/926

**Comment by pixitha** [comment]
I think fixing this with a single simple fix that covers both "types" is a better option than adding confusion by having multiple types. This PR is very simple while the other one is confusing and messy. The other PR was orig trying to solve this problem in a totally different way, which is why we opened this one instead.

**Comment by robinsmidsrod** [comment]
@pixitha The reason the other fix is more complex is because @OttoWinter asked for it, to avoid regressions with other variants of the DHT sensor. My patch started exactly as this one, but grew to accommodate his reasonable requests.

**Comment by glmnet** [comment]
I'm sorry but I'll close this PR, as @OttoWinter  say the 0.8ms implementation is needed and some people might get a breaking setup if this update reaches them.

We need another type or either an automatically fallback mechanism... see https://github.com/esphome/esphome/pull/926
