### ISSUE TITLE
Compile error with pulse_counter

### ISSUE THREAD

**Issue by ximex** [OttoWinter/esphomeyaml#14069]
### The problem

When i try to build with 2026.2.0 the pulse_counter component isn't compiling any more. worked with 2026.1.x before.

I have a esp32-c6

### Which version of ESPHome has the issue?

2026.2.0

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Component causing the issue

pulse_counter

### YAML Config

```yaml
sensor:
  - platform: pulse_counter
    pin: GPIXX
    name: "Pulse Counter"
```

### Anything in the logs that might be useful for us?

```txt
src/esphome/components/pulse_counter/pulse_counter_sensor.cpp: In member function 'virtual bool esphome::pulse_counter::HwPulseCounterStorage::pulse_counter_setup(esphome::InternalGPIOPin*)':
src/esphome/components/pulse_counter/pulse_counter_sensor.cpp:121:34: error: 'SOC_MOD_CLK_APB' was not declared in this scope; did you mean 'SOC_MOD_CLK_CPU'?
  121 |     esp_clk_tree_src_get_freq_hz(SOC_MOD_CLK_APB, ESP_CLK_TREE_SRC_FREQ_PRECISION_CACHED, &apb_freq);
      |                                  ^~~~~~~~~~~~~~~
      |                                  SOC_MOD_CLK_CPU
*** [.pioenvs/xxx/src/esphome/components/pulse_counter/pulse_counter_sensor.cpp.o] Error 1
```

**Comment by bdraco** [comment]
I was so focused on reviewing RMT in https://github.com/esphome/esphome/pull/13908 that we missed the pulse counter issue

**Comment by bdraco** [comment]
we shuold probably just go back toesp_clk_apb_freq even if its the private api

**Comment by bdraco** [comment]
Can you try https://github.com/esphome/esphome/pull/14070

**Comment by ximex** [comment]
works

**Comment by swoboda1337** [comment]
Didnt show up in the beta?

**Comment by ximex** [comment]
Didn't updated that one.
Maybe there ist still a Problem. Get different RPM. Instead of ~1000 i get 315.000

**Comment by swoboda1337** [comment]
> Didn't updated that one. Maybe there ist still a Problem. Get different RPM. Instead of ~1000 i get 315.000

I tested on esp32 with ledc at a fixed frequency and the new api seemed accurate:
```
output:
  - platform: ledc
    pin: GPIO19
    id: pulse_generator
    frequency: 1000Hz

# Connect GPIO19 -> GPIO18 with a jumper wire
sensor:
  - platform: pulse_counter
    pin: GPIO18
    name: "PCNT Test"
    update_interval: 5s
    internal_filter: 13us
    count_mode:
      rising_edge: INCREMENT
      falling_edge: DISABLE
```

**Comment by ximex** [comment]
i reflashed again with different settings:
- `use_pcnt: true`: ~280.000 (with and without dev branch fix)
- `use_pcnt: false`: ~3.600 (with external comp from dev branch - the fix you merged 2h ago was needed)
- with 2026.1.x: ~1.010
didn't change anything else. maybe something special with ESP32-C6?

**Comment by swoboda1337** [comment]
> with 2026.1.x: ~1.010 didn't change anything else. maybe something special with ESP32-C6?

That was with use_pcnt: true?

**Comment by swoboda1337** [comment]
> Maybe there ist still a Problem. Get different RPM. Instead of ~1000 i get 315.000

Is that 1 or 1000?

**Comment by ximex** [comment]
2026.1.x was without set `use_pcnt`. so should be `true`.
1010 vs 3600 vs 280000

**Comment by swoboda1337** [comment]
Ok that is helpful, I know some people use . to mean 1000 instead of a decimal :)

Yeah use_pcnt should be the default. I can test on C6 tonight

**Comment by ximex** [comment]
yeah in austria we write normally in `1.234.567,89` format. not compatible with development^^

**Comment by swoboda1337** [comment]
Its odd though that the hw (use_pcnt: true) count differs from the sw (use_pcnt: false). It doesnt match 2026.1 or 2026.2

**Comment by ximex** [comment]
confirm `use_pcnt` true is 1010 again. but with false it drifts between 900 and 3500
