### PR TITLE
[sntp] Merge multiple instances to fix crash and undefined behavior

### LINKED ISSUE #11899: sntp dump_config crash
### The problem

```
[00:23:08.937][C][sntp:059]: SNTP Time:
[00:23:08.948][C][sntp:062]:   Server 0Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.

[00:23:08.954]Core  1 register dump:
[00:23:08.960]PC      : 0x400014fd  PS      : 0x00060930  A0      : 0x80171019  A1      : 0x3ffc01c0  
[00:23:08.978]A2      : 0x00000000  A3      : 0xfffffffc  A4      : 0x000000ff  A5      : 0x0000ff00  
[00:23:08.979]A6      : 0x00ff0000  A7      : 0xff000000  A8      : 0x00000000  A9      : 0x00000000  
[00:23:08.982]A10     : 0x3ffba0b3  A11     : 0x3ffc03c3  A12     : 0x00000001  A13     : 0x00000001  
[00:23:08.993]A14     : 0x00000002  A15     : 0x00000000  SAR     : 0x00000013  EXCCAUSE: 0x0000001c  
[00:23:08.998]EXCVADDR: 0x00000000  LBEG    : 0x400014fd  LEND    : 0x4000150d  LCOUNT  : 0xffffffff  


[00:23:09.026]Backtrace: 0x400014fa:0x3ffc01c0 0x40171016:0x3ffc01d0 0x40168015:0x3ffc04f0 0x40168052:0x3ffc0580 0x400dbee5:0x3ffc05c0 0x400dc10e:0x3ffc0610 0x400e9fca:0x3ffc06f0 0x400e9ff6:0x3ffc0720 0x400e3340:0x3ffc0780 0x400e9275:0x3ffc07a0 0x400e8bf5:0x3ffc07c0 0x400eb5f2:0x3ffc07f0 0x400d5efe:0x3ffc0810
WARNING Found stack trace! Trying to decode it
WARNING Decoded 0x40171016: _svfprintf_r at /builds/idf/crosstool-NG/.build/xtensa-esp-elf/src/newlib/newlib/libc/stdio/vfprintf.c:1521
WARNING Decoded 0x40168015: _vsnprintf_r at /builds/idf/crosstool-NG/.build/xtensa-esp-elf/src/newlib/newlib/libc/stdio/vsnprintf.c:70
WARNING Decoded 0x40168052: vsnprintf at /builds/idf/crosstool-NG/.build/xtensa-esp-elf/src/newlib/newlib/libc/stdio/vsnprintf.c:40 (discriminator 1)
WARNING Decoded 0x400dbee5: esphome::logger::Logger::format_body_to_buffer_(char*, unsigned short*, unsigned short, char const*, __va_list_tag) at /home/ANT.AMAZON.COM/dwmw/esphome/.esphome/build/kitchen/src/esphome/components/logger/logger.h:421
 (inlined by) esphome::logger::Logger::format_log_to_buffer_with_terminator_(unsigned char, char const*, int, char const*, __va_list_tag, char*, unsigned short*, unsigned short) at /home/ANT.AMAZON.COM/dwmw/esphome/.esphome/build/kitchen/src/esphome/components/logger/logger.h:191
WARNING Decoded 0x400dc10e: esphome::logger::Logger::log_message_to_buffer_and_send_(unsigned char, char const*, int, char const*, __va_list_tag) at /home/ANT.AMAZON.COM/dwmw/esphome/.esphome/build/kitchen/src/esphome/components/logger/logger.h:208
 (inlined by) esphome::logger::Logger::log_vprintf_(unsigned char, char const*, int, char const*, __va_list_tag) at /home/ANT.AMAZON.COM/dwmw/esphome/.esphome/build/kitchen/src/esphome/components/logger/logger.cpp:40
WARNING Decoded 0x400e9fca: esphome::esp_log_vprintf_(int, char const*, int, char const*, __va_list_tag) at /home/ANT.AMAZON.COM/dwmw/esphome/.esphome/build/kitchen/src/esphome/core/log.cpp:32
WARNING Decoded 0x400e9ff6: esphome::esp_log_printf_(int, char const*, int, char const*, ...) at /home/ANT.AMAZON.COM/dwmw/esphome/.esphome/build/kitchen/src/esphome/core/log.cpp:14
WARNING Decoded 0x400e3340: esphome::sntp::SNTPComponent::dump_config() at /home/ANT.AMAZON.COM/dwmw/esphome/.esphome/build/kitchen/src/esphome/components/sntp/sntp_component.cpp:62
WARNING Decoded 0x400e9275: esphome::Component::call_dump_config() at /home/ANT.AMAZON.COM/dwmw/esphome/.esphome/build/kitchen/src/esphome/core/component.cpp:142
WARNING Decoded 0x400e8bf5: esphome::Application::loop() at /home/ANT.AMAZON.COM/dwmw/esphome/.esphome/build/kitchen/src/esphome/core/application.cpp:196 (discriminator 1)
WARNING Decoded 0x400eb5f2: loop() at /home/ANT.AMAZON.COM/dwmw/esphome/ufh.yaml:207
WARNING Decoded 0x400d5efe: esphome::loop_task(void*) at /home/ANT.AMAZON.COM/dwmw/esphome/.esphome/build/kitchen/src/esphome/components/esp32/core.cpp:94 (discriminator 1)

```

Reverting commit e212ed024d80bf6b03b0ce5786ca5c294f791e27 (#11525) appears to make it go away.

### Which version of ESPHome has the issue?

dev

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Component causing the issue

sntp

### YAML Config

```yaml
https://git.infradead.org/?p=users/dwmw2/esp32-pool.git;a=blob_plain;f=kitchen.yaml;hb=HEAD

There are two NTP servers, one Legacy IP address and one name timeless.aa.net.uk which resolves to both IPv6 and Legacy IP.
```

### Anything in the logs that might be useful for us?

```txt

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by bdraco**
# What does this implement/fix?

Fixes a crash in the SNTP component introduced by PR #11525 where `dump_config()` causes a LoadProhibited exception on ESP32 devices when multiple SNTP time instances are configured.

**Problem:**
PR #11525 replaced `std::vector<std::string>` with `std::array<const char*, SNTP_SERVER_COUNT>` to reduce heap usage. When multiple SNTP time instances are configured with different numbers of servers, `cg.add_define()` is called multiple times, causing the generated `defines.h` to contain multiple definitions of `SNTP_SERVER_COUNT`. The last definition wins, causing all instances to compile with the same array size even though constructor calls have different numbers of initializer elements. This results in uninitialized array elements (nullptr) which crash when `dump_config()` attempts to log them.

**Background:**
Multiple SNTP instances have always been undefined behavior. The underlying ESP platform APIs (`configTime()` on ESP8266, `esp_sntp_*` on ESP32) only support a single NTP client configuration - calling them multiple times means whichever instance initialized last would overwrite the previous configuration. The crash introduced in PR #11525 made this latent issue immediately visible rather than silently causing undefined behavior.

**Solution:**
Implement SNTP instance merging similar to how OTA handles multiple platform configurations. When multiple SNTP time instances are configured:
- All instances are automatically merged into a single SNTP component
- Server lists are combined and deduplicated (preserving order)
- If more than 3 servers result from merging, excess servers are dropped with a warning (SNTP protocol limitation)
- Only one `SNTP_SERVER_COUNT` define is generated, preventing the macro redefinition issue
- Users are warned when merging occurs

This approach:
- **Prevents the crash**: Only one SNTP instance means no macro redefinition conflicts
- **Fixes undefined behavior**: Ensures only one NTP client configuration is active (matches ESP API expectations)
- **Matches OTA behavior**: Follows established pattern for platform component merging
- **No breaking changes**: Existing single-instance configs continue to work unchanged
- **Helpful warnings**: Users are informed when merging occurs and when servers are dropped

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes https://github.com/esphome/esphome/issues/11899

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- N/A (no user-facing configuration changes - internal fix only)

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx
- [ ] nRF52840

## Example entry for `config.yaml`:

```yaml
# This configuration previously crashed - now merges into single instance
time:
  - platform: sntp
    servers:
      - 192.168.1.1
      - pool.ntp.org
  - platform: sntp
    servers:
      - pool.ntp.org      # Deduplicated
      - 192.168.1.2

# Results in single SNTP instance with servers: [192.168.1.1, pool.ntp.org, 192.168.1.2]
# Warning logged: "Found and merged 2 SNTP time configurations into one instance"
```

## Technical Details

**Files Modified:**
1. `esphome/components/sntp/time.py`:
   - Added `CONF_SNTP` constant (local to component)
   - Added `_sntp_final_validate()` function with proper typing
   - Merges multiple SNTP instances into one using `merge_config()`
   - Deduplicates servers using `dict.fromkeys()` (preserves insertion order)
   - Warns when dropping servers beyond 3-server limit
   - Validates that manually-specified IDs are consistent
   - Uses constants (`CONF_TIME`, `CONF_PLATFORM`) instead of string literals
   - Set as `FINAL_VALIDATE_SCHEMA` to run during final validation phase

2. `tests/component_tests/sntp/`:
   - Created comprehensive unit tests covering:
     - Single instance (no merge)
     - Multiple instances merging
     - Server deduplication with order preservation
     - Excess server dropping with warnings
     - Inconsistent manual ID validation error
     - Merging with other time platforms (e.g., homeassistant)
   - All 7 tests pass

**Why instance merging?**
- ESP platform APIs only support a single NTP client configuration (multiple instances = undefined behavior)
- Calling ESP APIs multiple times means the last call wins, silently overwriting previous configurations
- Merging makes the intended behavior explicit and deterministic
- Matches the pattern used by OTA platform component
- Prevents the macro redefinition issue entirely
- Simple and maintainable solution

**Memory Impact:**
- Same memory usage as PR #11525 (array-based storage)
- Still ~72 bytes savings compared to original `std::vector<std::string>` implementation
- No additional overhead from merging (happens at config generation time)

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by swoboda1337** [comment]
Why not just error if there is more than one?

File: esphome/components/sntp/time.py [hunk 1]
```diff
@@ -12,13 +17,74 @@
...
+    other_time_configs: list[ConfigType] = []
+
+    for time_conf in time_confs:
+        if time_conf.get(CONF_PLATFORM) == CONF_SNTP:
+            sntp_configs.append(time_conf)
+        else:
+            other_time_configs.append(time_conf)
+
+    if len(sntp_configs) <= 1:
+        return
```
Comment (swoboda1337) [inline esphome/components/sntp/time.py:50]: Could save ~40 lines if we just throw an error?

Comment (bdraco) [reply esphome/components/sntp/time.py:50]: I chose merging over erroring for several reasons:

Making this an error would break any existing configs (including vendor-shipped configs) that have multiple SNTP instances. While those configs were technically broken (undefined behavior), they "worked" in that they didn't crash until #11525. The missing validation has been a problem for a very long time, so it's likely a lot more users are affected than just the tiny sample we get in beta, including vendor configs that have been shipping for months or years.

This also follows the same pattern we use for OTA platform merging - keeps things consistent.

As a general policy, Home Assistant and ESPHome have tried not to make breaking changes when already in beta (and only in exceptional circumstances after release when we really have something wrong or for security reasons). Breaking changes at this stage can scare off testers, which we desperately need. If we want to make this a breaking change, we should do it in 6 months with proper deprecation.

When we can detect the problem and fix it automatically (merging the instances), that's better than forcing users to manually update their configs.

Made for ESPHome vendors (and unofficial ones) and commercial partners understandably complain when we make breaking changes without notice, especially when they realize we didn't have to break their configs. Users complain as well, though they're less likely to know we could have avoided it. Keeping it friendly for them is important.

The merging logic handles edge cases like deduplication and the 3-server limit, so the extra complexity gives us real value in backward compatibility and user experience. The maintenance burden is low - similar to OTA platform merging, it's likely we won't need to touch this code again.

**Review by jesserockz — APPROVED** [review]
