### PR TITLE
Update esp32 arduino and platform versions

### PR DESCRIPTION
**Pull request by jesserockz**
# What does this implement/fix?

Follows on from and closes #2605

Left as a draft for testing
Relies on #3566 

## Breaking Changes:

- TLK110 Ethernet driver removed

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
external_components:
  - source: github://pr#3564
  	refresh: 0s
    components: 
      - esp32
      - esp32_camera
      - ethernet_info
      - ethernet
      - shelly_dimmer
      - wifi
      - dallas

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by SeByDocKy** [comment]
Is-it possibile to test this PR on hassio   via ?
```
external_components:
  - source: github://pr#3564
  
 ```

**Comment by wizardwatch** [comment]
How do you test pull requests? I tried the above code and it asked for a specific component.

**Comment by jesserockz** [comment]
@wizardwatch I have added an example yaml in the description on how this can be tested. This PR only changes the defaults used so its easy enough to test without `external_components`

**Comment by wizardwatch** [comment]
I can not build with version 4.4.0 of the platform version, I get the error `Unknown development platform ‘espressif32’`

Using version 4.3.0 and below makes it further  but breaks the Ethernet component, I believe https://github.com/espressif/esp-idf/issues/3825 is related as I get the same error as mentioned there. The relevant configuration is 
```
esp32:
  board: wesp32
  framework:
    version: 2.0.3
    platform_version: 4.3.0
ethernet:
  type: LAN8720
```

**Comment by ssieb** [comment]
Try deleting the platformio cache.  Probably in `~/.platformio` if you're running locally or rebuild the addon if you're using that.

**Comment by wizardwatch** [comment]
I am using the addon. I deleted the data in `/config/esphome/.esphome/build` as that was the closest thing I could find. I am still getting the same error `src/esphome/components/ethernet/ethernet_component.cpp:8:10: fatal error: eth_phv/phy_lan8720.h: No such file or directory `

**Comment by ssieb** [comment]
> src/esphome/components/ethernet/ethernet_component.cpp:8:10: fatal error: eth_phv/phy_lan8720.h: No such file or directory

Did you copy and paste that or retype it?  `eth_phv` is wrong, it should be `eth_phy`.

But the files I said to delete are not under `/config`.  That's why I said you would probably have to rebuild or re-install the addon to get rid of them.

**Comment by SeByDocKy** [comment]
> I can not build with version 4.4.0 of the platform version, I get the error `Unknown development platform ‘espressif32’`
> 
> Using version 4.3.0 and below makes it further but breaks the Ethernet component, I believe [espressif/esp-idf#3825](https://github.com/espressif/esp-idf/issues/3825) is related as I get the same error as mentioned there. The relevant configuration is
> 
> ```
> esp32:
>   board: wesp32
>   framework:
>     version: 2.0.3
>     platform_version: 4.3.0
> ethernet:
>   type: LAN8720
> ```

I have also exactly the same error on my HASSIO :( Odroid C4
EDIT. Finally, with the last dev, I can download the last toolchain correctly and now it's compiling fine :) 👍

**Comment by wizardwatch** [comment]
> > src/esphome/components/ethernet/ethernet_component.cpp:8:10: fatal error: eth_phv/phy_lan8720.h: No such file or directory
> 
> Did you copy and paste that or retype it? `eth_phv` is wrong, it should be `eth_phy`.
> 
> But the files I said to delete are not under `/config`. That's why I said you would probably have to rebuild or re-install the addon to get rid of them.

I retyped it, my bad. Reinstalling the addon got rid of the espressif32 error but not other one. I also tried the dev branch and cannot build with that. I believe this is relevant https://github.com/esphome/feature-requests/issues/1462#issuecomment-1163289052 . Sorry if I am missing something.

**Comment by devoh747** [comment]
Sorry for this newb question but I am trying to learn the process. Will this be coming out of DRAFT and into a PR that can get pulled into Dev?  I am really keen on getting some of those board fixes like [#3357](https://github.com/esphome/issues/issues/3357) .

**Comment by ssieb** [comment]
Looks like https://github.com/esphome/issues/issues/3400 is a problem for regular ESP32 as well.

**Comment by ssieb** [comment]
https://github.com/esphome/esphome/pull/3667 will fix the test4 failure.

**Comment by devoh747** [comment]
> #3667 will fix the test4 failure.

You mean test1 right?  Test4 is for <eth_phy/phy_lan8720.h> not being found.

**Comment by ssieb** [comment]
You are correct, not sure what happened there.  Test1 is the adc, test2 and test4 are Ethernet.

**Comment by jenscski** [comment]
Updating to Arduino 2.0.3 will break Dallas
https://github.com/esphome/issues/issues/3401

**Comment by jesserockz** [comment]
Note to self: Fix ethernet dump config types

**Comment by jenscski** [comment]
I have taken a look that the problem with gpio appeared in Arduino 2.0.3 in https://github.com/esphome/esphome/pull/3998
