### ISSUE TITLE
Bug Report: pulse_counter component fails to compile with ESPHome 2026.2.0 / ESP-IDF 5.5.2

### ISSUE THREAD

**Issue by RoboKaren** [OttoWinter/esphomeyaml#14115]
### Description

The `pulse_counter` component fails to compile after upgrading to ESPHome 2026.2.0. The component includes `driver/pulse_cnt.h`, which is no longer available at that path in ESP-IDF 5.5.2 (framework-espidf @ 3.50502.0), which was bundled with this release.

### Steps to Reproduce

1. Use a configuration with the `pulse_counter` platform (e.g. a Geiger counter or flow meter)
2. Compile with ESPHome 2026.2.0 targeting an ESP32 with `framework: espidf`
3. Compilation fails

### Expected Behavior

Project compiles successfully as it did with the previous ESPHome version.

### Actual Behavior

Compilation fails with:

```
In file included from src/esphome/components/pulse_counter/pulse_counter_sensor.cpp:1:
src/esphome/components/pulse_counter/pulse_counter_sensor.h:12:10: fatal error: driver/pulse_cnt.h: No such file or directory
   12 | #include <driver/pulse_cnt.h>
          |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

### Environment

- **ESPHome version:** 2026.2.0
- **ESP-IDF version:** 5.5.2 (framework-espidf @ 3.50502.0)
- **Platform:** pioarduino platform-espressif32 @ 55.03.37
- **Board:** esp32dev
- **Framework:** espidf

### Root Cause (suspected)

ESP-IDF 5.x reorganized legacy driver header paths. The `driver/pulse_cnt.h` include path used in `pulse_counter_sensor.h` appears to have been moved or removed in ESP-IDF 5.5.2. This worked correctly in the previous ESPHome release which used an older ESP-IDF version.

### Workaround

Rolling back to the previous ESPHome version restores functionality. 

Or get someone to patch the pulse_counter component, specifically the file esphome/components/pulse_counter/pulse_counter_sensor.h at line 12, where it includes <driver/pulse_cnt.h>.

### Which version of ESPHome has the issue?

2026.2.0

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Component causing the issue

pulse_counter

### YAML Config

```yaml
esphome:
  name: esp-geiger-rgb90
  friendly_name: esp-geiger-rgb90

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "xxxxx"

ota:
  - platform: esphome
    password: "xxxxxx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Geiger-Rgb90"
    password: "xxxxx"

captive_portal:


globals:
  - id: pulse_history
    type: int[60]
    restore_value: no
    initial_value: "{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}"

  - id: pulse_index
    type: int
    restore_value: no
    initial_value: "0"

  - id: pulse_sum
    type: int
    restore_value: no
    initial_value: "0"

output:
  - platform: gpio
    pin:
      number: 2
      mode: output
      ignore_strapping_warning: true
    id: greenLED



sensor:
  - platform: pulse_counter
    id: geiger_cps
    internal: true
    pin:
      number: 34
      inverted: True
      mode:
        input: True
        pullup: false
        pulldown: false
    unit_of_measurement: 'CPS'
    name: 'Ionizing Radiation Power CPS'
    count_mode:
      rising_edge: DISABLE
      falling_edge: INCREMENT
    use_pcnt: false        
    internal_filter: 100ms
    accuracy_decimals: 0
    update_interval: 1s
    filters:
      delta: 1
    on_raw_value:
      then:
        - lambda: |-
            x=round(x/60); // esphome calculating based on pulses per minute. round required to avoid problem when esphome calc value less than 60 pulses per minute (for example 59.7)
            id(pulse_sum) -= id(pulse_history)[id(pulse_index)]; // remove old value from overall sum
            id(pulse_history)[id(pulse_index)] = x; // 'x' is the raw pulse count
            id(pulse_sum) += x; // add new value to overall sum

            id(pulse_index)++; // change array index where next value will be stores
            if (id(pulse_index) >= 60) id(pulse_index) = 0; // Reset at 60
    on_value:
      then:
        - component.update: geiger_cpm
        - output.turn_on: greenLED
        - delay: 10ms
        - output.turn_off: greenLED

  - platform: template
    id: geiger_cpm
    unit_of_measurement: 'CPM'
    name: 'Ionizing Radiation Power CPM'
    accuracy_decimals: 0
    update_interval: 1s
    state_class: measurement
    lambda: return id(pulse_sum);
    filters:
      delta: 1

  - platform: copy
    source_id: geiger_cpm
    id: ionizing_radiaton_power
    unit_of_measurement: 'µSv/h'
    name: 'Ionizing Radiation Power'
    state_class: measurement
    icon: mdi:radioactive
    accuracy_decimals: 3
    filters:
      - skip_initial: 15
      - sliding_window_moving_average: # 15 measurements moving average (MA5) here
          window_size: 15
          send_every: 1
      - multiply: 0.0057 # 0.0057 original value or 0.00332 for J305 by IoT-devices tube conversion factor of pulses into uSv/Hour
```

### Anything in the logs that might be useful for us?

```txt
Compiling .pioenvs/esp-geiger-rgb90/src/esphome/components/pulse_counter/pulse_counter_sensor.cpp.o In file included from src/esphome/components/pulse_counter/pulse_counter_sensor.cpp:1: src/esphome/components/pulse_counter/pulse_counter_sensor.h:12:10: fatal error: driver/pulse_cnt.h: No such file or directory    12 | #include <driver/pulse_cnt.h>       |          ^~~~~~~~~~~~~~~~~~~~ compilation terminated. *** [.pioenvs/esp-geiger-rgb90/src/esphome/components/pulse_counter/pulse_counter_sensor.cpp.o] Error 1 ========================= [FAILED] Took 14.33 seconds =========================
```
