### PR TITLE
[packet_transport] Fix packet size check to account for round4 padding

### LINKED ISSUE #13151: espnow.packet_transport: exceed packet size error when chunking data
### The problem

When using espnow between several controllers, I found that most packet_transport objects threw an error message to the log saying that the packet was too large.  By manually chunking my sensors (58 total + 11 binary_sensors) in individual packet_transport id's of ~10 each, the error would go away.  However, when I bundle the entire set into one id all the _data came across_ in spite of the error message.

I think the error message might be in error.

### Which version of ESPHome has the issue?

2025.12.0

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Component causing the issue

espnow.packet_transport?

### YAML Config

```yaml
# this is included as a package.
# if the two packets, below, are combined, the transport component will 
# throw an error every cycle, remove the comments and the errors go away.
# 
#INFO Successful handshake with vancontroller @ 192.168.8.107 in 0.049s
#[09:35:06.516][E][espnow.transport:047]: Packet too large: 252 bytes (max 250)
#[09:35:16.509][E][espnow.transport:047]: Packet too large: 252 bytes (max 250)


substitutions:
  transport: espnow

espnow:
  auto_add_peer: true

packet_transport:  #!include transport_packets.yaml
  - platform: ${transport}
    id: battery1_packet
    update_interval: 10s
    sensors:
      - battery1current
      - battery1voltage
      - battery1size
      - battery1capacity
      - battery1cycles

#  - platform: ${transport}
#    id: battery1a_packet
#    update_interval: 10s
#    sensors:
      - battery1_v_cell1
      - battery1_v_cell2
      - battery1_v_cell3
      - battery1_v_cell4
      - battery1_t_cell1
      - battery1_t_cell2
      - battery1_t_cell3
      - battery1_t_cell4
```

### Anything in the logs that might be useful for us?

```txt
INFO Successful handshake with vancontroller @ 192.168.8.107 in 0.049s
[09:35:06.516][E][espnow.transport:047]: Packet too large: 252 bytes (max 250)
[09:35:16.509][E][espnow.transport:047]: Packet too large: 252 bytes (max 250)
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by swoboda1337**
# What does this implement/fix?

Fix false positive "Packet too large" errors in ESP-NOW packet transport. The size checks in `add_data_()` and `add_binary_data_()` used unrounded sizes, but `flush_()` creates buffers with rounded sizes using `round4()`. This mismatch caused spurious "Packet too large: 252 bytes (max 250)" errors when data was close to the 250-byte ESP-NOW limit, despite successful data transmission.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Developer breaking change (an API change that could break external components)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes https://github.com/esphome/esphome/issues/13151

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- N/A (no documentation changes needed)

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx
- [ ] nRF52840

## Example entry for `config.yaml`:

```yaml
# No config changes - this is a bugfix for existing functionality
# Affects configurations using espnow.packet_transport with many sensors
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by larrybarello** [comment]
I included the yaml for the external component and it failed to compile 2025.12.0  "format_hex_pretty_size" not declared lines 270 and 513  Same failure after updating to 2025.12.5
```
src/esphome/components/packet_transport/packet_transport.cpp: In member function 'void esphome::packet_transport::PacketTransport::flush_()':
src/esphome/components/packet_transport/packet_transport.cpp:270:16: error: 'format_hex_pretty_size' was not declared in this scope; did you mean 'format_hex_pretty_char'?
  270 |   char hex_buf[format_hex_pretty_size(PACKET_MAX_LOG_BYTES)];
      |                ^~~~~~~~~~~~~~~~~~~~~~
      |                format_hex_pretty_char
src/esphome/components/packet_transport/packet_transport.cpp: In member function 'void esphome::packet_transport::PacketTransport::process_(const std::vector<unsigned char>&)':
src/esphome/components/packet_transport/packet_transport.cpp:513:20: error: 'format_hex_pretty_size' was not declared in this scope; did you mean 'format_hex_pretty_char'?
  513 |       char hex_buf[format_hex_pretty_size(PACKET_MAX_LOG_BYTES)];
      |                    ^~~~~~~~~~~~~~~~~~~~~~
      |                    format_hex_pretty_char
*** [.pioenvs\vancontroller\src\esphome\components\packet_transport\packet_transport.cpp.o] Error 1

```

**Comment by swoboda1337** [comment]
Will have to use dev, too many changes to core

**Review by bdraco — APPROVED** [review]

**Comment by swoboda1337** [comment]
Thanks
