### PR TITLE
[midea] Add ESP-IDF framework support

### PR DESCRIPTION
**Pull request by ShaTie**
# What does this implement/fix?

Add ESP-IDF framework support for the Midea climate component by removing `USE_ARDUINO` guards and the `cv.only_with_arduino` restriction.

This enables using the Midea component with ESP-IDF framework, which is required for features like MQTT over TLS.

All frameworks now use upstream `dudanov/MideaUART` pinned at the commit that merged ESP-IDF support (dudanov/MideaUART#27); there is no release containing it yet, so the pin should move to a registry version once one is tagged. This also moves existing Arduino users from the published `1.1.9` release to that main-branch commit — the Arduino-facing changes between the two are include reshuffling only (platform shims moved into `Helpers/Platform.h`), so the risk is low, but the Arduino build does change.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Developer breaking change (an API change that could break external components)
- [x] Code quality improvements to existing code or addition of tests
- [x] Other

**Related issue or feature (if applicable):**

- Upstream library support merged in https://github.com/dudanov/MideaUART/pull/27

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- N/A (no documentation changes needed)

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx
- [ ] nRF52840

## Example entry for `config.yaml`:

```yaml
esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

uart:
  tx_pin: GPIO21
  rx_pin: GPIO20
  baud_rate: 9600

climate:
  - platform: midea
    name: "Air Conditioner"
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

---

**Note:** dudanov/MideaUART#27 is merged; the library is pinned to the merge commit on upstream main until a release containing ESP-IDF support is published.

### CODE REVIEW

**Comment by DjordjeMandic** [comment]
Im willing to test with esp32c3 or even esp32c6 which is idf only.

**Comment by heeeyflo** [comment]
Can confirm: me & @ShaTie tested on a real AC sold under the Lessar brand – works fine.

Lessar AC with a custom ESP32-C3 SuperMini

image

**Comment by DjordjeMandic** [comment]
Works with ESP32-C3 with ESPHome 2025.12.2

**Comment by DjordjeMandic** [comment]
Please mark this PR as draft until it's ready for review.

**Review by swoboda1337 — CHANGES_REQUESTED** [review]
ESP8266 is broken see my comments on https://github.com/dudanov/MideaUART/pull/27

**Comment by ShaTie** [comment]
@swoboda1337, thank you very much for finishing this work!

**Comment by jonathanschiefer** [comment]
I tried to compile for ESP32H2 (which doesn't have wifi, but is thread only) and it failed (`MideaUART/include/Frame/FrameData.h:38:(.text._ZN7dudanov5midea13ApplianceBase19m_sendNetworkNotifyENS0_9FrameTypeE+0x50): undefined reference to `esp_wifi_sta_get_ap_info'`). Is there a way to get this working without wifi?

**Comment by DjordjeMandic** [comment]
Hey,

I'm suddenly getting this error during validation:
```
INFO ESPHome 2026.2.4
INFO Reading configuration /config/esphome/livingroom-samsung-ac.yaml...
INFO Updating https://github.com/esphome/esphome.git@pull/12646/head
ERROR Unable to load component midea.climate:
Traceback (most recent call last):
  File "/esphome/esphome/loader.py", line 206, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/data/external_components/e0864618/esphome/components/midea/climate.py", line 182, in <module>
    @register_action("follow_me", FollowMeAction, MIDEA_FOLLOW_ME_SCHEMA)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/external_components/e0864618/esphome/components/midea/climate.py", line 56, in register_action
    registerer = automation.register_action(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: register_action() got an unexpected keyword argument 'synchronous'
Failed config

Platform not found: 'climate.midea'
```

Config:
```yaml
climate:
  - platform: midea
    id: midea_climate
    name: Living room AC        # Use a unique name.
    period: 1s                  # Optional
    timeout: 2s                 # Optional
    num_attempts: 3             # Optional
    autoconf: false              # Autoconfigure most options.
    beeper: true                # Beep on commands.
    visual:                     # Optional. Example of visual settings override.
      min_temperature: 17 °C    # min: 17
      max_temperature: 30 °C    # max: 30
      temperature_step: 1 °C    # min: 1
    supported_modes:            # All capabilities in this section detected by autoconf.
      - FAN_ONLY                # This capability is always used.
      - HEAT_COOL
      - COOL
      - HEAT
      - DRY
    supported_presets:          # All capabilities in this section detected by autoconf.
      - BOOST
      - SLEEP  
    supported_swing_modes:
      - VERTICAL                # This capability is always used.
    outdoor_temperature:        # Optional. Outdoor temperature sensor (may display incorrect values after long inactivity).
      name: "Outdoor Air Temperature"
    on_state: 
      then:
        lambda: |-
          if (x.current_temperature >= 37.0f) {
            ESP_LOGW("main", "Follow me transaction failed, ac got temp: %.0f", x.current_temperature);
          }

sensor:
  - platform: copy
    source_id: dht_temp
    id: dht_temp_follow_me
    internal: true
    filters:
      - throttle: 10s
      - heartbeat: 1min
      - debounce: 1s
    on_value:
      if:
        condition:
          switch.is_on: follow_room_temp_sw
        then:
          midea_ac.follow_me:
            temperature: !lambda "return x;"

script:
  - id: follow_me_30c
    mode: single
    then:
      midea_ac.follow_me:
        temperature: 30
  - id: follow_me_17c
    mode: single
    then:
      midea_ac.follow_me:
        temperature: 17

button:
  - platform: template
    name: "Follow Me Target Reached"
    icon: mdi:hvac-off
    on_press:
      - lambda: |-
          if (id(midea_climate).mode == CLIMATE_MODE_COOL) {
            id(follow_me_17c).execute();
          }
          if (id(midea_climate).mode == CLIMATE_MODE_HEAT) {
            id(follow_me_30c).execute();
          }
```

Could someone test this PR with follow me action?

With arduino framework and public 2025.2.4 it validates the config without any issues, adding this PR as external component makes it fail both on arduino and on esp-idf

**Comment by swoboda1337** [comment]
> Hey,
> 
> I'm suddenly getting this error during validation:
> 
> Could someone test this PR with follow me action?
> 
> With arduino framework and public 2025.2.4 it validates the config without any issues, adding this PR as external component makes it fail both on arduino and on esp-idf

Need to use dev there was a change that touched all actions.

**Comment by swoboda1337** [comment]
You can also use a commit ref to use an older version of this pr.

**Comment by DjordjeMandic** [comment]
> > Hey,
> > I'm suddenly getting this error during validation:
> > Could someone test this PR with follow me action?
> > With arduino framework and public 2025.2.4 it validates the config without any issues, adding this PR as external component makes it fail both on arduino and on esp-idf
> 
> Need to use dev there was a change that touched all actions.

I can wait until it gets released, any info in what version would this change be released?

**Comment by swoboda1337** [comment]
> I can wait until it gets released, any info in what version would this change be released?

This PR has to get merged first https://github.com/dudanov/MideaUART/pull/27 and @ShaTie has to fix a bug in that PR first.

**Comment by DjordjeMandic** [comment]
> > I can wait until it gets released, any info in what version would this change be released?
> 
> This PR has to get merged first [dudanov/MideaUART#27](https://github.com/dudanov/MideaUART/pull/27) and @ShaTie has to fix a bug in that PR first.


Sorry for confusion, i meant change that touched all actions, so that i can use it as external component.
> Need to use dev there was a change that touched all actions.

**Comment by swoboda1337** [comment]
Either wait till 2026.4 or do something like this to pin the external component to a point before dev was merged:
```
  external_components:
    - source:
        type: git
        url: https://github.com/ShaTie/esphome
        ref: 9675016d758a
      components: [midea]
```

**Comment by cbossaers** [comment]
Any progress on this? I'm failing to make it work on a WaveShare C5 board.

**Comment by swoboda1337** [comment]
Looks like the midea pr was merged

**Comment by swoboda1337** [comment]
@esphbot review

**Review by esphbot — CHANGES_REQUESTED** [review]
> [!WARNING]
> Important issues found.
>
> - No config-time guard that WiFi is available — ESP32 variants without a WiFi PHY now fail at link time

**Comment by swoboda1337** [comment]
@esphbot review

**Review by esphbot — CHANGES_REQUESTED** [review]
> [!WARNING]
> Important issues found.
>
> - New shared UART package file is missing a trailing newline

**Comment by swoboda1337** [comment]
The file does end with a trailing newline - checked the blob at HEAD directly, it terminates with 0x0a. Nothing to change here.

**Comment by swoboda1337** [comment]
@esphbot review

**Review by esphbot — APPROVED** [review]
> [!TIP]
> No blocking issues found — ready to merge.

**Review by swoboda1337 — APPROVED** [review]

**Comment by swoboda1337** [comment]
Thanks!
