### PR TITLE
[web_server] Fix v1 compilation on ESP-IDF by adding missing write method

### LINKED ISSUE #13123: web_server_v1 IDF fails to compile
### The problem

Compiling for an ESP32-C6 with the V1 webserver will fail due to a missing stream write function. 

### Which version of ESPHome has the issue?

2026.1.0-dev

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Component causing the issue

web_server

### YAML Config

```yaml
esphome:
  name: idftest
  friendly_name: IDFTest

esp32:
  board: esp32-c6-devkitc-1
  flash_size: 4MB
  variant: esp32c6
  framework:
    type: esp-idf
    version: recommended

wifi:
  ssid: bla

ota:
  - platform: web_server

web_server:
  port: 80
  version: 1
```

### Anything in the logs that might be useful for us?

```txt
Compiling .pioenvs/grpm2-324e18/src/esphome/components/web_server_idf/utils.cpp.o
src/esphome/components/web_server/web_server_v1.cpp: In function 'void esphome::web_server::write_html_escaped(esphome::web_server_idf::AsyncResponseStream*, const char*)':
src/esphome/components/web_server/web_server_v1.cpp:25:17: error: 'class esphome::web_server_idf::AsyncResponseStream' has no member named 'write'
   25 |         stream->write(*p);
      |                 ^~~~~
Compiling .pioenvs/grpm2-324e18/src/esphome/components/web_server_idf/web_server_idf.cpp.o
*** [.pioenvs/grpm2-324e18/src/esphome/components/web_server/web_server_v1.cpp.o] Error 1
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by bdraco**
# What does this implement/fix?

Fixes compilation failure for `web_server` version 1 on ESP32 with ESP-IDF framework.

The `AsyncResponseStream` class in `web_server_idf.h` was missing a `write()` method that is called by the `write_html_escaped()` function in `web_server_v1.cpp`. This was introduced in #12627 when HTML escaping was added.

The error was:
```
error: 'class esphome::web_server_idf::AsyncResponseStream' has no member named 'write'
```

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Developer breaking change (an API change that could break external components)
- [x] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes https://github.com/esphome/esphome/issues/13123

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- N/A

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx
- [ ] nRF52840

## Example entry for `config.yaml`:

```yaml
web_server:
  version: 1
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by swoboda1337 — APPROVED** [review]

**Comment by bdraco** [comment]
thanks

**Comment by GelidusResearch** [comment]
Hi Guys,
I did a test with full YAML on our PR, there is still an issue with the SELECT component (Maybe others, I have not checked yet).
The "option" var is already in c_str format, compiler seems to hate it calling c_str() with that input. IDF does not like it, Arduino is Ok with calling c_str() on a const char * input.

```src/esphome/components/web_server/web_server_v1.cpp: In lambda function:
src/esphome/components/web_server/web_server_v1.cpp:205:31: error: request for member 'c_str' in 'option', which is of non-class type 'const char* const'
  205 |           stream.print(option.c_str());
```

Verified with this edit removing the c_str() function:
```
#ifdef USE_SELECT
  for (auto *obj : App.get_selects()) {
    if (this->include_internal_ || !obj->is_internal()) {
      write_row(stream, obj, "select", "", [](AsyncResponseStream &stream, EntityBase *obj) {
        select::Select *select = (select::Select *) obj;
        stream.print("<select>");
        stream.print("<option></option>");
        for (auto const &option : select->traits.get_options()) {
          stream.print("<option>");
          stream.print(option);
          stream.print("</option>");
        }
        stream.print("</select>");
      });
    }
  }
#endif

**Comment by bdraco** [comment]
https://github.com/esphome/esphome/pull/13169
