### PR TITLE
[opentherm] Fix ESP-IDF build by re-enabling legacy driver component

### PR DESCRIPTION
**Pull request by bdraco**
# What does this implement/fix?

Fix opentherm component build failure on ESP32 with ESP-IDF framework after #13664 excluded the `driver` IDF component by default.

The opentherm component uses the legacy timer API (`driver/timer.h`) which requires the `driver` IDF component. This PR re-enables it for opentherm and adds TODO comments noting future migration to the GPTimer API (`driver/gptimer.h`).

Error before fix:
```
src/esphome/components/opentherm/opentherm.h:16:10: fatal error: driver/timer.h: No such file or directory
```

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Developer breaking change (an API change that could break external components)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes build regression from #13664

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- N/A

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx
- [ ] LN882x
- [ ] nRF52840

## Example entry for `config.yaml`:

```yaml
# Standard opentherm config - no changes needed
opentherm:
  in_pin: GPIO4
  out_pin: GPIO5
```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by swoboda1337 — APPROVED** [review]

**Comment by bdraco** [comment]
thanks
