### PR TITLE
[http_request] on_response body must be owned

### LINKED ISSUE #5987: repeat action in http_request.get on_response handler fails to compile
### The problem

The repeat action can't be used inside the http_request `on_response` handler anymore because of a compile failure.

This is a regression from 2024.6.2 and the first bad commit is 0179358f9cbb212d30627999a2f7233ff18e12ea

### Which version of ESPHome has the issue?

2024.6.3+

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

_No response_

### What platform are you using?

ESP8266

### Board

d1_mini

### Component causing the issue

http_request

### Example YAML snippet

```yaml
esphome:
  name: reproduce
  platform: ESP8266
  board: d1_mini
  on_boot:
    - priority: -100
      then:
        - http_request.get:
            url: "https://esphome.io/"
            on_response:
              then:
                - repeat:
                    count: 3
                    then:

wifi:
  ssid: "abcdefgh"
  password: "12345678"

http_request:
  useragent: esphome
  timeout: 2s
  id: http_request_data
  verify_ssl: false
```

### Anything in the logs that might be useful for us?

```txt
src/main.cpp: In function 'void setup()':
src/main.cpp:149:99: error: use of deleted function 'esphome::RepeatAction<std::shared_ptr<esphome::http_request::HttpContainer>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&>::RepeatAction()'
  149 |   repeataction_id = new RepeatAction<std::shared_ptr<http_request::HttpContainer>, std::string &>();
      |                                                                                                   ^
In file included from src/esphome.h:18,
                 from src/main.cpp:3:
src/esphome/core/base_automation.h:273:32: note: 'esphome::RepeatAction<std::shared_ptr<esphome::http_request::HttpContainer>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&>::RepeatAction()' is implicitly deleted because the default definition would be ill-formed:
  273 | template<typename... Ts> class RepeatAction : public Action<Ts...> {
      |                                ^~~~~~~~~~~~
src/esphome/core/base_automation.h:273:32: error: no matching function for call to 'std::tuple<std::shared_ptr<esphome::http_request::HttpContainer>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&>::tuple()'
In file included from /home/me/.platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/functional:54,
                 from /home/me/.platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/pstl/glue_algorithm_defs.h:13,
                 from /home/me/.platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/algorithm:74,
                 from /home/me/.platformio/packages/framework-arduinoespressif8266/cores/esp8266/Arduino.h:229,
                 from src/esphome/components/esp8266/gpio.h:6,
                 from src/esphome.h:4,
                 from src/main.cpp:3:
```

### Additional information

0179358f9cbb212d30627999a2f7233ff18e12ea is the first bad commit
commit 0179358f9cbb212d30627999a2f7233ff18e12ea

    Improve 'body' handling in http_request on_response triggers (#6968)

 esphome/codegen.py                             |  1 +
 esphome/components/http_request/__init__.py    |  2 +-
 esphome/components/http_request/http_request.h | 19 ++++++++++++++-----
 esphome/cpp_types.py                           |  1 +
 4 files changed, 17 insertions(+), 6 deletions(-)

### PR DESCRIPTION
**Pull request by afflux**
# What does this implement/fix?

https://github.com/esphome/esphome/pull/6968 changed the response_body to a reference of string to avoid copies when passing the string by value. However, the owned string will be deallocated right after the call to process(), so actions such as delay and wait_until would be passed an invalid reference. ~Additionally, wait_until, while and repeat will not compile anymore, since they store their arguments in a default-constructed member - which fails for references.~ (fixed by #7972)

~This PR instead uses a shared_ptr, which will still avoid the copies between each action. However, users must now dereference the body argument in their on_response lambdas to get the std::string, therefore it is a breaking change.~ (fixed by #11704)

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes https://github.com/esphome/issues/issues/5987

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

N/A

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [x] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
esphome:
  name: reproduce
  platform: ESP8266
  board: d1_mini
  on_boot:
    - priority: -100
      then:
        - http_request.get:
            url: "https://example.com/"
            on_response:
              then:
                - repeat:
                    count: 3
                    then:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_psk

http_request:
  useragent: esphome
  timeout: 2s
  id: http_request_data
  verify_ssl: false
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by afflux** [comment]
still relevant

**Comment by bdraco** [comment]
@afflux would you please rebase

**Comment by afflux** [comment]
Sure. I think with the change from https://github.com/esphome/esphome/pull/11464, I can skip the `shared_ptr` and just change it it back to a non-ref std::string...

**Comment by afflux** [comment]
Well, I had another look at the disassembly and realized that all functions in the call tree below `Trigger::trigger()` will create copies of their arguments when passing them to the next function, so every std::string is copied at least three times before it even reaches the first action. I'm therefore now back to shared_ptr.

This has another caveat: [if allocation for the uint8 buffer failed](https://github.com/esphome/esphome/pull/7923/files#diff-1cf5bd82614da7ca2744ef3946b1ab6842d7652822ba1f00fc5c34ad6abd94bcR247), the shared_ptr will be empty, with UB when dereferencing it. So the breakage is even bigger, as every user has to check for validity and then dereference the body. We could just not call the trigger in this case and log an error.

Alternative to this, we could put some effort into reworking the automation trigger functions to properly use references and std::forward/std::move, to reduce the number of copies needed. (We could keep the current, slightly odd behavior of passing the empty string to the trigger when allocation failed.)

**Comment by X-Ryl669** [comment]
Can't you use a const reference here instead ? It would avoid using the heap (and/or stack) to transmit the string argument.
If the pass by const ref doesn't work, what about moving the string to the levels below the first pass by value?

**Comment by afflux** [comment]
See #11704 - it's a const reference already. To be perfectly honest, I'm not sure we still need this PR now (not much of a C++ wizard, no ideas what will happen with the double reference) but I guess it's cleaner this way.

**Comment by X-Ryl669** [comment]
I don't know about the context. In your patch, you're changing a string reference to a value. This implies that any function in the callstack below this function will make a copy of the string (and thus, call the heap to allocate a buffer to copy the string content into). If the code works with a value, it's likely to work with a const reference (unless it's modifying the string's **content** in its scope). So instead of `string &` becoming `string`, make it `const string &` instead. That tells the compiler to only pass the address to the object below, which is fast and ensure there's no modification to the object. Most of the time, there isn't so it should be almost free win here.

In the worst case, if one of the function need to modify the string content, **and** none of the function above in the callstack use it afterward, you can pass the string by r-value (make it `string &&`) and move the string (with `std::move(variable)`) instead.

**Comment by afflux** [comment]
I'm sorry, it doesn't make sense to argue without context. Please see the recently merged #11704, which is changing every argument to actions to const ref.

**Comment by afflux** [comment]
@bdraco: let me know if you think we still need this PR. AFAICS, with #11704 merged, this now boils down to a minor cleanup
