### ISSUE TITLE
2025.7.0 does not compile on BK7231T (WB3S)

### ISSUE THREAD

**Issue by mvoss96** [OttoWinter/esphomeyaml#9602]
### The problem

Hi,
since the update to 2025.7.0 my device absed on libretiny BK7231T WB3s does no longer compile.
it fails with error:
/root/.platformio/lib/RPAsyncTCP/src/async_config.h:9:25: error: 'MBED_CONF_LWIP_TCP_MSS' was not declared in this scope

### Which version of ESPHome has the issue?

2025.7.0

### What type of installation are you using?

Docker

### What platform are you using?

BK72XX

### YAML Config

```yaml
esphome:
  name: tv-backlight
  friendly_name: TV Backlight

# Example configuration entry for BK72xx
bk72xx:
  board: wb3s

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Tv-Backlight Fallback Hotspot"
    password: ""

captive_portal:

binary_sensor:
  - platform: status
    name: "Status"

  - platform: gpio
    pin:
      number: P14
      mode: INPUT_PULLUP
      inverted: true
    name: "Power Button"
    disabled_by_default: true
    on_click:
      - light.toggle: leds

sensor:
  - platform: uptime
    name: "Uptime Sensor"

  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

output:
  - platform: libretiny_pwm
    id: output_red
    pin: PWM3

  - platform: libretiny_pwm
    id: output_green
    pin: PWM4

  - platform: libretiny_pwm
    id: output_blue
    pin: PWM5

  - platform: libretiny_pwm
    id: output_white
    pin: PWM0
    
light:
  - platform: rgbw
    name: "RGBW_Controller"
    id: leds
    red: output_red
    green: output_green
    blue: output_blue
    white: output_white
    color_interlock: True
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2025.7.0
INFO Reading configuration /config/tv-backlight.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing tv-backlight (board: wb3s; framework: arduino; platform: libretiny @ 1.9.1)
--------------------------------------------------------------------------------
Warning! Non-Git installations are NOT SUPPORTED.
HARDWARE: BK7231T 120MHz, 256KB RAM, 1.03MB Flash
 - framework-arduino-api @ 2022.8.24+sha.237b10a 
 - framework-beken-bdk @ 0.0.0+v2021.06.07.sha.6491b8c 
 - library-flashdb @ 1.2.0+sha.d5c892f 
 - library-freertos @ 9.0.0+sha.95cc959 
 - library-freertos-port @ 2025.1.18+sha.dbfc408 
 - library-lwip @ 2.2.0-bdk+sha.48da4a2 
 - library-printf @ 6.1.0+sha.28a79bd 
 - library-uf2ota @ 5.0.0+sha.f955412 
PLATFORM VERSIONS:
 - libretiny @ 1.9.1
 - ltchiptool @ 4.12.0
CUSTOM OPTIONS:
 - fw_name = esphome
 - fw_version = 2025.7.0
Dependency Graph
|-- AsyncTCP @ 3.4.5
|-- ESPAsyncWebServer @ 3.7.10
|-- DNSServer @ 1.1.0
|-- noise-c @ 0.1.10
Compiling .pioenvs/tv-backlight/lib46e/RPAsyncTCP/SyncClient.cpp.o
In file included from /config/.esphome/platformio/platforms/libretiny/cores/common/base/config/lwipopts.h:12,
                 from /config/.esphome/platformio/platforms/libretiny/cores/beken-72xx/base/config/lwipopts.h:5,
                 from /config/.esphome/platformio/packages/library-lwip/src/include/lwip/opt.h:51,
                 from /config/.esphome/platformio/packages/library-lwip/src/include/lwip/ip_addr.h:40,
                 from /root/.platformio/lib/RPAsyncTCP/src/RPAsyncTCP.h:24,
                 from /root/.platformio/lib/RPAsyncTCP/src/SyncClient.cpp:7:
/config/.esphome/platformio/packages/library-lwip/port/lwipopts.h:418: warning: "TCP_MSS" redefined
  418 | #define TCP_MSS                 (1500 - 40)
      | 
In file included from /root/.platformio/lib/RPAsyncTCP/src/SyncClient.h:14,
                 from /root/.platformio/lib/RPAsyncTCP/src/SyncClient.cpp:6:
/root/.platformio/lib/RPAsyncTCP/src/async_config.h:9: note: this is the location of the previous definition
    9 |   #define TCP_MSS       MBED_CONF_LWIP_TCP_MSS        //(1460)
      | 
Compiling .pioenvs/tv-backlight/libd4b/ESPAsyncWebServer/WebRequest.cpp.o
Compiling .pioenvs/tv-backlight/libd4b/ESPAsyncWebServer/WebResponses.cpp.o
Compiling .pioenvs/tv-backlight/libd4b/ESPAsyncWebServer/WebServer.cpp.o
/root/.platformio/lib/RPAsyncTCP/src/async_config.h:9:25: error: 'MBED_CONF_LWIP_TCP_MSS' was not declared in this scope
    9 |   #define TCP_MSS       MBED_CONF_LWIP_TCP_MSS        //(1460)
      |                         ^~~~~~~~~~~~~~~~~~~~~~
/root/.platformio/lib/RPAsyncTCP/src/SyncClient.h:40:34: note: in expansion of macro 'TCP_MSS'
   40 |     SyncClient(size_t txBufLen = TCP_MSS);
      |                                  ^~~~~~~
/root/.platformio/lib/RPAsyncTCP/src/async_config.h:9:25: error: 'MBED_CONF_LWIP_TCP_MSS' was not declared in this scope
    9 |   #define TCP_MSS       MBED_CONF_LWIP_TCP_MSS        //(1460)
      |                         ^~~~~~~~~~~~~~~~~~~~~~
/root/.platformio/lib/RPAsyncTCP/src/SyncClient.h:41:55: note: in expansion of macro 'TCP_MSS'
   41 |     SyncClient(AsyncClient *client, size_t txBufLen = TCP_MSS);
      |                                                       ^~~~~~~
*** [.pioenvs/tv-backlight/lib46e/RPAsyncTCP/SyncClient.cpp.o] Error 1
========================== [FAILED] Took 5.30 seconds ==========================
```
