### ISSUE TITLE
'Wire' was not declared in this scope

### ISSUE THREAD

**Issue by FuNK3Y** [OttoWinter/esphomeyaml#12528]
### The problem

Since `2025.12` I cannot use `Wire` anymore. This used to work fine with `2025.11` and below. Could be related to https://github.com/esphome/esphome/pull/12076

I went through the release note and found no mention of deprecation. I am more than happy to revise my syntax if I am doing it wrong.

### Which version of ESPHome has the issue?

2015.12

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Component causing the issue

esphome

### YAML Config

```yaml
esphome:
  name: "house-weather-station"
  friendly_name: House - Weather station
  on_boot:
    - priority: 800
      then:
        - lambda: |- # Turn on the power of the display
            Wire.beginTransmission(0x34);
            Wire.write((uint8_t[]){0x95, 0x1C}, 2);
            Wire.endTransmission();

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  framework:
    type: arduino

i2c:
  sda: GPIO47
  scl: GPIO48
  scan: true
```

### Anything in the logs that might be useful for us?

```txt
/config/house-weather-station.yaml: In lambda function:
/config/house-weather-station.yaml:8:7: error: 'Wire' was not declared in this scope
    8 |             Wire.beginTransmission(0x34);
      |       ^   
Compiling .pioenvs/house-weather-station/lib80b/Network/NetworkManager.cpp.o
*** [.pioenvs/house-weather-station/src/main.cpp.o] Error 1
```

**Comment by FuNK3Y** [comment]
So, I was able to figure out the proper syntax myself:
````
esphome:
  name: "house-weather-station"
  friendly_name: House - Weather station
  on_boot:
    - priority: 800 # Turn the screen on
      then:
      - lambda: |-
          id(bus).write(0x34, (uint8_t[]){0x95, 0x1C}, 2);

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  framework:
    type: esp-idf

i2c:
  sda: GPIO47
  scl: GPIO48
  scan: true
  id: bus
````
Feel free to close this issue. I am letting it open to let you take the shot whether this regression is worth mentioning in the doc

**Comment by ssieb** [comment]
It's not a regression.  Using `Wire` was never "supported".  If you use the display id instead, you can drop the address parameter.
