### PR TITLE
[Tuya Climate] Fix compilation error caused by codegen

### LINKED ISSUE #5707: Tuya climate compilation error
### The problem

I'm getting the following compilation error when trying to update my ME-81H thermostat:
`src/main.cpp: In function 'void setup()':
src/main.cpp:360:41: error: invalid conversion from 'const char*' to 'uint8_t' {aka 'unsigned char'} [-fpermissive]
  360 |   tuya_tuyaclimate->set_active_state_id("datapoint");
      |                                         ^~~~~~~~~~~
      |                                         |
      |                                         const char*
In file included from src/esphome.h:54,
                 from src/main.cpp:3:
src/esphome/components/tuya/climate/tuya_climate.h:18:36: note:   initializing argument 1 of 'void esphome::tuya::TuyaClimate::set_active_state_id(uint8_t)'
   18 |   void set_active_state_id(uint8_t state_id) { this->active_state_id_ = state_id; }
      |                            ~~~~~~~~^~~~~~~~`

### Which version of ESPHome has the issue?

2024.4.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.4.3

### What platform are you using?

ESP8266

### Board

_No response_

### Component causing the issue

tuya climate

### Example YAML snippet

```yaml
substitutions:
  device_name: warm-floor

packages:
  device_common: !include .device_common.yaml

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m

logger:
  baud_rate: 0

uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

tuya:
  time_id: sntp_time
  status_pin:
    number: 14
    inverted: true

climate:
  - platform: tuya
    name: "Warm floor"
    switch_datapoint: 1
    target_temperature_datapoint: 16
    target_temperature_multiplier: 1.0
    current_temperature_datapoint: 24
    current_temperature_multiplier: 0.1
    active_state:
      datapoint: 36
      heating_value: 0

switch:
  - platform: "tuya"
    name: "Warm floor lock"
    switch_datapoint: 40

select:
  - platform: "tuya"
    name: "Warm floor sensor selection"
    enum_datapoint: 43
    options:
      0: Internal
      1: Floor
      2: Both
```

### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by zry98**
# What does this implement/fix?

This fixes compilation error in Tuya Climate component described in https://github.com/esphome/issues/issues/5707

which is caused by multiple errors in the code generator introduced by the commit https://github.com/esphome/esphome/pull/5159/commits/be23153a68e509958e107b34a9c59ee3daeab5ae

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/issues/issues/5707

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by jesserockz — APPROVED** [review]
Wow, that was a horrible mess. Thanks for fixing
