### ISSUE TITLE
LVGL Arc angles cannot be changed

### ISSUE THREAD

**Issue by dirkjankrijnders** [OttoWinter/esphomeyaml#12642]
### The problem

I’m encountering unexpected behaviour with the arc component of LGVL. With this definition:
```
lvgl:
  pages:
    - id: main_page
      widgets:
        - arc:
            id: lv_arc_0
            x: 90
            y: 120
            width: 75
            height: 75
            value: 100
            min_value: -10
            max_value: 100
            adjustable: false
            start_angle: 170
            end_angle: 280
```
I expect:

But I get:

It looks like setting the `start_angle` and `end_angle` are not set

### Which version of ESPHome has the issue?

2025.12.0

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Component causing the issue

lvgl

### YAML Config

```yaml
substitutions:
  devicename: "segment-turntable"

esphome:
  name: $devicename
  build_path: ./build/$devicename
  #includes:
  #  - pl_display.h
  #on_boot:
  #  - display.page.show: welcome_page
  #  - component.update: my_display

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .krijnders.net

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  #ap:
  #  ssid: "Test Fallback Hotspot"
  #  password: "aUnU3CaiJYRA"
esp32:
  variant: ESP32
  # board: esp32dev
  # framework:
    # type: arduino
  framework:
    type: esp-idf
logger:
  

mqtt:
  broker: loki.krijnders.net
  port: 1883
  username: ha
  password: qwer1234
  client_id: screen_01
  keepalive: 60s
  # on_message:
  #   - topic: tuin/ota_mode
  #     payload: 'ON'
  #     then:
  #       - deep_sleep.prevent: deep_sleep_1
  #   - topic: tuin/sleep_mode
  #     payload: 'ON'
  #     then:
  #       - deep_sleep.enter: deep_sleep_1
  birth_message:
    topic: $devicename/status
    payload: online
  will_message:
    topic: $devicename/status
    payload: offline

ota:
  platform: esphome

# captive_portal:

http_request:
  useragent: esphome/device
  timeout: 1s
  id: http_request_data
  verify_ssl: false

spi:
  - id: lcd
    clk_pin: GPIO14
    mosi_pin: GPIO13
    miso_pin: 
      number: 12
      #ignore_strapping_warning: true
  #- id: touch
  #  clk_pin: GPIO25
  #  mosi_pin: GPIO32
  #  miso_pin: GPIO39

i2c:
  sda: GPIO33
  scl: GPIO32
  scan: true
  id: bus_a
  frequency: 400kHz

uart:
  baud_rate: 115200
  rx_pin: GPIO3
  tx_pin: GPIO1

external_components:
  - source: github://eigger/espcomponents@latest
    components: [ uartex ]
    refresh: always

uartex:
  rx_timeout: 10ms
  rx_footer: "\n" #add a termination character if one is present.

sensor:
  - platform: template
    name: "Angle"
    id: angle
    # state_number: 0
    on_value: 
      then:
        - lvgl.arc.update:
            id: arc_id
            value: !lambda return x;

text_sensor:
  - platform: uartex
    name: "text"
    id: uart_output
    lambda: |-
      //id(angle).publish_state(13.);
      if (len <= 6) return "";
      auto line = std::string(reinterpret_cast<const char*>(data), len);
      int comma_idx = line.find(",");
      if (comma_idx == std::string::npos) return "";
      int msg_id = std::stoi(line.substr(0, comma_idx));
      if (msg_id == 1) {
        int second_idx = line.find(",", comma_idx + 2);
        if (second_idx == std::string::npos) return "";
          id(angle).publish_state(std::stof(line.substr(comma_idx+1, second_idx)));
      };
      return line;
#     lambda: |-
#      auto line = std::string(reinterpret_cast<const char*>(data), len);
#      ESP_LOGD("uart", line.c_str());
#      return line;
    #on_value: 
    #  then:
    #    - component.update: my_display


lvgl:
  pages:
    - id: welcome_page
      widgets:
        - arc:
            x: 10
            y: 10
            id: arc_id
            value: 100
            min_value: -10
            max_value: 100
            adjustable: false
            start_angle: 170
            end_angle: 280



          
    
color:
  - id: my_red
    red: 100%
    green: 0%
    blue: 0%
  - id: my_orange
    red: 100%
    green: 50%
    blue: 0%
  - id: my_yellow
    red: 100%
    green: 100%
    blue: 0%
  - id: my_green
    red: 0%
    green: 100%
    blue: 0%
  - id: my_blue
    red: 0%
    green: 0%
    blue: 100%
  - id: my_teal
    red: 0%
    green: 100%
    blue: 100%
  - id: my_gray
    red: 70%
    green: 70%
    blue: 70%
  - id: my_white
    red: 100%
    green: 100%
    blue: 100%
  - id: bg_ginger
    red: 63%
    green: 55%
    blue: 0%
  - id: fg_purple
    red: 63%
    green: 5%
    blue: 63%

font:
  - file: "Helvetica.ttf"
    id: helvetica_48
    size: 48
  - file: "Helvetica.ttf"
    id: helvetica_36
    size: 36
  - file: "Helvetica.ttf"
    id: helvetica_24
    size: 24
  - file: "Helvetica.ttf"
    id: helvetica_18
    size: 18
  - file: "Helvetica.ttf"
    id: helvetica_12
    size: 12

#image:
#  - file: "power-off-button.png"
#    id: on_off_button
#    type: RGB565
#  - file: "radio-station.png"
#    id: radio
#    type: RGB565

binary_sensor:
  - platform: status
    name: "Node Status"
    id: system_status

  # - platform: touchscreen
  #   name: Power
  #   x_min: 30
  #   x_max: 90
  #   y_min: 20
  #   y_max: 80

  # - platform: touchscreen
  #   name: Music
  #   x_min: 150
  #   x_max: 210
  #   y_min: 20
  #   y_max: 80


display:
  - platform: ili9xxx
    model: ILI9341
    spi_id: lcd
    cs_pin: 15
    dc_pin: 2
    rotation: 90
    id: my_display
    invert_colors: false
    update_interval: 1s
    color_palette: 8BIT
    #pages:
    #- id: welcome_page
    #  lambda: |-
    #    it.fill(bg_ginger);
    #    it.printf(0, 0, id(helvetica_24), "%0.1f", id(angle).state);
#        it.printf(0, 0, id(helvetica_24), "%s", id(uart_output).state);


# Define pins for backlight display and back LED1
output:
  - platform: ledc
    pin: GPIO27
    id: former_led_pin
    channel: 7
    frequency: "5000Hz"
  - platform: ledc
    id: output_red
    pin: GPIO4
    inverted: true
  - platform: ledc
    id: output_green
    pin: GPIO16
    inverted: true
  - platform: ledc
    id: output_blue
    pin: GPIO17
    inverted: true

# Define a monochromatic, dimmable light for the backlight
light:
  - platform: monochromatic
    output: former_led_pin
    name: "Display Backlight"
    id: back_light
    restore_mode: ALWAYS_ON
  - platform: rgb
    name: LED
    red: output_red
    id: led
    green: output_green
    blue: output_blue
    restore_mode: ALWAYS_OFF

# touchscreen:
#   platform: cst860
#   id: my_touchscreen
#   i2c_id: bus_a
#   # touchscreen:
#   #   platform: xpt2046
#   #   id: my_touchscreen
#   #   spi_id: touch
#   #   cs_pin: 33
#   #   interrupt_pin: 36
#   update_interval: 50ms
#   report_interval: 1s
#   #   threshold: 400
#   #   calibration_x_min: 3860
#   #   calibration_x_max: 280
#   #   calibration_y_min: 340
#   #   calibration_y_max: 3860
#   #   swap_x_y: false
#   on_touch:
#       - lambda: |-
#             ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
#                 id(my_touchscreen).x,
#                 id(my_touchscreen).y,
#                 id(my_touchscreen).x_raw,
#                 id(my_touchscreen).y_raw
#                 );
  # # Exposed switches.
switch:
  - platform: restart
    name: ESP32-2432S028 Restart
```

### Anything in the logs that might be useful for us?

```txt

```

**Comment by ssieb** [comment]
Were there supposed to be pictures?

**Comment by sblogoshs** [comment]
I have also noticed the problem. The „start_angle and end_angle“ It no longer functions; for me, it should be 360°.
All my "arc" on four displays are "top_layer" and all look like in the picture. The "arc" display is not permanent but only indicates a status.

![Image](https://github.com/user-attachments/assets/b445a1ab-0523-4f61-919e-33e9117c63b7)

The problem began with 2025.12, and reverting a single device back to 2025.11 does not work either, apparently because the associated data is not all reset.

**Comment by widget** [comment]
```yaml
esphome:
  name: arctest

host:

logger:

display:
  - platform: sdl
    id: disp0
    dimensions:
      width: 700
      height: 200
    auto_clear_enabled: false 

touchscreen:
  - platform: sdl
    id: touch0
    display: disp0
    sdl_id: disp0

          
lvgl:
    layout:
        type: flex
        flex_flow: row
        flex_align_main: space_evenly
        flex_align_track: center
        flex_align_cross: stretch

    widgets:
      - arc:
          id: arc_value_id
          value: 75
          min_value: 0
          max_value: 100
      - arc:
          id: arc_angle_id
          start_angle: 215
          end_angle: 330
```

These should look different.  I'm assuming it's something from [PR 12066](https://github.com/esphome/esphome/pull/12066) which allows `(start|end)_angle` to be updated, and the example yaml in that does indeed dynamically change it.

**Comment by widget** [comment]
~~In fact yes of course this fixes it~~

```yaml
on_boot:
  - lvgl.arc.update: 
      id: whatever
      start_angle: 10
      end_angle: 180
```
This does *not* fix it - any update to the widget resets the values with crazy results.  Trying `on_value` makes things very confusing.

**Comment by clydebarrow** [comment]
> I expect:
> 
> But I get:

It would be helpful if this information was actually provided.

**Comment by widget** [comment]
Just tried your PR in dev, success!

<img width="692" height="191" alt="Image" src="https://github.com/user-attachments/assets/cd14473c-60c2-466e-939c-d75dfec84040" />

(without)

<img width="647" height="192" alt="Image" src="https://github.com/user-attachments/assets/7b937d32-eea4-4cfc-88ad-41093a78f9cb" />

I assume it depends on something else as it doesn't work from 2025.12.3, so I'll wait to see it in main.  Thanks!

```
Traceback (most recent call last):
  File "/home/widget/infra/builder_esphome/.direnv/python-3.13.7/bin/esphome", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/home/widget/infra/builder_esphome/.direnv/python-3.13.7/lib/python3.13/site-packages/esphome/__main__.py", line 1508, in main
    return run_esphome(sys.argv)
  File "/home/widget/infra/builder_esphome/.direnv/python-3.13.7/lib/python3.13/site-packages/esphome/__main__.py", line 1495, in run_esphome
    rc = POST_CONFIG_ACTIONS[args.command](args, config)
  File "/home/widget/infra/builder_esphome/.direnv/python-3.13.7/lib/python3.13/site-packages/esphome/__main__.py", line 793, in command_run
    exit_code = write_cpp(config)
  File "/home/widget/infra/builder_esphome/.direnv/python-3.13.7/lib/python3.13/site-packages/esphome/__main__.py", line 486, in write_cpp
    generate_cpp_contents(config)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/widget/infra/builder_esphome/.direnv/python-3.13.7/lib/python3.13/site-packages/esphome/__main__.py", line 498, in generate_cpp_contents
    CORE.flush_tasks()
    ~~~~~~~~~~~~~~~~^^
  File "/home/widget/infra/builder_esphome/.direnv/python-3.13.7/lib/python3.13/site-packages/esphome/core/__init__.py", line 794, in flush_tasks
    self.event_loop.flush_tasks()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/widget/infra/builder_esphome/.direnv/python-3.13.7/lib/python3.13/site-packages/esphome/coroutine.py", line 341, in flush_tasks
    next(task.iterator)
    ~~~~^^^^^^^^^^^^^^^
  File "/home/widget/infra/builder_esphome/.direnv/python-3.13.7/lib/python3.13/site-packages/esphome/__main__.py", line 475, in wrapped
    await coro(conf)
  File "/home/widget/infra/builder_esphome/data/external_components/b136ffb2/esphome/components/lvgl/__init__.py", line 305, in to_code
    await add_widgets(lv_scr_act, config)
  File "/home/widget/infra/builder_esphome/data/external_components/b136ffb2/esphome/components/lvgl/widgets/__init__.py", line 429, in add_widgets
    await widget_to_code(w_cnfig, w_type, parent.obj)
  File "/home/widget/infra/builder_esphome/data/external_components/b136ffb2/esphome/components/lvgl/widgets/__init__.py", line 451, in widget_to_code
    var = lv_Pvariable(lv_obj_t, wid)
  File "/home/widget/infra/builder_esphome/data/external_components/b136ffb2/esphome/components/lvgl/lvcode.py", line 356, in lv_Pvariable
    decl = VariableDeclarationExpression(type, "*", name, static=True)
TypeError: VariableDeclarationExpression.__init__() got an unexpected keyword argument 'static'
```

**Comment by clydebarrow** [comment]
Yeah, that is caused by https://github.com/esphome/esphome/pull/12616 which has both core and LVGL changes and is not yet in the release version.
