### ISSUE TITLE
homeassistant.tag_scanned` causes Build-Error 'HomeAssistantServiceCallAction' in ESPHome 2025.8.0

### ISSUE THREAD

**Issue by RalfAlbers** [OttoWinter/esphomeyaml#10383]
### The problem

after upgrading from 2025.7.5 to 2025.8.0 the build is broken with the Error "src/main.cpp:36:6: error: 'HomeAssistantServiceCallAction' in namespace 'esphome::api' does not name a template type"
When I remove the line "      - homeassistant.tag_scanned: !lambda 'return x;'" the build is successful. 

The Error stays also after esphome clean build-files

### Which version of ESPHome has the issue?

2025.8.0

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Component causing the issue

esphome::api

### YAML Config

```yaml
esphome:
  name: rfid-wallbox
  # If buzzer is enabled, notify on api connection success
  on_boot:
    priority: -10
    then:
    - wait_until:
        api.connected:
    - logger.log: API is connected!
    - rtttl.play: "scale_up:d=32,o=5,b=100:c,c#,d#,e,f#,g#,a#,b"


substitutions:
  # Modify variables based on your settings
  hostname: rfid-wallbox

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
    
ota:
  platform: esphome
  password: "df16a36a614318f4d544cf701a700887"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

spi:
  clk_pin: GPIO14
  miso_pin: GPIO12
  mosi_pin: GPIO13

rc522_spi:
  reset_pin: GPIO5
  cs_pin: GPIO4
  update_interval: 1s
  on_tag:
    then:
      - homeassistant.tag_scanned: !lambda 'return x;'
      - text_sensor.template.publish:
          id: rfid_wallbox_tag
          state: !lambda 'return x;'
      - if:
          condition:
            api.connected:
          then:
            - rtttl.play: "two short:d=4,o=5,b=100:16e6,16e6"
output:
- platform: esp8266_pwm
  pin: GPIO15
  id: buzzer

rtttl:
  output: buzzer

sensor:
  - platform: wifi_signal
    name: $hostname WiFi Signal
    update_interval: 60s
  - platform: uptime
    name: $hostname Uptime

text_sensor:
  - platform: version
    name: $hostname ESPHome Version
  - platform: wifi_info
    ssid:
      name: $hostname WiFi
  - platform: template
    name: "RFID Tag"
    id: rfid_wallbox_tag
    icon: mdi:id-card

switch:      
  - platform: restart
    name: $hostname restart
    
  - platform: template
    id: rfid_wallbox_tag_reset
    name: "Reset RFID Tag"
    turn_on_action:
      - text_sensor.template.publish:
          id: rfid_wallbox_tag
          state: 'unknown'
      - switch.turn_off:
          id: rfid_wallbox_tag_reset
    assumed_state: off

    
binary_sensor:
  - platform: status
    name: $hostname status
    
captive_portal:
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2025.8.0
INFO Reading configuration /config/esphome/rfid-wallbox.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing rfid-wallbox (board: nodemcuv2; framework: arduino; platform: platformio/espressif8266@4.2.1)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
Dependency Graph
|-- ESPAsyncTCP @ 2.0.0
|-- ESP8266WiFi @ 1.0
|-- ESPAsyncWebServer @ 3.7.10
|-- DNSServer @ 1.1.1
|-- ESP8266mDNS @ 1.2
|-- SPI @ 1.0
Compiling .pioenvs/rfid-wallbox/src/main.cpp.o
src/main.cpp:36:6: error: 'HomeAssistantServiceCallAction' in namespace 'esphome::api' does not name a template type
   36 | api::HomeAssistantServiceCallAction<std::string> *api_homeassistantservicecallaction_id;
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/main.cpp: In function 'void setup()':
src/main.cpp:390:3: error: 'api_homeassistantservicecallaction_id' was not declared in this scope
  390 |   api_homeassistantservicecallaction_id = new api::HomeAssistantServiceCallAction<std::string>(api_apiserver_id, true);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/main.cpp:390:52: error: 'HomeAssistantServiceCallAction' in namespace 'esphome::api' does not name a template type
  390 |   api_homeassistantservicecallaction_id = new api::HomeAssistantServiceCallAction<std::string>(api_apiserver_id, true);
      |                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/main.cpp:390:94: error: expected primary-expression before '>' token
  390 |   api_homeassistantservicecallaction_id = new api::HomeAssistantServiceCallAction<std::string>(api_apiserver_id, true);
      |                                                                                              ^
src/main.cpp:390:96: warning: left operand of comma operator has no effect [-Wunused-value]
  390 |   api_homeassistantservicecallaction_id = new api::HomeAssistantServiceCallAction<std::string>(api_apiserver_id, true);
      |                                                                                                ^~~~~~~~~~~~~~~~
/config/esphome/rfid-wallbox.yaml:103:124: error: cannot convert '<brace-enclosed initializer list>' to 'const std::vector<esphome::Action<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >*, std::allocator<esphome::Action<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >*> >&'
  103 | #          condition:
      |                                                                                                                            ^
In file included from src/esphome/components/binary_sensor/filter.h:3,
                 from src/esphome/components/binary_sensor/binary_sensor.h:5,
                 from src/esphome/core/application.h:26,
                 from src/esphome/components/api/api_frame_helper.h:12,
                 from src/esphome/components/api/api_connection.h:5,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/core/automation.h:289:56: note:   initializing argument 1 of 'void esphome::Automation<Ts>::add_actions(const std::vector<esphome::Action<Ts ...>*>&) [with Ts = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >}]'
  289 |   void add_actions(const std::vector<Action<Ts...> *> &actions) { this->actions_.add_actions(actions); }
      |                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
*** [.pioenvs/rfid-wallbox/src/main.cpp.o] Error 1
========================== [FAILED] Took 5.67 seconds ==========================
```

### Additional information

This Setup was running with 2025.7.5

**Comment by RalfAlbers** [comment]
fixed with https://github.com/esphome/esphome/issues/10263
